package com.xingyu.domain.po;

import java.util.Date;

public class SdArchiveInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.archive_no
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private String archiveNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.name
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.sex
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.birth_time
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private Date birthTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.birth_place
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private String birthPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.ID_num
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private String idNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.disabler_num
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private String disablerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.enroll_time
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private Date enrollTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.training_type
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private String trainingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.diagnose_result
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private String diagnoseResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.diagnose_time
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private Date diagnoseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.diagnose_organiz
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private String diagnoseOrganiz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.cur_state
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private String curState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.training_his
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private String trainingHis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.status
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.home_address
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private String homeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.live_address
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private String liveAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.mobile
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.end_time
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.train_result
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private String trainResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_archive_info.writeoff_time
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    private Date writeoffTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.archive_no
     *
     * @return the value of sd_archive_info.archive_no
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public String getArchiveNo() {
        return archiveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.archive_no
     *
     * @param archiveNo the value for sd_archive_info.archive_no
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setArchiveNo(String archiveNo) {
        this.archiveNo = archiveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.name
     *
     * @return the value of sd_archive_info.name
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.name
     *
     * @param name the value for sd_archive_info.name
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.sex
     *
     * @return the value of sd_archive_info.sex
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.sex
     *
     * @param sex the value for sd_archive_info.sex
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.birth_time
     *
     * @return the value of sd_archive_info.birth_time
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public Date getBirthTime() {
        return birthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.birth_time
     *
     * @param birthTime the value for sd_archive_info.birth_time
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setBirthTime(Date birthTime) {
        this.birthTime = birthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.birth_place
     *
     * @return the value of sd_archive_info.birth_place
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.birth_place
     *
     * @param birthPlace the value for sd_archive_info.birth_place
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.ID_num
     *
     * @return the value of sd_archive_info.ID_num
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public String getIdNum() {
        return idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.ID_num
     *
     * @param idNum the value for sd_archive_info.ID_num
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setIdNum(String idNum) {
        this.idNum = idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.disabler_num
     *
     * @return the value of sd_archive_info.disabler_num
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public String getDisablerNum() {
        return disablerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.disabler_num
     *
     * @param disablerNum the value for sd_archive_info.disabler_num
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setDisablerNum(String disablerNum) {
        this.disablerNum = disablerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.enroll_time
     *
     * @return the value of sd_archive_info.enroll_time
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public Date getEnrollTime() {
        return enrollTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.enroll_time
     *
     * @param enrollTime the value for sd_archive_info.enroll_time
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setEnrollTime(Date enrollTime) {
        this.enrollTime = enrollTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.training_type
     *
     * @return the value of sd_archive_info.training_type
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public String getTrainingType() {
        return trainingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.training_type
     *
     * @param trainingType the value for sd_archive_info.training_type
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setTrainingType(String trainingType) {
        this.trainingType = trainingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.diagnose_result
     *
     * @return the value of sd_archive_info.diagnose_result
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public String getDiagnoseResult() {
        return diagnoseResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.diagnose_result
     *
     * @param diagnoseResult the value for sd_archive_info.diagnose_result
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setDiagnoseResult(String diagnoseResult) {
        this.diagnoseResult = diagnoseResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.diagnose_time
     *
     * @return the value of sd_archive_info.diagnose_time
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public Date getDiagnoseTime() {
        return diagnoseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.diagnose_time
     *
     * @param diagnoseTime the value for sd_archive_info.diagnose_time
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setDiagnoseTime(Date diagnoseTime) {
        this.diagnoseTime = diagnoseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.diagnose_organiz
     *
     * @return the value of sd_archive_info.diagnose_organiz
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public String getDiagnoseOrganiz() {
        return diagnoseOrganiz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.diagnose_organiz
     *
     * @param diagnoseOrganiz the value for sd_archive_info.diagnose_organiz
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setDiagnoseOrganiz(String diagnoseOrganiz) {
        this.diagnoseOrganiz = diagnoseOrganiz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.cur_state
     *
     * @return the value of sd_archive_info.cur_state
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public String getCurState() {
        return curState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.cur_state
     *
     * @param curState the value for sd_archive_info.cur_state
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setCurState(String curState) {
        this.curState = curState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.training_his
     *
     * @return the value of sd_archive_info.training_his
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public String getTrainingHis() {
        return trainingHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.training_his
     *
     * @param trainingHis the value for sd_archive_info.training_his
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setTrainingHis(String trainingHis) {
        this.trainingHis = trainingHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.status
     *
     * @return the value of sd_archive_info.status
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.status
     *
     * @param status the value for sd_archive_info.status
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.home_address
     *
     * @return the value of sd_archive_info.home_address
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.home_address
     *
     * @param homeAddress the value for sd_archive_info.home_address
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.live_address
     *
     * @return the value of sd_archive_info.live_address
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public String getLiveAddress() {
        return liveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.live_address
     *
     * @param liveAddress the value for sd_archive_info.live_address
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setLiveAddress(String liveAddress) {
        this.liveAddress = liveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.mobile
     *
     * @return the value of sd_archive_info.mobile
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.mobile
     *
     * @param mobile the value for sd_archive_info.mobile
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.end_time
     *
     * @return the value of sd_archive_info.end_time
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.end_time
     *
     * @param endTime the value for sd_archive_info.end_time
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.train_result
     *
     * @return the value of sd_archive_info.train_result
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public String getTrainResult() {
        return trainResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.train_result
     *
     * @param trainResult the value for sd_archive_info.train_result
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setTrainResult(String trainResult) {
        this.trainResult = trainResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_archive_info.writeoff_time
     *
     * @return the value of sd_archive_info.writeoff_time
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public Date getWriteoffTime() {
        return writeoffTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_archive_info.writeoff_time
     *
     * @param writeoffTime the value for sd_archive_info.writeoff_time
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    public void setWriteoffTime(Date writeoffTime) {
        this.writeoffTime = writeoffTime;
    }
}