package com.xingyu.domain.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SdAssessTimesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    public SdAssessTimesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andArchiveNoIsNull() {
            addCriterion("archive_no is null");
            return (Criteria) this;
        }

        public Criteria andArchiveNoIsNotNull() {
            addCriterion("archive_no is not null");
            return (Criteria) this;
        }

        public Criteria andArchiveNoEqualTo(String value) {
            addCriterion("archive_no =", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotEqualTo(String value) {
            addCriterion("archive_no <>", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoGreaterThan(String value) {
            addCriterion("archive_no >", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoGreaterThanOrEqualTo(String value) {
            addCriterion("archive_no >=", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoLessThan(String value) {
            addCriterion("archive_no <", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoLessThanOrEqualTo(String value) {
            addCriterion("archive_no <=", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoLike(String value) {
            addCriterion("archive_no like", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotLike(String value) {
            addCriterion("archive_no not like", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoIn(List<String> values) {
            addCriterion("archive_no in", values, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotIn(List<String> values) {
            addCriterion("archive_no not in", values, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoBetween(String value1, String value2) {
            addCriterion("archive_no between", value1, value2, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotBetween(String value1, String value2) {
            addCriterion("archive_no not between", value1, value2, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andAssessTimesIsNull() {
            addCriterion("assess_times is null");
            return (Criteria) this;
        }

        public Criteria andAssessTimesIsNotNull() {
            addCriterion("assess_times is not null");
            return (Criteria) this;
        }

        public Criteria andAssessTimesEqualTo(String value) {
            addCriterion("assess_times =", value, "assessTimes");
            return (Criteria) this;
        }

        public Criteria andAssessTimesNotEqualTo(String value) {
            addCriterion("assess_times <>", value, "assessTimes");
            return (Criteria) this;
        }

        public Criteria andAssessTimesGreaterThan(String value) {
            addCriterion("assess_times >", value, "assessTimes");
            return (Criteria) this;
        }

        public Criteria andAssessTimesGreaterThanOrEqualTo(String value) {
            addCriterion("assess_times >=", value, "assessTimes");
            return (Criteria) this;
        }

        public Criteria andAssessTimesLessThan(String value) {
            addCriterion("assess_times <", value, "assessTimes");
            return (Criteria) this;
        }

        public Criteria andAssessTimesLessThanOrEqualTo(String value) {
            addCriterion("assess_times <=", value, "assessTimes");
            return (Criteria) this;
        }

        public Criteria andAssessTimesLike(String value) {
            addCriterion("assess_times like", value, "assessTimes");
            return (Criteria) this;
        }

        public Criteria andAssessTimesNotLike(String value) {
            addCriterion("assess_times not like", value, "assessTimes");
            return (Criteria) this;
        }

        public Criteria andAssessTimesIn(List<String> values) {
            addCriterion("assess_times in", values, "assessTimes");
            return (Criteria) this;
        }

        public Criteria andAssessTimesNotIn(List<String> values) {
            addCriterion("assess_times not in", values, "assessTimes");
            return (Criteria) this;
        }

        public Criteria andAssessTimesBetween(String value1, String value2) {
            addCriterion("assess_times between", value1, value2, "assessTimes");
            return (Criteria) this;
        }

        public Criteria andAssessTimesNotBetween(String value1, String value2) {
            addCriterion("assess_times not between", value1, value2, "assessTimes");
            return (Criteria) this;
        }

        public Criteria andAssessDateIsNull() {
            addCriterion("assess_date is null");
            return (Criteria) this;
        }

        public Criteria andAssessDateIsNotNull() {
            addCriterion("assess_date is not null");
            return (Criteria) this;
        }

        public Criteria andAssessDateEqualTo(Date value) {
            addCriterionForJDBCDate("assess_date =", value, "assessDate");
            return (Criteria) this;
        }

        public Criteria andAssessDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("assess_date <>", value, "assessDate");
            return (Criteria) this;
        }

        public Criteria andAssessDateGreaterThan(Date value) {
            addCriterionForJDBCDate("assess_date >", value, "assessDate");
            return (Criteria) this;
        }

        public Criteria andAssessDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("assess_date >=", value, "assessDate");
            return (Criteria) this;
        }

        public Criteria andAssessDateLessThan(Date value) {
            addCriterionForJDBCDate("assess_date <", value, "assessDate");
            return (Criteria) this;
        }

        public Criteria andAssessDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("assess_date <=", value, "assessDate");
            return (Criteria) this;
        }

        public Criteria andAssessDateIn(List<Date> values) {
            addCriterionForJDBCDate("assess_date in", values, "assessDate");
            return (Criteria) this;
        }

        public Criteria andAssessDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("assess_date not in", values, "assessDate");
            return (Criteria) this;
        }

        public Criteria andAssessDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("assess_date between", value1, value2, "assessDate");
            return (Criteria) this;
        }

        public Criteria andAssessDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("assess_date not between", value1, value2, "assessDate");
            return (Criteria) this;
        }

        public Criteria andSdAgeIsNull() {
            addCriterion("sd_age is null");
            return (Criteria) this;
        }

        public Criteria andSdAgeIsNotNull() {
            addCriterion("sd_age is not null");
            return (Criteria) this;
        }

        public Criteria andSdAgeEqualTo(String value) {
            addCriterion("sd_age =", value, "sdAge");
            return (Criteria) this;
        }

        public Criteria andSdAgeNotEqualTo(String value) {
            addCriterion("sd_age <>", value, "sdAge");
            return (Criteria) this;
        }

        public Criteria andSdAgeGreaterThan(String value) {
            addCriterion("sd_age >", value, "sdAge");
            return (Criteria) this;
        }

        public Criteria andSdAgeGreaterThanOrEqualTo(String value) {
            addCriterion("sd_age >=", value, "sdAge");
            return (Criteria) this;
        }

        public Criteria andSdAgeLessThan(String value) {
            addCriterion("sd_age <", value, "sdAge");
            return (Criteria) this;
        }

        public Criteria andSdAgeLessThanOrEqualTo(String value) {
            addCriterion("sd_age <=", value, "sdAge");
            return (Criteria) this;
        }

        public Criteria andSdAgeLike(String value) {
            addCriterion("sd_age like", value, "sdAge");
            return (Criteria) this;
        }

        public Criteria andSdAgeNotLike(String value) {
            addCriterion("sd_age not like", value, "sdAge");
            return (Criteria) this;
        }

        public Criteria andSdAgeIn(List<String> values) {
            addCriterion("sd_age in", values, "sdAge");
            return (Criteria) this;
        }

        public Criteria andSdAgeNotIn(List<String> values) {
            addCriterion("sd_age not in", values, "sdAge");
            return (Criteria) this;
        }

        public Criteria andSdAgeBetween(String value1, String value2) {
            addCriterion("sd_age between", value1, value2, "sdAge");
            return (Criteria) this;
        }

        public Criteria andSdAgeNotBetween(String value1, String value2) {
            addCriterion("sd_age not between", value1, value2, "sdAge");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherIsNull() {
            addCriterion("assess_teacher is null");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherIsNotNull() {
            addCriterion("assess_teacher is not null");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherEqualTo(String value) {
            addCriterion("assess_teacher =", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherNotEqualTo(String value) {
            addCriterion("assess_teacher <>", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherGreaterThan(String value) {
            addCriterion("assess_teacher >", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherGreaterThanOrEqualTo(String value) {
            addCriterion("assess_teacher >=", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherLessThan(String value) {
            addCriterion("assess_teacher <", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherLessThanOrEqualTo(String value) {
            addCriterion("assess_teacher <=", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherLike(String value) {
            addCriterion("assess_teacher like", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherNotLike(String value) {
            addCriterion("assess_teacher not like", value, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherIn(List<String> values) {
            addCriterion("assess_teacher in", values, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherNotIn(List<String> values) {
            addCriterion("assess_teacher not in", values, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherBetween(String value1, String value2) {
            addCriterion("assess_teacher between", value1, value2, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessTeacherNotBetween(String value1, String value2) {
            addCriterion("assess_teacher not between", value1, value2, "assessTeacher");
            return (Criteria) this;
        }

        public Criteria andAssessAgeIsNull() {
            addCriterion("assess_age is null");
            return (Criteria) this;
        }

        public Criteria andAssessAgeIsNotNull() {
            addCriterion("assess_age is not null");
            return (Criteria) this;
        }

        public Criteria andAssessAgeEqualTo(String value) {
            addCriterion("assess_age =", value, "assessAge");
            return (Criteria) this;
        }

        public Criteria andAssessAgeNotEqualTo(String value) {
            addCriterion("assess_age <>", value, "assessAge");
            return (Criteria) this;
        }

        public Criteria andAssessAgeGreaterThan(String value) {
            addCriterion("assess_age >", value, "assessAge");
            return (Criteria) this;
        }

        public Criteria andAssessAgeGreaterThanOrEqualTo(String value) {
            addCriterion("assess_age >=", value, "assessAge");
            return (Criteria) this;
        }

        public Criteria andAssessAgeLessThan(String value) {
            addCriterion("assess_age <", value, "assessAge");
            return (Criteria) this;
        }

        public Criteria andAssessAgeLessThanOrEqualTo(String value) {
            addCriterion("assess_age <=", value, "assessAge");
            return (Criteria) this;
        }

        public Criteria andAssessAgeLike(String value) {
            addCriterion("assess_age like", value, "assessAge");
            return (Criteria) this;
        }

        public Criteria andAssessAgeNotLike(String value) {
            addCriterion("assess_age not like", value, "assessAge");
            return (Criteria) this;
        }

        public Criteria andAssessAgeIn(List<String> values) {
            addCriterion("assess_age in", values, "assessAge");
            return (Criteria) this;
        }

        public Criteria andAssessAgeNotIn(List<String> values) {
            addCriterion("assess_age not in", values, "assessAge");
            return (Criteria) this;
        }

        public Criteria andAssessAgeBetween(String value1, String value2) {
            addCriterion("assess_age between", value1, value2, "assessAge");
            return (Criteria) this;
        }

        public Criteria andAssessAgeNotBetween(String value1, String value2) {
            addCriterion("assess_age not between", value1, value2, "assessAge");
            return (Criteria) this;
        }

        public Criteria andDevelopAgeIsNull() {
            addCriterion("develop_age is null");
            return (Criteria) this;
        }

        public Criteria andDevelopAgeIsNotNull() {
            addCriterion("develop_age is not null");
            return (Criteria) this;
        }

        public Criteria andDevelopAgeEqualTo(String value) {
            addCriterion("develop_age =", value, "developAge");
            return (Criteria) this;
        }

        public Criteria andDevelopAgeNotEqualTo(String value) {
            addCriterion("develop_age <>", value, "developAge");
            return (Criteria) this;
        }

        public Criteria andDevelopAgeGreaterThan(String value) {
            addCriterion("develop_age >", value, "developAge");
            return (Criteria) this;
        }

        public Criteria andDevelopAgeGreaterThanOrEqualTo(String value) {
            addCriterion("develop_age >=", value, "developAge");
            return (Criteria) this;
        }

        public Criteria andDevelopAgeLessThan(String value) {
            addCriterion("develop_age <", value, "developAge");
            return (Criteria) this;
        }

        public Criteria andDevelopAgeLessThanOrEqualTo(String value) {
            addCriterion("develop_age <=", value, "developAge");
            return (Criteria) this;
        }

        public Criteria andDevelopAgeLike(String value) {
            addCriterion("develop_age like", value, "developAge");
            return (Criteria) this;
        }

        public Criteria andDevelopAgeNotLike(String value) {
            addCriterion("develop_age not like", value, "developAge");
            return (Criteria) this;
        }

        public Criteria andDevelopAgeIn(List<String> values) {
            addCriterion("develop_age in", values, "developAge");
            return (Criteria) this;
        }

        public Criteria andDevelopAgeNotIn(List<String> values) {
            addCriterion("develop_age not in", values, "developAge");
            return (Criteria) this;
        }

        public Criteria andDevelopAgeBetween(String value1, String value2) {
            addCriterion("develop_age between", value1, value2, "developAge");
            return (Criteria) this;
        }

        public Criteria andDevelopAgeNotBetween(String value1, String value2) {
            addCriterion("develop_age not between", value1, value2, "developAge");
            return (Criteria) this;
        }

        public Criteria andAnalyseTeacherIsNull() {
            addCriterion("analyse_teacher is null");
            return (Criteria) this;
        }

        public Criteria andAnalyseTeacherIsNotNull() {
            addCriterion("analyse_teacher is not null");
            return (Criteria) this;
        }

        public Criteria andAnalyseTeacherEqualTo(String value) {
            addCriterion("analyse_teacher =", value, "analyseTeacher");
            return (Criteria) this;
        }

        public Criteria andAnalyseTeacherNotEqualTo(String value) {
            addCriterion("analyse_teacher <>", value, "analyseTeacher");
            return (Criteria) this;
        }

        public Criteria andAnalyseTeacherGreaterThan(String value) {
            addCriterion("analyse_teacher >", value, "analyseTeacher");
            return (Criteria) this;
        }

        public Criteria andAnalyseTeacherGreaterThanOrEqualTo(String value) {
            addCriterion("analyse_teacher >=", value, "analyseTeacher");
            return (Criteria) this;
        }

        public Criteria andAnalyseTeacherLessThan(String value) {
            addCriterion("analyse_teacher <", value, "analyseTeacher");
            return (Criteria) this;
        }

        public Criteria andAnalyseTeacherLessThanOrEqualTo(String value) {
            addCriterion("analyse_teacher <=", value, "analyseTeacher");
            return (Criteria) this;
        }

        public Criteria andAnalyseTeacherLike(String value) {
            addCriterion("analyse_teacher like", value, "analyseTeacher");
            return (Criteria) this;
        }

        public Criteria andAnalyseTeacherNotLike(String value) {
            addCriterion("analyse_teacher not like", value, "analyseTeacher");
            return (Criteria) this;
        }

        public Criteria andAnalyseTeacherIn(List<String> values) {
            addCriterion("analyse_teacher in", values, "analyseTeacher");
            return (Criteria) this;
        }

        public Criteria andAnalyseTeacherNotIn(List<String> values) {
            addCriterion("analyse_teacher not in", values, "analyseTeacher");
            return (Criteria) this;
        }

        public Criteria andAnalyseTeacherBetween(String value1, String value2) {
            addCriterion("analyse_teacher between", value1, value2, "analyseTeacher");
            return (Criteria) this;
        }

        public Criteria andAnalyseTeacherNotBetween(String value1, String value2) {
            addCriterion("analyse_teacher not between", value1, value2, "analyseTeacher");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeIsNull() {
            addCriterion("analyse_time is null");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeIsNotNull() {
            addCriterion("analyse_time is not null");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeEqualTo(Date value) {
            addCriterionForJDBCDate("analyse_time =", value, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("analyse_time <>", value, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("analyse_time >", value, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("analyse_time >=", value, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeLessThan(Date value) {
            addCriterionForJDBCDate("analyse_time <", value, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("analyse_time <=", value, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeIn(List<Date> values) {
            addCriterionForJDBCDate("analyse_time in", values, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("analyse_time not in", values, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("analyse_time between", value1, value2, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andAnalyseTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("analyse_time not between", value1, value2, "analyseTime");
            return (Criteria) this;
        }

        public Criteria andIepChargeIsNull() {
            addCriterion("iep_charge is null");
            return (Criteria) this;
        }

        public Criteria andIepChargeIsNotNull() {
            addCriterion("iep_charge is not null");
            return (Criteria) this;
        }

        public Criteria andIepChargeEqualTo(String value) {
            addCriterion("iep_charge =", value, "iepCharge");
            return (Criteria) this;
        }

        public Criteria andIepChargeNotEqualTo(String value) {
            addCriterion("iep_charge <>", value, "iepCharge");
            return (Criteria) this;
        }

        public Criteria andIepChargeGreaterThan(String value) {
            addCriterion("iep_charge >", value, "iepCharge");
            return (Criteria) this;
        }

        public Criteria andIepChargeGreaterThanOrEqualTo(String value) {
            addCriterion("iep_charge >=", value, "iepCharge");
            return (Criteria) this;
        }

        public Criteria andIepChargeLessThan(String value) {
            addCriterion("iep_charge <", value, "iepCharge");
            return (Criteria) this;
        }

        public Criteria andIepChargeLessThanOrEqualTo(String value) {
            addCriterion("iep_charge <=", value, "iepCharge");
            return (Criteria) this;
        }

        public Criteria andIepChargeLike(String value) {
            addCriterion("iep_charge like", value, "iepCharge");
            return (Criteria) this;
        }

        public Criteria andIepChargeNotLike(String value) {
            addCriterion("iep_charge not like", value, "iepCharge");
            return (Criteria) this;
        }

        public Criteria andIepChargeIn(List<String> values) {
            addCriterion("iep_charge in", values, "iepCharge");
            return (Criteria) this;
        }

        public Criteria andIepChargeNotIn(List<String> values) {
            addCriterion("iep_charge not in", values, "iepCharge");
            return (Criteria) this;
        }

        public Criteria andIepChargeBetween(String value1, String value2) {
            addCriterion("iep_charge between", value1, value2, "iepCharge");
            return (Criteria) this;
        }

        public Criteria andIepChargeNotBetween(String value1, String value2) {
            addCriterion("iep_charge not between", value1, value2, "iepCharge");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherIsNull() {
            addCriterion("train_teacher is null");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherIsNotNull() {
            addCriterion("train_teacher is not null");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherEqualTo(String value) {
            addCriterion("train_teacher =", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherNotEqualTo(String value) {
            addCriterion("train_teacher <>", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherGreaterThan(String value) {
            addCriterion("train_teacher >", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherGreaterThanOrEqualTo(String value) {
            addCriterion("train_teacher >=", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherLessThan(String value) {
            addCriterion("train_teacher <", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherLessThanOrEqualTo(String value) {
            addCriterion("train_teacher <=", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherLike(String value) {
            addCriterion("train_teacher like", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherNotLike(String value) {
            addCriterion("train_teacher not like", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherIn(List<String> values) {
            addCriterion("train_teacher in", values, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherNotIn(List<String> values) {
            addCriterion("train_teacher not in", values, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherBetween(String value1, String value2) {
            addCriterion("train_teacher between", value1, value2, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherNotBetween(String value1, String value2) {
            addCriterion("train_teacher not between", value1, value2, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainStartTimeIsNull() {
            addCriterion("train_start_time is null");
            return (Criteria) this;
        }

        public Criteria andTrainStartTimeIsNotNull() {
            addCriterion("train_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andTrainStartTimeEqualTo(Date value) {
            addCriterionForJDBCDate("train_start_time =", value, "trainStartTime");
            return (Criteria) this;
        }

        public Criteria andTrainStartTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("train_start_time <>", value, "trainStartTime");
            return (Criteria) this;
        }

        public Criteria andTrainStartTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("train_start_time >", value, "trainStartTime");
            return (Criteria) this;
        }

        public Criteria andTrainStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("train_start_time >=", value, "trainStartTime");
            return (Criteria) this;
        }

        public Criteria andTrainStartTimeLessThan(Date value) {
            addCriterionForJDBCDate("train_start_time <", value, "trainStartTime");
            return (Criteria) this;
        }

        public Criteria andTrainStartTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("train_start_time <=", value, "trainStartTime");
            return (Criteria) this;
        }

        public Criteria andTrainStartTimeIn(List<Date> values) {
            addCriterionForJDBCDate("train_start_time in", values, "trainStartTime");
            return (Criteria) this;
        }

        public Criteria andTrainStartTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("train_start_time not in", values, "trainStartTime");
            return (Criteria) this;
        }

        public Criteria andTrainStartTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("train_start_time between", value1, value2, "trainStartTime");
            return (Criteria) this;
        }

        public Criteria andTrainStartTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("train_start_time not between", value1, value2, "trainStartTime");
            return (Criteria) this;
        }

        public Criteria andTrainEndTimeIsNull() {
            addCriterion("train_end_time is null");
            return (Criteria) this;
        }

        public Criteria andTrainEndTimeIsNotNull() {
            addCriterion("train_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andTrainEndTimeEqualTo(Date value) {
            addCriterionForJDBCDate("train_end_time =", value, "trainEndTime");
            return (Criteria) this;
        }

        public Criteria andTrainEndTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("train_end_time <>", value, "trainEndTime");
            return (Criteria) this;
        }

        public Criteria andTrainEndTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("train_end_time >", value, "trainEndTime");
            return (Criteria) this;
        }

        public Criteria andTrainEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("train_end_time >=", value, "trainEndTime");
            return (Criteria) this;
        }

        public Criteria andTrainEndTimeLessThan(Date value) {
            addCriterionForJDBCDate("train_end_time <", value, "trainEndTime");
            return (Criteria) this;
        }

        public Criteria andTrainEndTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("train_end_time <=", value, "trainEndTime");
            return (Criteria) this;
        }

        public Criteria andTrainEndTimeIn(List<Date> values) {
            addCriterionForJDBCDate("train_end_time in", values, "trainEndTime");
            return (Criteria) this;
        }

        public Criteria andTrainEndTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("train_end_time not in", values, "trainEndTime");
            return (Criteria) this;
        }

        public Criteria andTrainEndTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("train_end_time between", value1, value2, "trainEndTime");
            return (Criteria) this;
        }

        public Criteria andTrainEndTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("train_end_time not between", value1, value2, "trainEndTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_assess_times
     *
     * @mbggenerated do_not_delete_during_merge Fri Aug 02 23:23:12 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}