package com.xingyu.domain.po;

import java.util.Date;

public class SdAssessTimes extends SdAssessTimesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_assess_times.assess_date
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private Date assessDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_assess_times.sd_age
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String sdAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_assess_times.assess_teacher
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String assessTeacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_assess_times.assess_age
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String assessAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_assess_times.develop_age
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String developAge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_assess_times.assess_date
     *
     * @return the value of sd_assess_times.assess_date
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public Date getAssessDate() {
        return assessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_assess_times.assess_date
     *
     * @param assessDate the value for sd_assess_times.assess_date
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setAssessDate(Date assessDate) {
        this.assessDate = assessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_assess_times.sd_age
     *
     * @return the value of sd_assess_times.sd_age
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getSdAge() {
        return sdAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_assess_times.sd_age
     *
     * @param sdAge the value for sd_assess_times.sd_age
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setSdAge(String sdAge) {
        this.sdAge = sdAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_assess_times.assess_teacher
     *
     * @return the value of sd_assess_times.assess_teacher
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getAssessTeacher() {
        return assessTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_assess_times.assess_teacher
     *
     * @param assessTeacher the value for sd_assess_times.assess_teacher
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setAssessTeacher(String assessTeacher) {
        this.assessTeacher = assessTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_assess_times.assess_age
     *
     * @return the value of sd_assess_times.assess_age
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getAssessAge() {
        return assessAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_assess_times.assess_age
     *
     * @param assessAge the value for sd_assess_times.assess_age
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setAssessAge(String assessAge) {
        this.assessAge = assessAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_assess_times.develop_age
     *
     * @return the value of sd_assess_times.develop_age
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getDevelopAge() {
        return developAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_assess_times.develop_age
     *
     * @param developAge the value for sd_assess_times.develop_age
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setDevelopAge(String developAge) {
        this.developAge = developAge;
    }
}