package com.xingyu.domain.po;

public class SdAssessTimesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_assess_times.archive_no
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    private String archiveNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_assess_times.assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    private String assessTimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_assess_times.archive_no
     *
     * @return the value of sd_assess_times.archive_no
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    public String getArchiveNo() {
        return archiveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_assess_times.archive_no
     *
     * @param archiveNo the value for sd_assess_times.archive_no
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    public void setArchiveNo(String archiveNo) {
        this.archiveNo = archiveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_assess_times.assess_times
     *
     * @return the value of sd_assess_times.assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    public String getAssessTimes() {
        return assessTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_assess_times.assess_times
     *
     * @param assessTimes the value for sd_assess_times.assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    public void setAssessTimes(String assessTimes) {
        this.assessTimes = assessTimes;
    }
}