package com.xingyu.domain.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SdEduTrackExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    public SdEduTrackExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andArchiveNoIsNull() {
            addCriterion("archive_no is null");
            return (Criteria) this;
        }

        public Criteria andArchiveNoIsNotNull() {
            addCriterion("archive_no is not null");
            return (Criteria) this;
        }

        public Criteria andArchiveNoEqualTo(String value) {
            addCriterion("archive_no =", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotEqualTo(String value) {
            addCriterion("archive_no <>", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoGreaterThan(String value) {
            addCriterion("archive_no >", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoGreaterThanOrEqualTo(String value) {
            addCriterion("archive_no >=", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoLessThan(String value) {
            addCriterion("archive_no <", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoLessThanOrEqualTo(String value) {
            addCriterion("archive_no <=", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoLike(String value) {
            addCriterion("archive_no like", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotLike(String value) {
            addCriterion("archive_no not like", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoIn(List<String> values) {
            addCriterion("archive_no in", values, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotIn(List<String> values) {
            addCriterion("archive_no not in", values, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoBetween(String value1, String value2) {
            addCriterion("archive_no between", value1, value2, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotBetween(String value1, String value2) {
            addCriterion("archive_no not between", value1, value2, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIsNull() {
            addCriterion("school_name is null");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIsNotNull() {
            addCriterion("school_name is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolNameEqualTo(String value) {
            addCriterion("school_name =", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotEqualTo(String value) {
            addCriterion("school_name <>", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameGreaterThan(String value) {
            addCriterion("school_name >", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameGreaterThanOrEqualTo(String value) {
            addCriterion("school_name >=", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLessThan(String value) {
            addCriterion("school_name <", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLessThanOrEqualTo(String value) {
            addCriterion("school_name <=", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameLike(String value) {
            addCriterion("school_name like", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotLike(String value) {
            addCriterion("school_name not like", value, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameIn(List<String> values) {
            addCriterion("school_name in", values, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotIn(List<String> values) {
            addCriterion("school_name not in", values, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameBetween(String value1, String value2) {
            addCriterion("school_name between", value1, value2, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolNameNotBetween(String value1, String value2) {
            addCriterion("school_name not between", value1, value2, "schoolName");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeIsNull() {
            addCriterion("school_type is null");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeIsNotNull() {
            addCriterion("school_type is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeEqualTo(String value) {
            addCriterion("school_type =", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeNotEqualTo(String value) {
            addCriterion("school_type <>", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeGreaterThan(String value) {
            addCriterion("school_type >", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeGreaterThanOrEqualTo(String value) {
            addCriterion("school_type >=", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeLessThan(String value) {
            addCriterion("school_type <", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeLessThanOrEqualTo(String value) {
            addCriterion("school_type <=", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeLike(String value) {
            addCriterion("school_type like", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeNotLike(String value) {
            addCriterion("school_type not like", value, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeIn(List<String> values) {
            addCriterion("school_type in", values, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeNotIn(List<String> values) {
            addCriterion("school_type not in", values, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeBetween(String value1, String value2) {
            addCriterion("school_type between", value1, value2, "schoolType");
            return (Criteria) this;
        }

        public Criteria andSchoolTypeNotBetween(String value1, String value2) {
            addCriterion("school_type not between", value1, value2, "schoolType");
            return (Criteria) this;
        }

        public Criteria andEnrollTimeIsNull() {
            addCriterion("enroll_time is null");
            return (Criteria) this;
        }

        public Criteria andEnrollTimeIsNotNull() {
            addCriterion("enroll_time is not null");
            return (Criteria) this;
        }

        public Criteria andEnrollTimeEqualTo(Date value) {
            addCriterionForJDBCDate("enroll_time =", value, "enrollTime");
            return (Criteria) this;
        }

        public Criteria andEnrollTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("enroll_time <>", value, "enrollTime");
            return (Criteria) this;
        }

        public Criteria andEnrollTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("enroll_time >", value, "enrollTime");
            return (Criteria) this;
        }

        public Criteria andEnrollTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("enroll_time >=", value, "enrollTime");
            return (Criteria) this;
        }

        public Criteria andEnrollTimeLessThan(Date value) {
            addCriterionForJDBCDate("enroll_time <", value, "enrollTime");
            return (Criteria) this;
        }

        public Criteria andEnrollTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("enroll_time <=", value, "enrollTime");
            return (Criteria) this;
        }

        public Criteria andEnrollTimeIn(List<Date> values) {
            addCriterionForJDBCDate("enroll_time in", values, "enrollTime");
            return (Criteria) this;
        }

        public Criteria andEnrollTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("enroll_time not in", values, "enrollTime");
            return (Criteria) this;
        }

        public Criteria andEnrollTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("enroll_time between", value1, value2, "enrollTime");
            return (Criteria) this;
        }

        public Criteria andEnrollTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("enroll_time not between", value1, value2, "enrollTime");
            return (Criteria) this;
        }

        public Criteria andIntervieweeIsNull() {
            addCriterion("interviewee is null");
            return (Criteria) this;
        }

        public Criteria andIntervieweeIsNotNull() {
            addCriterion("interviewee is not null");
            return (Criteria) this;
        }

        public Criteria andIntervieweeEqualTo(String value) {
            addCriterion("interviewee =", value, "interviewee");
            return (Criteria) this;
        }

        public Criteria andIntervieweeNotEqualTo(String value) {
            addCriterion("interviewee <>", value, "interviewee");
            return (Criteria) this;
        }

        public Criteria andIntervieweeGreaterThan(String value) {
            addCriterion("interviewee >", value, "interviewee");
            return (Criteria) this;
        }

        public Criteria andIntervieweeGreaterThanOrEqualTo(String value) {
            addCriterion("interviewee >=", value, "interviewee");
            return (Criteria) this;
        }

        public Criteria andIntervieweeLessThan(String value) {
            addCriterion("interviewee <", value, "interviewee");
            return (Criteria) this;
        }

        public Criteria andIntervieweeLessThanOrEqualTo(String value) {
            addCriterion("interviewee <=", value, "interviewee");
            return (Criteria) this;
        }

        public Criteria andIntervieweeLike(String value) {
            addCriterion("interviewee like", value, "interviewee");
            return (Criteria) this;
        }

        public Criteria andIntervieweeNotLike(String value) {
            addCriterion("interviewee not like", value, "interviewee");
            return (Criteria) this;
        }

        public Criteria andIntervieweeIn(List<String> values) {
            addCriterion("interviewee in", values, "interviewee");
            return (Criteria) this;
        }

        public Criteria andIntervieweeNotIn(List<String> values) {
            addCriterion("interviewee not in", values, "interviewee");
            return (Criteria) this;
        }

        public Criteria andIntervieweeBetween(String value1, String value2) {
            addCriterion("interviewee between", value1, value2, "interviewee");
            return (Criteria) this;
        }

        public Criteria andIntervieweeNotBetween(String value1, String value2) {
            addCriterion("interviewee not between", value1, value2, "interviewee");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andInterviewLocationIsNull() {
            addCriterion("interview_location is null");
            return (Criteria) this;
        }

        public Criteria andInterviewLocationIsNotNull() {
            addCriterion("interview_location is not null");
            return (Criteria) this;
        }

        public Criteria andInterviewLocationEqualTo(String value) {
            addCriterion("interview_location =", value, "interviewLocation");
            return (Criteria) this;
        }

        public Criteria andInterviewLocationNotEqualTo(String value) {
            addCriterion("interview_location <>", value, "interviewLocation");
            return (Criteria) this;
        }

        public Criteria andInterviewLocationGreaterThan(String value) {
            addCriterion("interview_location >", value, "interviewLocation");
            return (Criteria) this;
        }

        public Criteria andInterviewLocationGreaterThanOrEqualTo(String value) {
            addCriterion("interview_location >=", value, "interviewLocation");
            return (Criteria) this;
        }

        public Criteria andInterviewLocationLessThan(String value) {
            addCriterion("interview_location <", value, "interviewLocation");
            return (Criteria) this;
        }

        public Criteria andInterviewLocationLessThanOrEqualTo(String value) {
            addCriterion("interview_location <=", value, "interviewLocation");
            return (Criteria) this;
        }

        public Criteria andInterviewLocationLike(String value) {
            addCriterion("interview_location like", value, "interviewLocation");
            return (Criteria) this;
        }

        public Criteria andInterviewLocationNotLike(String value) {
            addCriterion("interview_location not like", value, "interviewLocation");
            return (Criteria) this;
        }

        public Criteria andInterviewLocationIn(List<String> values) {
            addCriterion("interview_location in", values, "interviewLocation");
            return (Criteria) this;
        }

        public Criteria andInterviewLocationNotIn(List<String> values) {
            addCriterion("interview_location not in", values, "interviewLocation");
            return (Criteria) this;
        }

        public Criteria andInterviewLocationBetween(String value1, String value2) {
            addCriterion("interview_location between", value1, value2, "interviewLocation");
            return (Criteria) this;
        }

        public Criteria andInterviewLocationNotBetween(String value1, String value2) {
            addCriterion("interview_location not between", value1, value2, "interviewLocation");
            return (Criteria) this;
        }

        public Criteria andInterviewTypeIsNull() {
            addCriterion("interview_type is null");
            return (Criteria) this;
        }

        public Criteria andInterviewTypeIsNotNull() {
            addCriterion("interview_type is not null");
            return (Criteria) this;
        }

        public Criteria andInterviewTypeEqualTo(String value) {
            addCriterion("interview_type =", value, "interviewType");
            return (Criteria) this;
        }

        public Criteria andInterviewTypeNotEqualTo(String value) {
            addCriterion("interview_type <>", value, "interviewType");
            return (Criteria) this;
        }

        public Criteria andInterviewTypeGreaterThan(String value) {
            addCriterion("interview_type >", value, "interviewType");
            return (Criteria) this;
        }

        public Criteria andInterviewTypeGreaterThanOrEqualTo(String value) {
            addCriterion("interview_type >=", value, "interviewType");
            return (Criteria) this;
        }

        public Criteria andInterviewTypeLessThan(String value) {
            addCriterion("interview_type <", value, "interviewType");
            return (Criteria) this;
        }

        public Criteria andInterviewTypeLessThanOrEqualTo(String value) {
            addCriterion("interview_type <=", value, "interviewType");
            return (Criteria) this;
        }

        public Criteria andInterviewTypeLike(String value) {
            addCriterion("interview_type like", value, "interviewType");
            return (Criteria) this;
        }

        public Criteria andInterviewTypeNotLike(String value) {
            addCriterion("interview_type not like", value, "interviewType");
            return (Criteria) this;
        }

        public Criteria andInterviewTypeIn(List<String> values) {
            addCriterion("interview_type in", values, "interviewType");
            return (Criteria) this;
        }

        public Criteria andInterviewTypeNotIn(List<String> values) {
            addCriterion("interview_type not in", values, "interviewType");
            return (Criteria) this;
        }

        public Criteria andInterviewTypeBetween(String value1, String value2) {
            addCriterion("interview_type between", value1, value2, "interviewType");
            return (Criteria) this;
        }

        public Criteria andInterviewTypeNotBetween(String value1, String value2) {
            addCriterion("interview_type not between", value1, value2, "interviewType");
            return (Criteria) this;
        }

        public Criteria andClassroomPerformanceIsNull() {
            addCriterion("classroom_performance is null");
            return (Criteria) this;
        }

        public Criteria andClassroomPerformanceIsNotNull() {
            addCriterion("classroom_performance is not null");
            return (Criteria) this;
        }

        public Criteria andClassroomPerformanceEqualTo(String value) {
            addCriterion("classroom_performance =", value, "classroomPerformance");
            return (Criteria) this;
        }

        public Criteria andClassroomPerformanceNotEqualTo(String value) {
            addCriterion("classroom_performance <>", value, "classroomPerformance");
            return (Criteria) this;
        }

        public Criteria andClassroomPerformanceGreaterThan(String value) {
            addCriterion("classroom_performance >", value, "classroomPerformance");
            return (Criteria) this;
        }

        public Criteria andClassroomPerformanceGreaterThanOrEqualTo(String value) {
            addCriterion("classroom_performance >=", value, "classroomPerformance");
            return (Criteria) this;
        }

        public Criteria andClassroomPerformanceLessThan(String value) {
            addCriterion("classroom_performance <", value, "classroomPerformance");
            return (Criteria) this;
        }

        public Criteria andClassroomPerformanceLessThanOrEqualTo(String value) {
            addCriterion("classroom_performance <=", value, "classroomPerformance");
            return (Criteria) this;
        }

        public Criteria andClassroomPerformanceLike(String value) {
            addCriterion("classroom_performance like", value, "classroomPerformance");
            return (Criteria) this;
        }

        public Criteria andClassroomPerformanceNotLike(String value) {
            addCriterion("classroom_performance not like", value, "classroomPerformance");
            return (Criteria) this;
        }

        public Criteria andClassroomPerformanceIn(List<String> values) {
            addCriterion("classroom_performance in", values, "classroomPerformance");
            return (Criteria) this;
        }

        public Criteria andClassroomPerformanceNotIn(List<String> values) {
            addCriterion("classroom_performance not in", values, "classroomPerformance");
            return (Criteria) this;
        }

        public Criteria andClassroomPerformanceBetween(String value1, String value2) {
            addCriterion("classroom_performance between", value1, value2, "classroomPerformance");
            return (Criteria) this;
        }

        public Criteria andClassroomPerformanceNotBetween(String value1, String value2) {
            addCriterion("classroom_performance not between", value1, value2, "classroomPerformance");
            return (Criteria) this;
        }

        public Criteria andPaperworkPerformanceIsNull() {
            addCriterion("paperwork_performance is null");
            return (Criteria) this;
        }

        public Criteria andPaperworkPerformanceIsNotNull() {
            addCriterion("paperwork_performance is not null");
            return (Criteria) this;
        }

        public Criteria andPaperworkPerformanceEqualTo(String value) {
            addCriterion("paperwork_performance =", value, "paperworkPerformance");
            return (Criteria) this;
        }

        public Criteria andPaperworkPerformanceNotEqualTo(String value) {
            addCriterion("paperwork_performance <>", value, "paperworkPerformance");
            return (Criteria) this;
        }

        public Criteria andPaperworkPerformanceGreaterThan(String value) {
            addCriterion("paperwork_performance >", value, "paperworkPerformance");
            return (Criteria) this;
        }

        public Criteria andPaperworkPerformanceGreaterThanOrEqualTo(String value) {
            addCriterion("paperwork_performance >=", value, "paperworkPerformance");
            return (Criteria) this;
        }

        public Criteria andPaperworkPerformanceLessThan(String value) {
            addCriterion("paperwork_performance <", value, "paperworkPerformance");
            return (Criteria) this;
        }

        public Criteria andPaperworkPerformanceLessThanOrEqualTo(String value) {
            addCriterion("paperwork_performance <=", value, "paperworkPerformance");
            return (Criteria) this;
        }

        public Criteria andPaperworkPerformanceLike(String value) {
            addCriterion("paperwork_performance like", value, "paperworkPerformance");
            return (Criteria) this;
        }

        public Criteria andPaperworkPerformanceNotLike(String value) {
            addCriterion("paperwork_performance not like", value, "paperworkPerformance");
            return (Criteria) this;
        }

        public Criteria andPaperworkPerformanceIn(List<String> values) {
            addCriterion("paperwork_performance in", values, "paperworkPerformance");
            return (Criteria) this;
        }

        public Criteria andPaperworkPerformanceNotIn(List<String> values) {
            addCriterion("paperwork_performance not in", values, "paperworkPerformance");
            return (Criteria) this;
        }

        public Criteria andPaperworkPerformanceBetween(String value1, String value2) {
            addCriterion("paperwork_performance between", value1, value2, "paperworkPerformance");
            return (Criteria) this;
        }

        public Criteria andPaperworkPerformanceNotBetween(String value1, String value2) {
            addCriterion("paperwork_performance not between", value1, value2, "paperworkPerformance");
            return (Criteria) this;
        }

        public Criteria andActivityPerformanceIsNull() {
            addCriterion("activity_performance is null");
            return (Criteria) this;
        }

        public Criteria andActivityPerformanceIsNotNull() {
            addCriterion("activity_performance is not null");
            return (Criteria) this;
        }

        public Criteria andActivityPerformanceEqualTo(String value) {
            addCriterion("activity_performance =", value, "activityPerformance");
            return (Criteria) this;
        }

        public Criteria andActivityPerformanceNotEqualTo(String value) {
            addCriterion("activity_performance <>", value, "activityPerformance");
            return (Criteria) this;
        }

        public Criteria andActivityPerformanceGreaterThan(String value) {
            addCriterion("activity_performance >", value, "activityPerformance");
            return (Criteria) this;
        }

        public Criteria andActivityPerformanceGreaterThanOrEqualTo(String value) {
            addCriterion("activity_performance >=", value, "activityPerformance");
            return (Criteria) this;
        }

        public Criteria andActivityPerformanceLessThan(String value) {
            addCriterion("activity_performance <", value, "activityPerformance");
            return (Criteria) this;
        }

        public Criteria andActivityPerformanceLessThanOrEqualTo(String value) {
            addCriterion("activity_performance <=", value, "activityPerformance");
            return (Criteria) this;
        }

        public Criteria andActivityPerformanceLike(String value) {
            addCriterion("activity_performance like", value, "activityPerformance");
            return (Criteria) this;
        }

        public Criteria andActivityPerformanceNotLike(String value) {
            addCriterion("activity_performance not like", value, "activityPerformance");
            return (Criteria) this;
        }

        public Criteria andActivityPerformanceIn(List<String> values) {
            addCriterion("activity_performance in", values, "activityPerformance");
            return (Criteria) this;
        }

        public Criteria andActivityPerformanceNotIn(List<String> values) {
            addCriterion("activity_performance not in", values, "activityPerformance");
            return (Criteria) this;
        }

        public Criteria andActivityPerformanceBetween(String value1, String value2) {
            addCriterion("activity_performance between", value1, value2, "activityPerformance");
            return (Criteria) this;
        }

        public Criteria andActivityPerformanceNotBetween(String value1, String value2) {
            addCriterion("activity_performance not between", value1, value2, "activityPerformance");
            return (Criteria) this;
        }

        public Criteria andActionPerformanceIsNull() {
            addCriterion("action_performance is null");
            return (Criteria) this;
        }

        public Criteria andActionPerformanceIsNotNull() {
            addCriterion("action_performance is not null");
            return (Criteria) this;
        }

        public Criteria andActionPerformanceEqualTo(String value) {
            addCriterion("action_performance =", value, "actionPerformance");
            return (Criteria) this;
        }

        public Criteria andActionPerformanceNotEqualTo(String value) {
            addCriterion("action_performance <>", value, "actionPerformance");
            return (Criteria) this;
        }

        public Criteria andActionPerformanceGreaterThan(String value) {
            addCriterion("action_performance >", value, "actionPerformance");
            return (Criteria) this;
        }

        public Criteria andActionPerformanceGreaterThanOrEqualTo(String value) {
            addCriterion("action_performance >=", value, "actionPerformance");
            return (Criteria) this;
        }

        public Criteria andActionPerformanceLessThan(String value) {
            addCriterion("action_performance <", value, "actionPerformance");
            return (Criteria) this;
        }

        public Criteria andActionPerformanceLessThanOrEqualTo(String value) {
            addCriterion("action_performance <=", value, "actionPerformance");
            return (Criteria) this;
        }

        public Criteria andActionPerformanceLike(String value) {
            addCriterion("action_performance like", value, "actionPerformance");
            return (Criteria) this;
        }

        public Criteria andActionPerformanceNotLike(String value) {
            addCriterion("action_performance not like", value, "actionPerformance");
            return (Criteria) this;
        }

        public Criteria andActionPerformanceIn(List<String> values) {
            addCriterion("action_performance in", values, "actionPerformance");
            return (Criteria) this;
        }

        public Criteria andActionPerformanceNotIn(List<String> values) {
            addCriterion("action_performance not in", values, "actionPerformance");
            return (Criteria) this;
        }

        public Criteria andActionPerformanceBetween(String value1, String value2) {
            addCriterion("action_performance between", value1, value2, "actionPerformance");
            return (Criteria) this;
        }

        public Criteria andActionPerformanceNotBetween(String value1, String value2) {
            addCriterion("action_performance not between", value1, value2, "actionPerformance");
            return (Criteria) this;
        }

        public Criteria andOtherPerformanceIsNull() {
            addCriterion("other_performance is null");
            return (Criteria) this;
        }

        public Criteria andOtherPerformanceIsNotNull() {
            addCriterion("other_performance is not null");
            return (Criteria) this;
        }

        public Criteria andOtherPerformanceEqualTo(String value) {
            addCriterion("other_performance =", value, "otherPerformance");
            return (Criteria) this;
        }

        public Criteria andOtherPerformanceNotEqualTo(String value) {
            addCriterion("other_performance <>", value, "otherPerformance");
            return (Criteria) this;
        }

        public Criteria andOtherPerformanceGreaterThan(String value) {
            addCriterion("other_performance >", value, "otherPerformance");
            return (Criteria) this;
        }

        public Criteria andOtherPerformanceGreaterThanOrEqualTo(String value) {
            addCriterion("other_performance >=", value, "otherPerformance");
            return (Criteria) this;
        }

        public Criteria andOtherPerformanceLessThan(String value) {
            addCriterion("other_performance <", value, "otherPerformance");
            return (Criteria) this;
        }

        public Criteria andOtherPerformanceLessThanOrEqualTo(String value) {
            addCriterion("other_performance <=", value, "otherPerformance");
            return (Criteria) this;
        }

        public Criteria andOtherPerformanceLike(String value) {
            addCriterion("other_performance like", value, "otherPerformance");
            return (Criteria) this;
        }

        public Criteria andOtherPerformanceNotLike(String value) {
            addCriterion("other_performance not like", value, "otherPerformance");
            return (Criteria) this;
        }

        public Criteria andOtherPerformanceIn(List<String> values) {
            addCriterion("other_performance in", values, "otherPerformance");
            return (Criteria) this;
        }

        public Criteria andOtherPerformanceNotIn(List<String> values) {
            addCriterion("other_performance not in", values, "otherPerformance");
            return (Criteria) this;
        }

        public Criteria andOtherPerformanceBetween(String value1, String value2) {
            addCriterion("other_performance between", value1, value2, "otherPerformance");
            return (Criteria) this;
        }

        public Criteria andOtherPerformanceNotBetween(String value1, String value2) {
            addCriterion("other_performance not between", value1, value2, "otherPerformance");
            return (Criteria) this;
        }

        public Criteria andDifficultyIsNull() {
            addCriterion("difficulty is null");
            return (Criteria) this;
        }

        public Criteria andDifficultyIsNotNull() {
            addCriterion("difficulty is not null");
            return (Criteria) this;
        }

        public Criteria andDifficultyEqualTo(String value) {
            addCriterion("difficulty =", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyNotEqualTo(String value) {
            addCriterion("difficulty <>", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyGreaterThan(String value) {
            addCriterion("difficulty >", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyGreaterThanOrEqualTo(String value) {
            addCriterion("difficulty >=", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyLessThan(String value) {
            addCriterion("difficulty <", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyLessThanOrEqualTo(String value) {
            addCriterion("difficulty <=", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyLike(String value) {
            addCriterion("difficulty like", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyNotLike(String value) {
            addCriterion("difficulty not like", value, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyIn(List<String> values) {
            addCriterion("difficulty in", values, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyNotIn(List<String> values) {
            addCriterion("difficulty not in", values, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyBetween(String value1, String value2) {
            addCriterion("difficulty between", value1, value2, "difficulty");
            return (Criteria) this;
        }

        public Criteria andDifficultyNotBetween(String value1, String value2) {
            addCriterion("difficulty not between", value1, value2, "difficulty");
            return (Criteria) this;
        }

        public Criteria andGuidanceIsNull() {
            addCriterion("guidance is null");
            return (Criteria) this;
        }

        public Criteria andGuidanceIsNotNull() {
            addCriterion("guidance is not null");
            return (Criteria) this;
        }

        public Criteria andGuidanceEqualTo(String value) {
            addCriterion("guidance =", value, "guidance");
            return (Criteria) this;
        }

        public Criteria andGuidanceNotEqualTo(String value) {
            addCriterion("guidance <>", value, "guidance");
            return (Criteria) this;
        }

        public Criteria andGuidanceGreaterThan(String value) {
            addCriterion("guidance >", value, "guidance");
            return (Criteria) this;
        }

        public Criteria andGuidanceGreaterThanOrEqualTo(String value) {
            addCriterion("guidance >=", value, "guidance");
            return (Criteria) this;
        }

        public Criteria andGuidanceLessThan(String value) {
            addCriterion("guidance <", value, "guidance");
            return (Criteria) this;
        }

        public Criteria andGuidanceLessThanOrEqualTo(String value) {
            addCriterion("guidance <=", value, "guidance");
            return (Criteria) this;
        }

        public Criteria andGuidanceLike(String value) {
            addCriterion("guidance like", value, "guidance");
            return (Criteria) this;
        }

        public Criteria andGuidanceNotLike(String value) {
            addCriterion("guidance not like", value, "guidance");
            return (Criteria) this;
        }

        public Criteria andGuidanceIn(List<String> values) {
            addCriterion("guidance in", values, "guidance");
            return (Criteria) this;
        }

        public Criteria andGuidanceNotIn(List<String> values) {
            addCriterion("guidance not in", values, "guidance");
            return (Criteria) this;
        }

        public Criteria andGuidanceBetween(String value1, String value2) {
            addCriterion("guidance between", value1, value2, "guidance");
            return (Criteria) this;
        }

        public Criteria andGuidanceNotBetween(String value1, String value2) {
            addCriterion("guidance not between", value1, value2, "guidance");
            return (Criteria) this;
        }

        public Criteria andAssistanceIsNull() {
            addCriterion("assistance is null");
            return (Criteria) this;
        }

        public Criteria andAssistanceIsNotNull() {
            addCriterion("assistance is not null");
            return (Criteria) this;
        }

        public Criteria andAssistanceEqualTo(String value) {
            addCriterion("assistance =", value, "assistance");
            return (Criteria) this;
        }

        public Criteria andAssistanceNotEqualTo(String value) {
            addCriterion("assistance <>", value, "assistance");
            return (Criteria) this;
        }

        public Criteria andAssistanceGreaterThan(String value) {
            addCriterion("assistance >", value, "assistance");
            return (Criteria) this;
        }

        public Criteria andAssistanceGreaterThanOrEqualTo(String value) {
            addCriterion("assistance >=", value, "assistance");
            return (Criteria) this;
        }

        public Criteria andAssistanceLessThan(String value) {
            addCriterion("assistance <", value, "assistance");
            return (Criteria) this;
        }

        public Criteria andAssistanceLessThanOrEqualTo(String value) {
            addCriterion("assistance <=", value, "assistance");
            return (Criteria) this;
        }

        public Criteria andAssistanceLike(String value) {
            addCriterion("assistance like", value, "assistance");
            return (Criteria) this;
        }

        public Criteria andAssistanceNotLike(String value) {
            addCriterion("assistance not like", value, "assistance");
            return (Criteria) this;
        }

        public Criteria andAssistanceIn(List<String> values) {
            addCriterion("assistance in", values, "assistance");
            return (Criteria) this;
        }

        public Criteria andAssistanceNotIn(List<String> values) {
            addCriterion("assistance not in", values, "assistance");
            return (Criteria) this;
        }

        public Criteria andAssistanceBetween(String value1, String value2) {
            addCriterion("assistance between", value1, value2, "assistance");
            return (Criteria) this;
        }

        public Criteria andAssistanceNotBetween(String value1, String value2) {
            addCriterion("assistance not between", value1, value2, "assistance");
            return (Criteria) this;
        }

        public Criteria andSuggestionIsNull() {
            addCriterion("suggestion is null");
            return (Criteria) this;
        }

        public Criteria andSuggestionIsNotNull() {
            addCriterion("suggestion is not null");
            return (Criteria) this;
        }

        public Criteria andSuggestionEqualTo(String value) {
            addCriterion("suggestion =", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotEqualTo(String value) {
            addCriterion("suggestion <>", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionGreaterThan(String value) {
            addCriterion("suggestion >", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionGreaterThanOrEqualTo(String value) {
            addCriterion("suggestion >=", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionLessThan(String value) {
            addCriterion("suggestion <", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionLessThanOrEqualTo(String value) {
            addCriterion("suggestion <=", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionLike(String value) {
            addCriterion("suggestion like", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotLike(String value) {
            addCriterion("suggestion not like", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionIn(List<String> values) {
            addCriterion("suggestion in", values, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotIn(List<String> values) {
            addCriterion("suggestion not in", values, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionBetween(String value1, String value2) {
            addCriterion("suggestion between", value1, value2, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotBetween(String value1, String value2) {
            addCriterion("suggestion not between", value1, value2, "suggestion");
            return (Criteria) this;
        }

        public Criteria andVisitorIsNull() {
            addCriterion("visitor is null");
            return (Criteria) this;
        }

        public Criteria andVisitorIsNotNull() {
            addCriterion("visitor is not null");
            return (Criteria) this;
        }

        public Criteria andVisitorEqualTo(String value) {
            addCriterion("visitor =", value, "visitor");
            return (Criteria) this;
        }

        public Criteria andVisitorNotEqualTo(String value) {
            addCriterion("visitor <>", value, "visitor");
            return (Criteria) this;
        }

        public Criteria andVisitorGreaterThan(String value) {
            addCriterion("visitor >", value, "visitor");
            return (Criteria) this;
        }

        public Criteria andVisitorGreaterThanOrEqualTo(String value) {
            addCriterion("visitor >=", value, "visitor");
            return (Criteria) this;
        }

        public Criteria andVisitorLessThan(String value) {
            addCriterion("visitor <", value, "visitor");
            return (Criteria) this;
        }

        public Criteria andVisitorLessThanOrEqualTo(String value) {
            addCriterion("visitor <=", value, "visitor");
            return (Criteria) this;
        }

        public Criteria andVisitorLike(String value) {
            addCriterion("visitor like", value, "visitor");
            return (Criteria) this;
        }

        public Criteria andVisitorNotLike(String value) {
            addCriterion("visitor not like", value, "visitor");
            return (Criteria) this;
        }

        public Criteria andVisitorIn(List<String> values) {
            addCriterion("visitor in", values, "visitor");
            return (Criteria) this;
        }

        public Criteria andVisitorNotIn(List<String> values) {
            addCriterion("visitor not in", values, "visitor");
            return (Criteria) this;
        }

        public Criteria andVisitorBetween(String value1, String value2) {
            addCriterion("visitor between", value1, value2, "visitor");
            return (Criteria) this;
        }

        public Criteria andVisitorNotBetween(String value1, String value2) {
            addCriterion("visitor not between", value1, value2, "visitor");
            return (Criteria) this;
        }

        public Criteria andVisitTimeIsNull() {
            addCriterion("visit_time is null");
            return (Criteria) this;
        }

        public Criteria andVisitTimeIsNotNull() {
            addCriterion("visit_time is not null");
            return (Criteria) this;
        }

        public Criteria andVisitTimeEqualTo(Date value) {
            addCriterionForJDBCDate("visit_time =", value, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("visit_time <>", value, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("visit_time >", value, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("visit_time >=", value, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeLessThan(Date value) {
            addCriterionForJDBCDate("visit_time <", value, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("visit_time <=", value, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeIn(List<Date> values) {
            addCriterionForJDBCDate("visit_time in", values, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("visit_time not in", values, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("visit_time between", value1, value2, "visitTime");
            return (Criteria) this;
        }

        public Criteria andVisitTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("visit_time not between", value1, value2, "visitTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_edu_track
     *
     * @mbggenerated do_not_delete_during_merge Sat Aug 03 13:22:26 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_edu_track
     *
     * @mbggenerated Sat Aug 03 13:22:26 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}