package com.xingyu.domain.po;

import java.util.ArrayList;
import java.util.List;

public class SdFamilyInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    public SdFamilyInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andArchiveNoIsNull() {
            addCriterion("archive_no is null");
            return (Criteria) this;
        }

        public Criteria andArchiveNoIsNotNull() {
            addCriterion("archive_no is not null");
            return (Criteria) this;
        }

        public Criteria andArchiveNoEqualTo(String value) {
            addCriterion("archive_no =", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotEqualTo(String value) {
            addCriterion("archive_no <>", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoGreaterThan(String value) {
            addCriterion("archive_no >", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoGreaterThanOrEqualTo(String value) {
            addCriterion("archive_no >=", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoLessThan(String value) {
            addCriterion("archive_no <", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoLessThanOrEqualTo(String value) {
            addCriterion("archive_no <=", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoLike(String value) {
            addCriterion("archive_no like", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotLike(String value) {
            addCriterion("archive_no not like", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoIn(List<String> values) {
            addCriterion("archive_no in", values, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotIn(List<String> values) {
            addCriterion("archive_no not in", values, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoBetween(String value1, String value2) {
            addCriterion("archive_no between", value1, value2, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotBetween(String value1, String value2) {
            addCriterion("archive_no not between", value1, value2, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andFatherIsNull() {
            addCriterion("father is null");
            return (Criteria) this;
        }

        public Criteria andFatherIsNotNull() {
            addCriterion("father is not null");
            return (Criteria) this;
        }

        public Criteria andFatherEqualTo(String value) {
            addCriterion("father =", value, "father");
            return (Criteria) this;
        }

        public Criteria andFatherNotEqualTo(String value) {
            addCriterion("father <>", value, "father");
            return (Criteria) this;
        }

        public Criteria andFatherGreaterThan(String value) {
            addCriterion("father >", value, "father");
            return (Criteria) this;
        }

        public Criteria andFatherGreaterThanOrEqualTo(String value) {
            addCriterion("father >=", value, "father");
            return (Criteria) this;
        }

        public Criteria andFatherLessThan(String value) {
            addCriterion("father <", value, "father");
            return (Criteria) this;
        }

        public Criteria andFatherLessThanOrEqualTo(String value) {
            addCriterion("father <=", value, "father");
            return (Criteria) this;
        }

        public Criteria andFatherLike(String value) {
            addCriterion("father like", value, "father");
            return (Criteria) this;
        }

        public Criteria andFatherNotLike(String value) {
            addCriterion("father not like", value, "father");
            return (Criteria) this;
        }

        public Criteria andFatherIn(List<String> values) {
            addCriterion("father in", values, "father");
            return (Criteria) this;
        }

        public Criteria andFatherNotIn(List<String> values) {
            addCriterion("father not in", values, "father");
            return (Criteria) this;
        }

        public Criteria andFatherBetween(String value1, String value2) {
            addCriterion("father between", value1, value2, "father");
            return (Criteria) this;
        }

        public Criteria andFatherNotBetween(String value1, String value2) {
            addCriterion("father not between", value1, value2, "father");
            return (Criteria) this;
        }

        public Criteria andFatherAgeIsNull() {
            addCriterion("father_age is null");
            return (Criteria) this;
        }

        public Criteria andFatherAgeIsNotNull() {
            addCriterion("father_age is not null");
            return (Criteria) this;
        }

        public Criteria andFatherAgeEqualTo(Integer value) {
            addCriterion("father_age =", value, "fatherAge");
            return (Criteria) this;
        }

        public Criteria andFatherAgeNotEqualTo(Integer value) {
            addCriterion("father_age <>", value, "fatherAge");
            return (Criteria) this;
        }

        public Criteria andFatherAgeGreaterThan(Integer value) {
            addCriterion("father_age >", value, "fatherAge");
            return (Criteria) this;
        }

        public Criteria andFatherAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("father_age >=", value, "fatherAge");
            return (Criteria) this;
        }

        public Criteria andFatherAgeLessThan(Integer value) {
            addCriterion("father_age <", value, "fatherAge");
            return (Criteria) this;
        }

        public Criteria andFatherAgeLessThanOrEqualTo(Integer value) {
            addCriterion("father_age <=", value, "fatherAge");
            return (Criteria) this;
        }

        public Criteria andFatherAgeIn(List<Integer> values) {
            addCriterion("father_age in", values, "fatherAge");
            return (Criteria) this;
        }

        public Criteria andFatherAgeNotIn(List<Integer> values) {
            addCriterion("father_age not in", values, "fatherAge");
            return (Criteria) this;
        }

        public Criteria andFatherAgeBetween(Integer value1, Integer value2) {
            addCriterion("father_age between", value1, value2, "fatherAge");
            return (Criteria) this;
        }

        public Criteria andFatherAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("father_age not between", value1, value2, "fatherAge");
            return (Criteria) this;
        }

        public Criteria andFatherEduIsNull() {
            addCriterion("father_edu is null");
            return (Criteria) this;
        }

        public Criteria andFatherEduIsNotNull() {
            addCriterion("father_edu is not null");
            return (Criteria) this;
        }

        public Criteria andFatherEduEqualTo(String value) {
            addCriterion("father_edu =", value, "fatherEdu");
            return (Criteria) this;
        }

        public Criteria andFatherEduNotEqualTo(String value) {
            addCriterion("father_edu <>", value, "fatherEdu");
            return (Criteria) this;
        }

        public Criteria andFatherEduGreaterThan(String value) {
            addCriterion("father_edu >", value, "fatherEdu");
            return (Criteria) this;
        }

        public Criteria andFatherEduGreaterThanOrEqualTo(String value) {
            addCriterion("father_edu >=", value, "fatherEdu");
            return (Criteria) this;
        }

        public Criteria andFatherEduLessThan(String value) {
            addCriterion("father_edu <", value, "fatherEdu");
            return (Criteria) this;
        }

        public Criteria andFatherEduLessThanOrEqualTo(String value) {
            addCriterion("father_edu <=", value, "fatherEdu");
            return (Criteria) this;
        }

        public Criteria andFatherEduLike(String value) {
            addCriterion("father_edu like", value, "fatherEdu");
            return (Criteria) this;
        }

        public Criteria andFatherEduNotLike(String value) {
            addCriterion("father_edu not like", value, "fatherEdu");
            return (Criteria) this;
        }

        public Criteria andFatherEduIn(List<String> values) {
            addCriterion("father_edu in", values, "fatherEdu");
            return (Criteria) this;
        }

        public Criteria andFatherEduNotIn(List<String> values) {
            addCriterion("father_edu not in", values, "fatherEdu");
            return (Criteria) this;
        }

        public Criteria andFatherEduBetween(String value1, String value2) {
            addCriterion("father_edu between", value1, value2, "fatherEdu");
            return (Criteria) this;
        }

        public Criteria andFatherEduNotBetween(String value1, String value2) {
            addCriterion("father_edu not between", value1, value2, "fatherEdu");
            return (Criteria) this;
        }

        public Criteria andFatherIdIsNull() {
            addCriterion("father_ID is null");
            return (Criteria) this;
        }

        public Criteria andFatherIdIsNotNull() {
            addCriterion("father_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFatherIdEqualTo(String value) {
            addCriterion("father_ID =", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdNotEqualTo(String value) {
            addCriterion("father_ID <>", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdGreaterThan(String value) {
            addCriterion("father_ID >", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdGreaterThanOrEqualTo(String value) {
            addCriterion("father_ID >=", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdLessThan(String value) {
            addCriterion("father_ID <", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdLessThanOrEqualTo(String value) {
            addCriterion("father_ID <=", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdLike(String value) {
            addCriterion("father_ID like", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdNotLike(String value) {
            addCriterion("father_ID not like", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdIn(List<String> values) {
            addCriterion("father_ID in", values, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdNotIn(List<String> values) {
            addCriterion("father_ID not in", values, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdBetween(String value1, String value2) {
            addCriterion("father_ID between", value1, value2, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdNotBetween(String value1, String value2) {
            addCriterion("father_ID not between", value1, value2, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherMobileIsNull() {
            addCriterion("father_mobile is null");
            return (Criteria) this;
        }

        public Criteria andFatherMobileIsNotNull() {
            addCriterion("father_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andFatherMobileEqualTo(String value) {
            addCriterion("father_mobile =", value, "fatherMobile");
            return (Criteria) this;
        }

        public Criteria andFatherMobileNotEqualTo(String value) {
            addCriterion("father_mobile <>", value, "fatherMobile");
            return (Criteria) this;
        }

        public Criteria andFatherMobileGreaterThan(String value) {
            addCriterion("father_mobile >", value, "fatherMobile");
            return (Criteria) this;
        }

        public Criteria andFatherMobileGreaterThanOrEqualTo(String value) {
            addCriterion("father_mobile >=", value, "fatherMobile");
            return (Criteria) this;
        }

        public Criteria andFatherMobileLessThan(String value) {
            addCriterion("father_mobile <", value, "fatherMobile");
            return (Criteria) this;
        }

        public Criteria andFatherMobileLessThanOrEqualTo(String value) {
            addCriterion("father_mobile <=", value, "fatherMobile");
            return (Criteria) this;
        }

        public Criteria andFatherMobileLike(String value) {
            addCriterion("father_mobile like", value, "fatherMobile");
            return (Criteria) this;
        }

        public Criteria andFatherMobileNotLike(String value) {
            addCriterion("father_mobile not like", value, "fatherMobile");
            return (Criteria) this;
        }

        public Criteria andFatherMobileIn(List<String> values) {
            addCriterion("father_mobile in", values, "fatherMobile");
            return (Criteria) this;
        }

        public Criteria andFatherMobileNotIn(List<String> values) {
            addCriterion("father_mobile not in", values, "fatherMobile");
            return (Criteria) this;
        }

        public Criteria andFatherMobileBetween(String value1, String value2) {
            addCriterion("father_mobile between", value1, value2, "fatherMobile");
            return (Criteria) this;
        }

        public Criteria andFatherMobileNotBetween(String value1, String value2) {
            addCriterion("father_mobile not between", value1, value2, "fatherMobile");
            return (Criteria) this;
        }

        public Criteria andMotherIsNull() {
            addCriterion("mother is null");
            return (Criteria) this;
        }

        public Criteria andMotherIsNotNull() {
            addCriterion("mother is not null");
            return (Criteria) this;
        }

        public Criteria andMotherEqualTo(String value) {
            addCriterion("mother =", value, "mother");
            return (Criteria) this;
        }

        public Criteria andMotherNotEqualTo(String value) {
            addCriterion("mother <>", value, "mother");
            return (Criteria) this;
        }

        public Criteria andMotherGreaterThan(String value) {
            addCriterion("mother >", value, "mother");
            return (Criteria) this;
        }

        public Criteria andMotherGreaterThanOrEqualTo(String value) {
            addCriterion("mother >=", value, "mother");
            return (Criteria) this;
        }

        public Criteria andMotherLessThan(String value) {
            addCriterion("mother <", value, "mother");
            return (Criteria) this;
        }

        public Criteria andMotherLessThanOrEqualTo(String value) {
            addCriterion("mother <=", value, "mother");
            return (Criteria) this;
        }

        public Criteria andMotherLike(String value) {
            addCriterion("mother like", value, "mother");
            return (Criteria) this;
        }

        public Criteria andMotherNotLike(String value) {
            addCriterion("mother not like", value, "mother");
            return (Criteria) this;
        }

        public Criteria andMotherIn(List<String> values) {
            addCriterion("mother in", values, "mother");
            return (Criteria) this;
        }

        public Criteria andMotherNotIn(List<String> values) {
            addCriterion("mother not in", values, "mother");
            return (Criteria) this;
        }

        public Criteria andMotherBetween(String value1, String value2) {
            addCriterion("mother between", value1, value2, "mother");
            return (Criteria) this;
        }

        public Criteria andMotherNotBetween(String value1, String value2) {
            addCriterion("mother not between", value1, value2, "mother");
            return (Criteria) this;
        }

        public Criteria andMotherAgeIsNull() {
            addCriterion("mother_age is null");
            return (Criteria) this;
        }

        public Criteria andMotherAgeIsNotNull() {
            addCriterion("mother_age is not null");
            return (Criteria) this;
        }

        public Criteria andMotherAgeEqualTo(Integer value) {
            addCriterion("mother_age =", value, "motherAge");
            return (Criteria) this;
        }

        public Criteria andMotherAgeNotEqualTo(Integer value) {
            addCriterion("mother_age <>", value, "motherAge");
            return (Criteria) this;
        }

        public Criteria andMotherAgeGreaterThan(Integer value) {
            addCriterion("mother_age >", value, "motherAge");
            return (Criteria) this;
        }

        public Criteria andMotherAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("mother_age >=", value, "motherAge");
            return (Criteria) this;
        }

        public Criteria andMotherAgeLessThan(Integer value) {
            addCriterion("mother_age <", value, "motherAge");
            return (Criteria) this;
        }

        public Criteria andMotherAgeLessThanOrEqualTo(Integer value) {
            addCriterion("mother_age <=", value, "motherAge");
            return (Criteria) this;
        }

        public Criteria andMotherAgeIn(List<Integer> values) {
            addCriterion("mother_age in", values, "motherAge");
            return (Criteria) this;
        }

        public Criteria andMotherAgeNotIn(List<Integer> values) {
            addCriterion("mother_age not in", values, "motherAge");
            return (Criteria) this;
        }

        public Criteria andMotherAgeBetween(Integer value1, Integer value2) {
            addCriterion("mother_age between", value1, value2, "motherAge");
            return (Criteria) this;
        }

        public Criteria andMotherAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("mother_age not between", value1, value2, "motherAge");
            return (Criteria) this;
        }

        public Criteria andMotherEduIsNull() {
            addCriterion("mother_edu is null");
            return (Criteria) this;
        }

        public Criteria andMotherEduIsNotNull() {
            addCriterion("mother_edu is not null");
            return (Criteria) this;
        }

        public Criteria andMotherEduEqualTo(String value) {
            addCriterion("mother_edu =", value, "motherEdu");
            return (Criteria) this;
        }

        public Criteria andMotherEduNotEqualTo(String value) {
            addCriterion("mother_edu <>", value, "motherEdu");
            return (Criteria) this;
        }

        public Criteria andMotherEduGreaterThan(String value) {
            addCriterion("mother_edu >", value, "motherEdu");
            return (Criteria) this;
        }

        public Criteria andMotherEduGreaterThanOrEqualTo(String value) {
            addCriterion("mother_edu >=", value, "motherEdu");
            return (Criteria) this;
        }

        public Criteria andMotherEduLessThan(String value) {
            addCriterion("mother_edu <", value, "motherEdu");
            return (Criteria) this;
        }

        public Criteria andMotherEduLessThanOrEqualTo(String value) {
            addCriterion("mother_edu <=", value, "motherEdu");
            return (Criteria) this;
        }

        public Criteria andMotherEduLike(String value) {
            addCriterion("mother_edu like", value, "motherEdu");
            return (Criteria) this;
        }

        public Criteria andMotherEduNotLike(String value) {
            addCriterion("mother_edu not like", value, "motherEdu");
            return (Criteria) this;
        }

        public Criteria andMotherEduIn(List<String> values) {
            addCriterion("mother_edu in", values, "motherEdu");
            return (Criteria) this;
        }

        public Criteria andMotherEduNotIn(List<String> values) {
            addCriterion("mother_edu not in", values, "motherEdu");
            return (Criteria) this;
        }

        public Criteria andMotherEduBetween(String value1, String value2) {
            addCriterion("mother_edu between", value1, value2, "motherEdu");
            return (Criteria) this;
        }

        public Criteria andMotherEduNotBetween(String value1, String value2) {
            addCriterion("mother_edu not between", value1, value2, "motherEdu");
            return (Criteria) this;
        }

        public Criteria andMotherIdIsNull() {
            addCriterion("mother_ID is null");
            return (Criteria) this;
        }

        public Criteria andMotherIdIsNotNull() {
            addCriterion("mother_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMotherIdEqualTo(String value) {
            addCriterion("mother_ID =", value, "motherId");
            return (Criteria) this;
        }

        public Criteria andMotherIdNotEqualTo(String value) {
            addCriterion("mother_ID <>", value, "motherId");
            return (Criteria) this;
        }

        public Criteria andMotherIdGreaterThan(String value) {
            addCriterion("mother_ID >", value, "motherId");
            return (Criteria) this;
        }

        public Criteria andMotherIdGreaterThanOrEqualTo(String value) {
            addCriterion("mother_ID >=", value, "motherId");
            return (Criteria) this;
        }

        public Criteria andMotherIdLessThan(String value) {
            addCriterion("mother_ID <", value, "motherId");
            return (Criteria) this;
        }

        public Criteria andMotherIdLessThanOrEqualTo(String value) {
            addCriterion("mother_ID <=", value, "motherId");
            return (Criteria) this;
        }

        public Criteria andMotherIdLike(String value) {
            addCriterion("mother_ID like", value, "motherId");
            return (Criteria) this;
        }

        public Criteria andMotherIdNotLike(String value) {
            addCriterion("mother_ID not like", value, "motherId");
            return (Criteria) this;
        }

        public Criteria andMotherIdIn(List<String> values) {
            addCriterion("mother_ID in", values, "motherId");
            return (Criteria) this;
        }

        public Criteria andMotherIdNotIn(List<String> values) {
            addCriterion("mother_ID not in", values, "motherId");
            return (Criteria) this;
        }

        public Criteria andMotherIdBetween(String value1, String value2) {
            addCriterion("mother_ID between", value1, value2, "motherId");
            return (Criteria) this;
        }

        public Criteria andMotherIdNotBetween(String value1, String value2) {
            addCriterion("mother_ID not between", value1, value2, "motherId");
            return (Criteria) this;
        }

        public Criteria andMotherMobileIsNull() {
            addCriterion("mother_mobile is null");
            return (Criteria) this;
        }

        public Criteria andMotherMobileIsNotNull() {
            addCriterion("mother_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMotherMobileEqualTo(String value) {
            addCriterion("mother_mobile =", value, "motherMobile");
            return (Criteria) this;
        }

        public Criteria andMotherMobileNotEqualTo(String value) {
            addCriterion("mother_mobile <>", value, "motherMobile");
            return (Criteria) this;
        }

        public Criteria andMotherMobileGreaterThan(String value) {
            addCriterion("mother_mobile >", value, "motherMobile");
            return (Criteria) this;
        }

        public Criteria andMotherMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mother_mobile >=", value, "motherMobile");
            return (Criteria) this;
        }

        public Criteria andMotherMobileLessThan(String value) {
            addCriterion("mother_mobile <", value, "motherMobile");
            return (Criteria) this;
        }

        public Criteria andMotherMobileLessThanOrEqualTo(String value) {
            addCriterion("mother_mobile <=", value, "motherMobile");
            return (Criteria) this;
        }

        public Criteria andMotherMobileLike(String value) {
            addCriterion("mother_mobile like", value, "motherMobile");
            return (Criteria) this;
        }

        public Criteria andMotherMobileNotLike(String value) {
            addCriterion("mother_mobile not like", value, "motherMobile");
            return (Criteria) this;
        }

        public Criteria andMotherMobileIn(List<String> values) {
            addCriterion("mother_mobile in", values, "motherMobile");
            return (Criteria) this;
        }

        public Criteria andMotherMobileNotIn(List<String> values) {
            addCriterion("mother_mobile not in", values, "motherMobile");
            return (Criteria) this;
        }

        public Criteria andMotherMobileBetween(String value1, String value2) {
            addCriterion("mother_mobile between", value1, value2, "motherMobile");
            return (Criteria) this;
        }

        public Criteria andMotherMobileNotBetween(String value1, String value2) {
            addCriterion("mother_mobile not between", value1, value2, "motherMobile");
            return (Criteria) this;
        }

        public Criteria andOtherIsNull() {
            addCriterion("other is null");
            return (Criteria) this;
        }

        public Criteria andOtherIsNotNull() {
            addCriterion("other is not null");
            return (Criteria) this;
        }

        public Criteria andOtherEqualTo(String value) {
            addCriterion("other =", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotEqualTo(String value) {
            addCriterion("other <>", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherGreaterThan(String value) {
            addCriterion("other >", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherGreaterThanOrEqualTo(String value) {
            addCriterion("other >=", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherLessThan(String value) {
            addCriterion("other <", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherLessThanOrEqualTo(String value) {
            addCriterion("other <=", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherLike(String value) {
            addCriterion("other like", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotLike(String value) {
            addCriterion("other not like", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherIn(List<String> values) {
            addCriterion("other in", values, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotIn(List<String> values) {
            addCriterion("other not in", values, "other");
            return (Criteria) this;
        }

        public Criteria andOtherBetween(String value1, String value2) {
            addCriterion("other between", value1, value2, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotBetween(String value1, String value2) {
            addCriterion("other not between", value1, value2, "other");
            return (Criteria) this;
        }

        public Criteria andOtherAgeIsNull() {
            addCriterion("other_age is null");
            return (Criteria) this;
        }

        public Criteria andOtherAgeIsNotNull() {
            addCriterion("other_age is not null");
            return (Criteria) this;
        }

        public Criteria andOtherAgeEqualTo(Integer value) {
            addCriterion("other_age =", value, "otherAge");
            return (Criteria) this;
        }

        public Criteria andOtherAgeNotEqualTo(Integer value) {
            addCriterion("other_age <>", value, "otherAge");
            return (Criteria) this;
        }

        public Criteria andOtherAgeGreaterThan(Integer value) {
            addCriterion("other_age >", value, "otherAge");
            return (Criteria) this;
        }

        public Criteria andOtherAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("other_age >=", value, "otherAge");
            return (Criteria) this;
        }

        public Criteria andOtherAgeLessThan(Integer value) {
            addCriterion("other_age <", value, "otherAge");
            return (Criteria) this;
        }

        public Criteria andOtherAgeLessThanOrEqualTo(Integer value) {
            addCriterion("other_age <=", value, "otherAge");
            return (Criteria) this;
        }

        public Criteria andOtherAgeIn(List<Integer> values) {
            addCriterion("other_age in", values, "otherAge");
            return (Criteria) this;
        }

        public Criteria andOtherAgeNotIn(List<Integer> values) {
            addCriterion("other_age not in", values, "otherAge");
            return (Criteria) this;
        }

        public Criteria andOtherAgeBetween(Integer value1, Integer value2) {
            addCriterion("other_age between", value1, value2, "otherAge");
            return (Criteria) this;
        }

        public Criteria andOtherAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("other_age not between", value1, value2, "otherAge");
            return (Criteria) this;
        }

        public Criteria andOtherEduIsNull() {
            addCriterion("other_edu is null");
            return (Criteria) this;
        }

        public Criteria andOtherEduIsNotNull() {
            addCriterion("other_edu is not null");
            return (Criteria) this;
        }

        public Criteria andOtherEduEqualTo(String value) {
            addCriterion("other_edu =", value, "otherEdu");
            return (Criteria) this;
        }

        public Criteria andOtherEduNotEqualTo(String value) {
            addCriterion("other_edu <>", value, "otherEdu");
            return (Criteria) this;
        }

        public Criteria andOtherEduGreaterThan(String value) {
            addCriterion("other_edu >", value, "otherEdu");
            return (Criteria) this;
        }

        public Criteria andOtherEduGreaterThanOrEqualTo(String value) {
            addCriterion("other_edu >=", value, "otherEdu");
            return (Criteria) this;
        }

        public Criteria andOtherEduLessThan(String value) {
            addCriterion("other_edu <", value, "otherEdu");
            return (Criteria) this;
        }

        public Criteria andOtherEduLessThanOrEqualTo(String value) {
            addCriterion("other_edu <=", value, "otherEdu");
            return (Criteria) this;
        }

        public Criteria andOtherEduLike(String value) {
            addCriterion("other_edu like", value, "otherEdu");
            return (Criteria) this;
        }

        public Criteria andOtherEduNotLike(String value) {
            addCriterion("other_edu not like", value, "otherEdu");
            return (Criteria) this;
        }

        public Criteria andOtherEduIn(List<String> values) {
            addCriterion("other_edu in", values, "otherEdu");
            return (Criteria) this;
        }

        public Criteria andOtherEduNotIn(List<String> values) {
            addCriterion("other_edu not in", values, "otherEdu");
            return (Criteria) this;
        }

        public Criteria andOtherEduBetween(String value1, String value2) {
            addCriterion("other_edu between", value1, value2, "otherEdu");
            return (Criteria) this;
        }

        public Criteria andOtherEduNotBetween(String value1, String value2) {
            addCriterion("other_edu not between", value1, value2, "otherEdu");
            return (Criteria) this;
        }

        public Criteria andOtherIdIsNull() {
            addCriterion("other_ID is null");
            return (Criteria) this;
        }

        public Criteria andOtherIdIsNotNull() {
            addCriterion("other_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOtherIdEqualTo(String value) {
            addCriterion("other_ID =", value, "otherId");
            return (Criteria) this;
        }

        public Criteria andOtherIdNotEqualTo(String value) {
            addCriterion("other_ID <>", value, "otherId");
            return (Criteria) this;
        }

        public Criteria andOtherIdGreaterThan(String value) {
            addCriterion("other_ID >", value, "otherId");
            return (Criteria) this;
        }

        public Criteria andOtherIdGreaterThanOrEqualTo(String value) {
            addCriterion("other_ID >=", value, "otherId");
            return (Criteria) this;
        }

        public Criteria andOtherIdLessThan(String value) {
            addCriterion("other_ID <", value, "otherId");
            return (Criteria) this;
        }

        public Criteria andOtherIdLessThanOrEqualTo(String value) {
            addCriterion("other_ID <=", value, "otherId");
            return (Criteria) this;
        }

        public Criteria andOtherIdLike(String value) {
            addCriterion("other_ID like", value, "otherId");
            return (Criteria) this;
        }

        public Criteria andOtherIdNotLike(String value) {
            addCriterion("other_ID not like", value, "otherId");
            return (Criteria) this;
        }

        public Criteria andOtherIdIn(List<String> values) {
            addCriterion("other_ID in", values, "otherId");
            return (Criteria) this;
        }

        public Criteria andOtherIdNotIn(List<String> values) {
            addCriterion("other_ID not in", values, "otherId");
            return (Criteria) this;
        }

        public Criteria andOtherIdBetween(String value1, String value2) {
            addCriterion("other_ID between", value1, value2, "otherId");
            return (Criteria) this;
        }

        public Criteria andOtherIdNotBetween(String value1, String value2) {
            addCriterion("other_ID not between", value1, value2, "otherId");
            return (Criteria) this;
        }

        public Criteria andOtherMobileIsNull() {
            addCriterion("other_mobile is null");
            return (Criteria) this;
        }

        public Criteria andOtherMobileIsNotNull() {
            addCriterion("other_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andOtherMobileEqualTo(String value) {
            addCriterion("other_mobile =", value, "otherMobile");
            return (Criteria) this;
        }

        public Criteria andOtherMobileNotEqualTo(String value) {
            addCriterion("other_mobile <>", value, "otherMobile");
            return (Criteria) this;
        }

        public Criteria andOtherMobileGreaterThan(String value) {
            addCriterion("other_mobile >", value, "otherMobile");
            return (Criteria) this;
        }

        public Criteria andOtherMobileGreaterThanOrEqualTo(String value) {
            addCriterion("other_mobile >=", value, "otherMobile");
            return (Criteria) this;
        }

        public Criteria andOtherMobileLessThan(String value) {
            addCriterion("other_mobile <", value, "otherMobile");
            return (Criteria) this;
        }

        public Criteria andOtherMobileLessThanOrEqualTo(String value) {
            addCriterion("other_mobile <=", value, "otherMobile");
            return (Criteria) this;
        }

        public Criteria andOtherMobileLike(String value) {
            addCriterion("other_mobile like", value, "otherMobile");
            return (Criteria) this;
        }

        public Criteria andOtherMobileNotLike(String value) {
            addCriterion("other_mobile not like", value, "otherMobile");
            return (Criteria) this;
        }

        public Criteria andOtherMobileIn(List<String> values) {
            addCriterion("other_mobile in", values, "otherMobile");
            return (Criteria) this;
        }

        public Criteria andOtherMobileNotIn(List<String> values) {
            addCriterion("other_mobile not in", values, "otherMobile");
            return (Criteria) this;
        }

        public Criteria andOtherMobileBetween(String value1, String value2) {
            addCriterion("other_mobile between", value1, value2, "otherMobile");
            return (Criteria) this;
        }

        public Criteria andOtherMobileNotBetween(String value1, String value2) {
            addCriterion("other_mobile not between", value1, value2, "otherMobile");
            return (Criteria) this;
        }

        public Criteria andFamilyModelIsNull() {
            addCriterion("family_model is null");
            return (Criteria) this;
        }

        public Criteria andFamilyModelIsNotNull() {
            addCriterion("family_model is not null");
            return (Criteria) this;
        }

        public Criteria andFamilyModelEqualTo(String value) {
            addCriterion("family_model =", value, "familyModel");
            return (Criteria) this;
        }

        public Criteria andFamilyModelNotEqualTo(String value) {
            addCriterion("family_model <>", value, "familyModel");
            return (Criteria) this;
        }

        public Criteria andFamilyModelGreaterThan(String value) {
            addCriterion("family_model >", value, "familyModel");
            return (Criteria) this;
        }

        public Criteria andFamilyModelGreaterThanOrEqualTo(String value) {
            addCriterion("family_model >=", value, "familyModel");
            return (Criteria) this;
        }

        public Criteria andFamilyModelLessThan(String value) {
            addCriterion("family_model <", value, "familyModel");
            return (Criteria) this;
        }

        public Criteria andFamilyModelLessThanOrEqualTo(String value) {
            addCriterion("family_model <=", value, "familyModel");
            return (Criteria) this;
        }

        public Criteria andFamilyModelLike(String value) {
            addCriterion("family_model like", value, "familyModel");
            return (Criteria) this;
        }

        public Criteria andFamilyModelNotLike(String value) {
            addCriterion("family_model not like", value, "familyModel");
            return (Criteria) this;
        }

        public Criteria andFamilyModelIn(List<String> values) {
            addCriterion("family_model in", values, "familyModel");
            return (Criteria) this;
        }

        public Criteria andFamilyModelNotIn(List<String> values) {
            addCriterion("family_model not in", values, "familyModel");
            return (Criteria) this;
        }

        public Criteria andFamilyModelBetween(String value1, String value2) {
            addCriterion("family_model between", value1, value2, "familyModel");
            return (Criteria) this;
        }

        public Criteria andFamilyModelNotBetween(String value1, String value2) {
            addCriterion("family_model not between", value1, value2, "familyModel");
            return (Criteria) this;
        }

        public Criteria andLiveEnvIsNull() {
            addCriterion("live_env is null");
            return (Criteria) this;
        }

        public Criteria andLiveEnvIsNotNull() {
            addCriterion("live_env is not null");
            return (Criteria) this;
        }

        public Criteria andLiveEnvEqualTo(String value) {
            addCriterion("live_env =", value, "liveEnv");
            return (Criteria) this;
        }

        public Criteria andLiveEnvNotEqualTo(String value) {
            addCriterion("live_env <>", value, "liveEnv");
            return (Criteria) this;
        }

        public Criteria andLiveEnvGreaterThan(String value) {
            addCriterion("live_env >", value, "liveEnv");
            return (Criteria) this;
        }

        public Criteria andLiveEnvGreaterThanOrEqualTo(String value) {
            addCriterion("live_env >=", value, "liveEnv");
            return (Criteria) this;
        }

        public Criteria andLiveEnvLessThan(String value) {
            addCriterion("live_env <", value, "liveEnv");
            return (Criteria) this;
        }

        public Criteria andLiveEnvLessThanOrEqualTo(String value) {
            addCriterion("live_env <=", value, "liveEnv");
            return (Criteria) this;
        }

        public Criteria andLiveEnvLike(String value) {
            addCriterion("live_env like", value, "liveEnv");
            return (Criteria) this;
        }

        public Criteria andLiveEnvNotLike(String value) {
            addCriterion("live_env not like", value, "liveEnv");
            return (Criteria) this;
        }

        public Criteria andLiveEnvIn(List<String> values) {
            addCriterion("live_env in", values, "liveEnv");
            return (Criteria) this;
        }

        public Criteria andLiveEnvNotIn(List<String> values) {
            addCriterion("live_env not in", values, "liveEnv");
            return (Criteria) this;
        }

        public Criteria andLiveEnvBetween(String value1, String value2) {
            addCriterion("live_env between", value1, value2, "liveEnv");
            return (Criteria) this;
        }

        public Criteria andLiveEnvNotBetween(String value1, String value2) {
            addCriterion("live_env not between", value1, value2, "liveEnv");
            return (Criteria) this;
        }

        public Criteria andRaisingTypeIsNull() {
            addCriterion("raising_type is null");
            return (Criteria) this;
        }

        public Criteria andRaisingTypeIsNotNull() {
            addCriterion("raising_type is not null");
            return (Criteria) this;
        }

        public Criteria andRaisingTypeEqualTo(String value) {
            addCriterion("raising_type =", value, "raisingType");
            return (Criteria) this;
        }

        public Criteria andRaisingTypeNotEqualTo(String value) {
            addCriterion("raising_type <>", value, "raisingType");
            return (Criteria) this;
        }

        public Criteria andRaisingTypeGreaterThan(String value) {
            addCriterion("raising_type >", value, "raisingType");
            return (Criteria) this;
        }

        public Criteria andRaisingTypeGreaterThanOrEqualTo(String value) {
            addCriterion("raising_type >=", value, "raisingType");
            return (Criteria) this;
        }

        public Criteria andRaisingTypeLessThan(String value) {
            addCriterion("raising_type <", value, "raisingType");
            return (Criteria) this;
        }

        public Criteria andRaisingTypeLessThanOrEqualTo(String value) {
            addCriterion("raising_type <=", value, "raisingType");
            return (Criteria) this;
        }

        public Criteria andRaisingTypeLike(String value) {
            addCriterion("raising_type like", value, "raisingType");
            return (Criteria) this;
        }

        public Criteria andRaisingTypeNotLike(String value) {
            addCriterion("raising_type not like", value, "raisingType");
            return (Criteria) this;
        }

        public Criteria andRaisingTypeIn(List<String> values) {
            addCriterion("raising_type in", values, "raisingType");
            return (Criteria) this;
        }

        public Criteria andRaisingTypeNotIn(List<String> values) {
            addCriterion("raising_type not in", values, "raisingType");
            return (Criteria) this;
        }

        public Criteria andRaisingTypeBetween(String value1, String value2) {
            addCriterion("raising_type between", value1, value2, "raisingType");
            return (Criteria) this;
        }

        public Criteria andRaisingTypeNotBetween(String value1, String value2) {
            addCriterion("raising_type not between", value1, value2, "raisingType");
            return (Criteria) this;
        }

        public Criteria andLanguageEnvIsNull() {
            addCriterion("language_env is null");
            return (Criteria) this;
        }

        public Criteria andLanguageEnvIsNotNull() {
            addCriterion("language_env is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEnvEqualTo(String value) {
            addCriterion("language_env =", value, "languageEnv");
            return (Criteria) this;
        }

        public Criteria andLanguageEnvNotEqualTo(String value) {
            addCriterion("language_env <>", value, "languageEnv");
            return (Criteria) this;
        }

        public Criteria andLanguageEnvGreaterThan(String value) {
            addCriterion("language_env >", value, "languageEnv");
            return (Criteria) this;
        }

        public Criteria andLanguageEnvGreaterThanOrEqualTo(String value) {
            addCriterion("language_env >=", value, "languageEnv");
            return (Criteria) this;
        }

        public Criteria andLanguageEnvLessThan(String value) {
            addCriterion("language_env <", value, "languageEnv");
            return (Criteria) this;
        }

        public Criteria andLanguageEnvLessThanOrEqualTo(String value) {
            addCriterion("language_env <=", value, "languageEnv");
            return (Criteria) this;
        }

        public Criteria andLanguageEnvLike(String value) {
            addCriterion("language_env like", value, "languageEnv");
            return (Criteria) this;
        }

        public Criteria andLanguageEnvNotLike(String value) {
            addCriterion("language_env not like", value, "languageEnv");
            return (Criteria) this;
        }

        public Criteria andLanguageEnvIn(List<String> values) {
            addCriterion("language_env in", values, "languageEnv");
            return (Criteria) this;
        }

        public Criteria andLanguageEnvNotIn(List<String> values) {
            addCriterion("language_env not in", values, "languageEnv");
            return (Criteria) this;
        }

        public Criteria andLanguageEnvBetween(String value1, String value2) {
            addCriterion("language_env between", value1, value2, "languageEnv");
            return (Criteria) this;
        }

        public Criteria andLanguageEnvNotBetween(String value1, String value2) {
            addCriterion("language_env not between", value1, value2, "languageEnv");
            return (Criteria) this;
        }

        public Criteria andGuarderIsNull() {
            addCriterion("guarder is null");
            return (Criteria) this;
        }

        public Criteria andGuarderIsNotNull() {
            addCriterion("guarder is not null");
            return (Criteria) this;
        }

        public Criteria andGuarderEqualTo(String value) {
            addCriterion("guarder =", value, "guarder");
            return (Criteria) this;
        }

        public Criteria andGuarderNotEqualTo(String value) {
            addCriterion("guarder <>", value, "guarder");
            return (Criteria) this;
        }

        public Criteria andGuarderGreaterThan(String value) {
            addCriterion("guarder >", value, "guarder");
            return (Criteria) this;
        }

        public Criteria andGuarderGreaterThanOrEqualTo(String value) {
            addCriterion("guarder >=", value, "guarder");
            return (Criteria) this;
        }

        public Criteria andGuarderLessThan(String value) {
            addCriterion("guarder <", value, "guarder");
            return (Criteria) this;
        }

        public Criteria andGuarderLessThanOrEqualTo(String value) {
            addCriterion("guarder <=", value, "guarder");
            return (Criteria) this;
        }

        public Criteria andGuarderLike(String value) {
            addCriterion("guarder like", value, "guarder");
            return (Criteria) this;
        }

        public Criteria andGuarderNotLike(String value) {
            addCriterion("guarder not like", value, "guarder");
            return (Criteria) this;
        }

        public Criteria andGuarderIn(List<String> values) {
            addCriterion("guarder in", values, "guarder");
            return (Criteria) this;
        }

        public Criteria andGuarderNotIn(List<String> values) {
            addCriterion("guarder not in", values, "guarder");
            return (Criteria) this;
        }

        public Criteria andGuarderBetween(String value1, String value2) {
            addCriterion("guarder between", value1, value2, "guarder");
            return (Criteria) this;
        }

        public Criteria andGuarderNotBetween(String value1, String value2) {
            addCriterion("guarder not between", value1, value2, "guarder");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_family_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 22 22:51:50 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_family_info
     *
     * @mbggenerated Mon Jul 22 22:51:50 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}