package com.xingyu.domain.po;

public class SdIEPItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_iep_item.id
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_iep_item.archive_no
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    private String archiveNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_iep_item.assess_times
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    private String assessTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_iep_item.catalog_id
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    private Integer catalogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_iep_item.catalog_name
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    private String catalogName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_iep_item.purpose_item_id
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    private Integer purposeItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_iep_item.purpose_item_name
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    private String purposeItemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_iep_item.iep_assess_result
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    private Integer iepAssessResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_iep_item.progress_assess_result
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    private String progressAssessResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_iep_item.id
     *
     * @return the value of sd_iep_item.id
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_iep_item.id
     *
     * @param id the value for sd_iep_item.id
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_iep_item.archive_no
     *
     * @return the value of sd_iep_item.archive_no
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public String getArchiveNo() {
        return archiveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_iep_item.archive_no
     *
     * @param archiveNo the value for sd_iep_item.archive_no
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public void setArchiveNo(String archiveNo) {
        this.archiveNo = archiveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_iep_item.assess_times
     *
     * @return the value of sd_iep_item.assess_times
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public String getAssessTimes() {
        return assessTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_iep_item.assess_times
     *
     * @param assessTimes the value for sd_iep_item.assess_times
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public void setAssessTimes(String assessTimes) {
        this.assessTimes = assessTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_iep_item.catalog_id
     *
     * @return the value of sd_iep_item.catalog_id
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public Integer getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_iep_item.catalog_id
     *
     * @param catalogId the value for sd_iep_item.catalog_id
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public void setCatalogId(Integer catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_iep_item.catalog_name
     *
     * @return the value of sd_iep_item.catalog_name
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public String getCatalogName() {
        return catalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_iep_item.catalog_name
     *
     * @param catalogName the value for sd_iep_item.catalog_name
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_iep_item.purpose_item_id
     *
     * @return the value of sd_iep_item.purpose_item_id
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public Integer getPurposeItemId() {
        return purposeItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_iep_item.purpose_item_id
     *
     * @param purposeItemId the value for sd_iep_item.purpose_item_id
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public void setPurposeItemId(Integer purposeItemId) {
        this.purposeItemId = purposeItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_iep_item.purpose_item_name
     *
     * @return the value of sd_iep_item.purpose_item_name
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public String getPurposeItemName() {
        return purposeItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_iep_item.purpose_item_name
     *
     * @param purposeItemName the value for sd_iep_item.purpose_item_name
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public void setPurposeItemName(String purposeItemName) {
        this.purposeItemName = purposeItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_iep_item.iep_assess_result
     *
     * @return the value of sd_iep_item.iep_assess_result
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public Integer getIepAssessResult() {
        return iepAssessResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_iep_item.iep_assess_result
     *
     * @param iepAssessResult the value for sd_iep_item.iep_assess_result
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public void setIepAssessResult(Integer iepAssessResult) {
        this.iepAssessResult = iepAssessResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_iep_item.progress_assess_result
     *
     * @return the value of sd_iep_item.progress_assess_result
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public String getProgressAssessResult() {
        return progressAssessResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_iep_item.progress_assess_result
     *
     * @param progressAssessResult the value for sd_iep_item.progress_assess_result
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    public void setProgressAssessResult(String progressAssessResult) {
        this.progressAssessResult = progressAssessResult;
    }
}