package com.xingyu.domain.po;

public class SdSelfInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.archive_no
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String archiveNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.pregnancy_age
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private Integer pregnancyAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.pregnancy_edu
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String pregnancyEdu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.abortion_signs
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String abortionSigns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.pregnancy_emotion
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String pregnancyEmotion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.pregnancy_health
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String pregnancyHealth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.pregnancy_env
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String pregnancyEnv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.birth_fulltime
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String birthFulltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.birth_process
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String birthProcess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.birth_mode
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String birthMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.birth_early
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String birthEarly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.birth_stifle
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String birthStifle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.birth_weight
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String birthWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.monther_milk
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String montherMilk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.manual_milk
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String manualMilk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.fever_convulsion
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String feverConvulsion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.rise_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String riseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.turnover_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String turnoverTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.creep_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String creepTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.smile_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String smileTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.sit_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String sitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.walk_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String walkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.voice_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String voiceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.word_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String wordTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_self_info.multiword_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    private String multiwordTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.archive_no
     *
     * @return the value of sd_self_info.archive_no
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getArchiveNo() {
        return archiveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.archive_no
     *
     * @param archiveNo the value for sd_self_info.archive_no
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setArchiveNo(String archiveNo) {
        this.archiveNo = archiveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.pregnancy_age
     *
     * @return the value of sd_self_info.pregnancy_age
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public Integer getPregnancyAge() {
        return pregnancyAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.pregnancy_age
     *
     * @param pregnancyAge the value for sd_self_info.pregnancy_age
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setPregnancyAge(Integer pregnancyAge) {
        this.pregnancyAge = pregnancyAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.pregnancy_edu
     *
     * @return the value of sd_self_info.pregnancy_edu
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getPregnancyEdu() {
        return pregnancyEdu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.pregnancy_edu
     *
     * @param pregnancyEdu the value for sd_self_info.pregnancy_edu
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setPregnancyEdu(String pregnancyEdu) {
        this.pregnancyEdu = pregnancyEdu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.abortion_signs
     *
     * @return the value of sd_self_info.abortion_signs
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getAbortionSigns() {
        return abortionSigns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.abortion_signs
     *
     * @param abortionSigns the value for sd_self_info.abortion_signs
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setAbortionSigns(String abortionSigns) {
        this.abortionSigns = abortionSigns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.pregnancy_emotion
     *
     * @return the value of sd_self_info.pregnancy_emotion
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getPregnancyEmotion() {
        return pregnancyEmotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.pregnancy_emotion
     *
     * @param pregnancyEmotion the value for sd_self_info.pregnancy_emotion
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setPregnancyEmotion(String pregnancyEmotion) {
        this.pregnancyEmotion = pregnancyEmotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.pregnancy_health
     *
     * @return the value of sd_self_info.pregnancy_health
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getPregnancyHealth() {
        return pregnancyHealth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.pregnancy_health
     *
     * @param pregnancyHealth the value for sd_self_info.pregnancy_health
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setPregnancyHealth(String pregnancyHealth) {
        this.pregnancyHealth = pregnancyHealth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.pregnancy_env
     *
     * @return the value of sd_self_info.pregnancy_env
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getPregnancyEnv() {
        return pregnancyEnv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.pregnancy_env
     *
     * @param pregnancyEnv the value for sd_self_info.pregnancy_env
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setPregnancyEnv(String pregnancyEnv) {
        this.pregnancyEnv = pregnancyEnv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.birth_fulltime
     *
     * @return the value of sd_self_info.birth_fulltime
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getBirthFulltime() {
        return birthFulltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.birth_fulltime
     *
     * @param birthFulltime the value for sd_self_info.birth_fulltime
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setBirthFulltime(String birthFulltime) {
        this.birthFulltime = birthFulltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.birth_process
     *
     * @return the value of sd_self_info.birth_process
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getBirthProcess() {
        return birthProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.birth_process
     *
     * @param birthProcess the value for sd_self_info.birth_process
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setBirthProcess(String birthProcess) {
        this.birthProcess = birthProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.birth_mode
     *
     * @return the value of sd_self_info.birth_mode
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getBirthMode() {
        return birthMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.birth_mode
     *
     * @param birthMode the value for sd_self_info.birth_mode
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setBirthMode(String birthMode) {
        this.birthMode = birthMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.birth_early
     *
     * @return the value of sd_self_info.birth_early
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getBirthEarly() {
        return birthEarly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.birth_early
     *
     * @param birthEarly the value for sd_self_info.birth_early
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setBirthEarly(String birthEarly) {
        this.birthEarly = birthEarly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.birth_stifle
     *
     * @return the value of sd_self_info.birth_stifle
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getBirthStifle() {
        return birthStifle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.birth_stifle
     *
     * @param birthStifle the value for sd_self_info.birth_stifle
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setBirthStifle(String birthStifle) {
        this.birthStifle = birthStifle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.birth_weight
     *
     * @return the value of sd_self_info.birth_weight
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getBirthWeight() {
        return birthWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.birth_weight
     *
     * @param birthWeight the value for sd_self_info.birth_weight
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setBirthWeight(String birthWeight) {
        this.birthWeight = birthWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.monther_milk
     *
     * @return the value of sd_self_info.monther_milk
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getMontherMilk() {
        return montherMilk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.monther_milk
     *
     * @param montherMilk the value for sd_self_info.monther_milk
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setMontherMilk(String montherMilk) {
        this.montherMilk = montherMilk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.manual_milk
     *
     * @return the value of sd_self_info.manual_milk
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getManualMilk() {
        return manualMilk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.manual_milk
     *
     * @param manualMilk the value for sd_self_info.manual_milk
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setManualMilk(String manualMilk) {
        this.manualMilk = manualMilk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.fever_convulsion
     *
     * @return the value of sd_self_info.fever_convulsion
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getFeverConvulsion() {
        return feverConvulsion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.fever_convulsion
     *
     * @param feverConvulsion the value for sd_self_info.fever_convulsion
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setFeverConvulsion(String feverConvulsion) {
        this.feverConvulsion = feverConvulsion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.rise_time
     *
     * @return the value of sd_self_info.rise_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getRiseTime() {
        return riseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.rise_time
     *
     * @param riseTime the value for sd_self_info.rise_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setRiseTime(String riseTime) {
        this.riseTime = riseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.turnover_time
     *
     * @return the value of sd_self_info.turnover_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getTurnoverTime() {
        return turnoverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.turnover_time
     *
     * @param turnoverTime the value for sd_self_info.turnover_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setTurnoverTime(String turnoverTime) {
        this.turnoverTime = turnoverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.creep_time
     *
     * @return the value of sd_self_info.creep_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getCreepTime() {
        return creepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.creep_time
     *
     * @param creepTime the value for sd_self_info.creep_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setCreepTime(String creepTime) {
        this.creepTime = creepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.smile_time
     *
     * @return the value of sd_self_info.smile_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getSmileTime() {
        return smileTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.smile_time
     *
     * @param smileTime the value for sd_self_info.smile_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setSmileTime(String smileTime) {
        this.smileTime = smileTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.sit_time
     *
     * @return the value of sd_self_info.sit_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getSitTime() {
        return sitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.sit_time
     *
     * @param sitTime the value for sd_self_info.sit_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setSitTime(String sitTime) {
        this.sitTime = sitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.walk_time
     *
     * @return the value of sd_self_info.walk_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getWalkTime() {
        return walkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.walk_time
     *
     * @param walkTime the value for sd_self_info.walk_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setWalkTime(String walkTime) {
        this.walkTime = walkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.voice_time
     *
     * @return the value of sd_self_info.voice_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getVoiceTime() {
        return voiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.voice_time
     *
     * @param voiceTime the value for sd_self_info.voice_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setVoiceTime(String voiceTime) {
        this.voiceTime = voiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.word_time
     *
     * @return the value of sd_self_info.word_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getWordTime() {
        return wordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.word_time
     *
     * @param wordTime the value for sd_self_info.word_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setWordTime(String wordTime) {
        this.wordTime = wordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_self_info.multiword_time
     *
     * @return the value of sd_self_info.multiword_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getMultiwordTime() {
        return multiwordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_self_info.multiword_time
     *
     * @param multiwordTime the value for sd_self_info.multiword_time
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setMultiwordTime(String multiwordTime) {
        this.multiwordTime = multiwordTime;
    }
}