package com.xingyu.domain.po;

import java.util.ArrayList;
import java.util.List;

public class SdSelfInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public SdSelfInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andArchiveNoIsNull() {
            addCriterion("archive_no is null");
            return (Criteria) this;
        }

        public Criteria andArchiveNoIsNotNull() {
            addCriterion("archive_no is not null");
            return (Criteria) this;
        }

        public Criteria andArchiveNoEqualTo(String value) {
            addCriterion("archive_no =", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotEqualTo(String value) {
            addCriterion("archive_no <>", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoGreaterThan(String value) {
            addCriterion("archive_no >", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoGreaterThanOrEqualTo(String value) {
            addCriterion("archive_no >=", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoLessThan(String value) {
            addCriterion("archive_no <", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoLessThanOrEqualTo(String value) {
            addCriterion("archive_no <=", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoLike(String value) {
            addCriterion("archive_no like", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotLike(String value) {
            addCriterion("archive_no not like", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoIn(List<String> values) {
            addCriterion("archive_no in", values, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotIn(List<String> values) {
            addCriterion("archive_no not in", values, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoBetween(String value1, String value2) {
            addCriterion("archive_no between", value1, value2, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotBetween(String value1, String value2) {
            addCriterion("archive_no not between", value1, value2, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andPregnancyAgeIsNull() {
            addCriterion("pregnancy_age is null");
            return (Criteria) this;
        }

        public Criteria andPregnancyAgeIsNotNull() {
            addCriterion("pregnancy_age is not null");
            return (Criteria) this;
        }

        public Criteria andPregnancyAgeEqualTo(Integer value) {
            addCriterion("pregnancy_age =", value, "pregnancyAge");
            return (Criteria) this;
        }

        public Criteria andPregnancyAgeNotEqualTo(Integer value) {
            addCriterion("pregnancy_age <>", value, "pregnancyAge");
            return (Criteria) this;
        }

        public Criteria andPregnancyAgeGreaterThan(Integer value) {
            addCriterion("pregnancy_age >", value, "pregnancyAge");
            return (Criteria) this;
        }

        public Criteria andPregnancyAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("pregnancy_age >=", value, "pregnancyAge");
            return (Criteria) this;
        }

        public Criteria andPregnancyAgeLessThan(Integer value) {
            addCriterion("pregnancy_age <", value, "pregnancyAge");
            return (Criteria) this;
        }

        public Criteria andPregnancyAgeLessThanOrEqualTo(Integer value) {
            addCriterion("pregnancy_age <=", value, "pregnancyAge");
            return (Criteria) this;
        }

        public Criteria andPregnancyAgeIn(List<Integer> values) {
            addCriterion("pregnancy_age in", values, "pregnancyAge");
            return (Criteria) this;
        }

        public Criteria andPregnancyAgeNotIn(List<Integer> values) {
            addCriterion("pregnancy_age not in", values, "pregnancyAge");
            return (Criteria) this;
        }

        public Criteria andPregnancyAgeBetween(Integer value1, Integer value2) {
            addCriterion("pregnancy_age between", value1, value2, "pregnancyAge");
            return (Criteria) this;
        }

        public Criteria andPregnancyAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("pregnancy_age not between", value1, value2, "pregnancyAge");
            return (Criteria) this;
        }

        public Criteria andPregnancyEduIsNull() {
            addCriterion("pregnancy_edu is null");
            return (Criteria) this;
        }

        public Criteria andPregnancyEduIsNotNull() {
            addCriterion("pregnancy_edu is not null");
            return (Criteria) this;
        }

        public Criteria andPregnancyEduEqualTo(String value) {
            addCriterion("pregnancy_edu =", value, "pregnancyEdu");
            return (Criteria) this;
        }

        public Criteria andPregnancyEduNotEqualTo(String value) {
            addCriterion("pregnancy_edu <>", value, "pregnancyEdu");
            return (Criteria) this;
        }

        public Criteria andPregnancyEduGreaterThan(String value) {
            addCriterion("pregnancy_edu >", value, "pregnancyEdu");
            return (Criteria) this;
        }

        public Criteria andPregnancyEduGreaterThanOrEqualTo(String value) {
            addCriterion("pregnancy_edu >=", value, "pregnancyEdu");
            return (Criteria) this;
        }

        public Criteria andPregnancyEduLessThan(String value) {
            addCriterion("pregnancy_edu <", value, "pregnancyEdu");
            return (Criteria) this;
        }

        public Criteria andPregnancyEduLessThanOrEqualTo(String value) {
            addCriterion("pregnancy_edu <=", value, "pregnancyEdu");
            return (Criteria) this;
        }

        public Criteria andPregnancyEduLike(String value) {
            addCriterion("pregnancy_edu like", value, "pregnancyEdu");
            return (Criteria) this;
        }

        public Criteria andPregnancyEduNotLike(String value) {
            addCriterion("pregnancy_edu not like", value, "pregnancyEdu");
            return (Criteria) this;
        }

        public Criteria andPregnancyEduIn(List<String> values) {
            addCriterion("pregnancy_edu in", values, "pregnancyEdu");
            return (Criteria) this;
        }

        public Criteria andPregnancyEduNotIn(List<String> values) {
            addCriterion("pregnancy_edu not in", values, "pregnancyEdu");
            return (Criteria) this;
        }

        public Criteria andPregnancyEduBetween(String value1, String value2) {
            addCriterion("pregnancy_edu between", value1, value2, "pregnancyEdu");
            return (Criteria) this;
        }

        public Criteria andPregnancyEduNotBetween(String value1, String value2) {
            addCriterion("pregnancy_edu not between", value1, value2, "pregnancyEdu");
            return (Criteria) this;
        }

        public Criteria andAbortionSignsIsNull() {
            addCriterion("abortion_signs is null");
            return (Criteria) this;
        }

        public Criteria andAbortionSignsIsNotNull() {
            addCriterion("abortion_signs is not null");
            return (Criteria) this;
        }

        public Criteria andAbortionSignsEqualTo(String value) {
            addCriterion("abortion_signs =", value, "abortionSigns");
            return (Criteria) this;
        }

        public Criteria andAbortionSignsNotEqualTo(String value) {
            addCriterion("abortion_signs <>", value, "abortionSigns");
            return (Criteria) this;
        }

        public Criteria andAbortionSignsGreaterThan(String value) {
            addCriterion("abortion_signs >", value, "abortionSigns");
            return (Criteria) this;
        }

        public Criteria andAbortionSignsGreaterThanOrEqualTo(String value) {
            addCriterion("abortion_signs >=", value, "abortionSigns");
            return (Criteria) this;
        }

        public Criteria andAbortionSignsLessThan(String value) {
            addCriterion("abortion_signs <", value, "abortionSigns");
            return (Criteria) this;
        }

        public Criteria andAbortionSignsLessThanOrEqualTo(String value) {
            addCriterion("abortion_signs <=", value, "abortionSigns");
            return (Criteria) this;
        }

        public Criteria andAbortionSignsLike(String value) {
            addCriterion("abortion_signs like", value, "abortionSigns");
            return (Criteria) this;
        }

        public Criteria andAbortionSignsNotLike(String value) {
            addCriterion("abortion_signs not like", value, "abortionSigns");
            return (Criteria) this;
        }

        public Criteria andAbortionSignsIn(List<String> values) {
            addCriterion("abortion_signs in", values, "abortionSigns");
            return (Criteria) this;
        }

        public Criteria andAbortionSignsNotIn(List<String> values) {
            addCriterion("abortion_signs not in", values, "abortionSigns");
            return (Criteria) this;
        }

        public Criteria andAbortionSignsBetween(String value1, String value2) {
            addCriterion("abortion_signs between", value1, value2, "abortionSigns");
            return (Criteria) this;
        }

        public Criteria andAbortionSignsNotBetween(String value1, String value2) {
            addCriterion("abortion_signs not between", value1, value2, "abortionSigns");
            return (Criteria) this;
        }

        public Criteria andPregnancyEmotionIsNull() {
            addCriterion("pregnancy_emotion is null");
            return (Criteria) this;
        }

        public Criteria andPregnancyEmotionIsNotNull() {
            addCriterion("pregnancy_emotion is not null");
            return (Criteria) this;
        }

        public Criteria andPregnancyEmotionEqualTo(String value) {
            addCriterion("pregnancy_emotion =", value, "pregnancyEmotion");
            return (Criteria) this;
        }

        public Criteria andPregnancyEmotionNotEqualTo(String value) {
            addCriterion("pregnancy_emotion <>", value, "pregnancyEmotion");
            return (Criteria) this;
        }

        public Criteria andPregnancyEmotionGreaterThan(String value) {
            addCriterion("pregnancy_emotion >", value, "pregnancyEmotion");
            return (Criteria) this;
        }

        public Criteria andPregnancyEmotionGreaterThanOrEqualTo(String value) {
            addCriterion("pregnancy_emotion >=", value, "pregnancyEmotion");
            return (Criteria) this;
        }

        public Criteria andPregnancyEmotionLessThan(String value) {
            addCriterion("pregnancy_emotion <", value, "pregnancyEmotion");
            return (Criteria) this;
        }

        public Criteria andPregnancyEmotionLessThanOrEqualTo(String value) {
            addCriterion("pregnancy_emotion <=", value, "pregnancyEmotion");
            return (Criteria) this;
        }

        public Criteria andPregnancyEmotionLike(String value) {
            addCriterion("pregnancy_emotion like", value, "pregnancyEmotion");
            return (Criteria) this;
        }

        public Criteria andPregnancyEmotionNotLike(String value) {
            addCriterion("pregnancy_emotion not like", value, "pregnancyEmotion");
            return (Criteria) this;
        }

        public Criteria andPregnancyEmotionIn(List<String> values) {
            addCriterion("pregnancy_emotion in", values, "pregnancyEmotion");
            return (Criteria) this;
        }

        public Criteria andPregnancyEmotionNotIn(List<String> values) {
            addCriterion("pregnancy_emotion not in", values, "pregnancyEmotion");
            return (Criteria) this;
        }

        public Criteria andPregnancyEmotionBetween(String value1, String value2) {
            addCriterion("pregnancy_emotion between", value1, value2, "pregnancyEmotion");
            return (Criteria) this;
        }

        public Criteria andPregnancyEmotionNotBetween(String value1, String value2) {
            addCriterion("pregnancy_emotion not between", value1, value2, "pregnancyEmotion");
            return (Criteria) this;
        }

        public Criteria andPregnancyHealthIsNull() {
            addCriterion("pregnancy_health is null");
            return (Criteria) this;
        }

        public Criteria andPregnancyHealthIsNotNull() {
            addCriterion("pregnancy_health is not null");
            return (Criteria) this;
        }

        public Criteria andPregnancyHealthEqualTo(String value) {
            addCriterion("pregnancy_health =", value, "pregnancyHealth");
            return (Criteria) this;
        }

        public Criteria andPregnancyHealthNotEqualTo(String value) {
            addCriterion("pregnancy_health <>", value, "pregnancyHealth");
            return (Criteria) this;
        }

        public Criteria andPregnancyHealthGreaterThan(String value) {
            addCriterion("pregnancy_health >", value, "pregnancyHealth");
            return (Criteria) this;
        }

        public Criteria andPregnancyHealthGreaterThanOrEqualTo(String value) {
            addCriterion("pregnancy_health >=", value, "pregnancyHealth");
            return (Criteria) this;
        }

        public Criteria andPregnancyHealthLessThan(String value) {
            addCriterion("pregnancy_health <", value, "pregnancyHealth");
            return (Criteria) this;
        }

        public Criteria andPregnancyHealthLessThanOrEqualTo(String value) {
            addCriterion("pregnancy_health <=", value, "pregnancyHealth");
            return (Criteria) this;
        }

        public Criteria andPregnancyHealthLike(String value) {
            addCriterion("pregnancy_health like", value, "pregnancyHealth");
            return (Criteria) this;
        }

        public Criteria andPregnancyHealthNotLike(String value) {
            addCriterion("pregnancy_health not like", value, "pregnancyHealth");
            return (Criteria) this;
        }

        public Criteria andPregnancyHealthIn(List<String> values) {
            addCriterion("pregnancy_health in", values, "pregnancyHealth");
            return (Criteria) this;
        }

        public Criteria andPregnancyHealthNotIn(List<String> values) {
            addCriterion("pregnancy_health not in", values, "pregnancyHealth");
            return (Criteria) this;
        }

        public Criteria andPregnancyHealthBetween(String value1, String value2) {
            addCriterion("pregnancy_health between", value1, value2, "pregnancyHealth");
            return (Criteria) this;
        }

        public Criteria andPregnancyHealthNotBetween(String value1, String value2) {
            addCriterion("pregnancy_health not between", value1, value2, "pregnancyHealth");
            return (Criteria) this;
        }

        public Criteria andPregnancyEnvIsNull() {
            addCriterion("pregnancy_env is null");
            return (Criteria) this;
        }

        public Criteria andPregnancyEnvIsNotNull() {
            addCriterion("pregnancy_env is not null");
            return (Criteria) this;
        }

        public Criteria andPregnancyEnvEqualTo(String value) {
            addCriterion("pregnancy_env =", value, "pregnancyEnv");
            return (Criteria) this;
        }

        public Criteria andPregnancyEnvNotEqualTo(String value) {
            addCriterion("pregnancy_env <>", value, "pregnancyEnv");
            return (Criteria) this;
        }

        public Criteria andPregnancyEnvGreaterThan(String value) {
            addCriterion("pregnancy_env >", value, "pregnancyEnv");
            return (Criteria) this;
        }

        public Criteria andPregnancyEnvGreaterThanOrEqualTo(String value) {
            addCriterion("pregnancy_env >=", value, "pregnancyEnv");
            return (Criteria) this;
        }

        public Criteria andPregnancyEnvLessThan(String value) {
            addCriterion("pregnancy_env <", value, "pregnancyEnv");
            return (Criteria) this;
        }

        public Criteria andPregnancyEnvLessThanOrEqualTo(String value) {
            addCriterion("pregnancy_env <=", value, "pregnancyEnv");
            return (Criteria) this;
        }

        public Criteria andPregnancyEnvLike(String value) {
            addCriterion("pregnancy_env like", value, "pregnancyEnv");
            return (Criteria) this;
        }

        public Criteria andPregnancyEnvNotLike(String value) {
            addCriterion("pregnancy_env not like", value, "pregnancyEnv");
            return (Criteria) this;
        }

        public Criteria andPregnancyEnvIn(List<String> values) {
            addCriterion("pregnancy_env in", values, "pregnancyEnv");
            return (Criteria) this;
        }

        public Criteria andPregnancyEnvNotIn(List<String> values) {
            addCriterion("pregnancy_env not in", values, "pregnancyEnv");
            return (Criteria) this;
        }

        public Criteria andPregnancyEnvBetween(String value1, String value2) {
            addCriterion("pregnancy_env between", value1, value2, "pregnancyEnv");
            return (Criteria) this;
        }

        public Criteria andPregnancyEnvNotBetween(String value1, String value2) {
            addCriterion("pregnancy_env not between", value1, value2, "pregnancyEnv");
            return (Criteria) this;
        }

        public Criteria andBirthFulltimeIsNull() {
            addCriterion("birth_fulltime is null");
            return (Criteria) this;
        }

        public Criteria andBirthFulltimeIsNotNull() {
            addCriterion("birth_fulltime is not null");
            return (Criteria) this;
        }

        public Criteria andBirthFulltimeEqualTo(String value) {
            addCriterion("birth_fulltime =", value, "birthFulltime");
            return (Criteria) this;
        }

        public Criteria andBirthFulltimeNotEqualTo(String value) {
            addCriterion("birth_fulltime <>", value, "birthFulltime");
            return (Criteria) this;
        }

        public Criteria andBirthFulltimeGreaterThan(String value) {
            addCriterion("birth_fulltime >", value, "birthFulltime");
            return (Criteria) this;
        }

        public Criteria andBirthFulltimeGreaterThanOrEqualTo(String value) {
            addCriterion("birth_fulltime >=", value, "birthFulltime");
            return (Criteria) this;
        }

        public Criteria andBirthFulltimeLessThan(String value) {
            addCriterion("birth_fulltime <", value, "birthFulltime");
            return (Criteria) this;
        }

        public Criteria andBirthFulltimeLessThanOrEqualTo(String value) {
            addCriterion("birth_fulltime <=", value, "birthFulltime");
            return (Criteria) this;
        }

        public Criteria andBirthFulltimeLike(String value) {
            addCriterion("birth_fulltime like", value, "birthFulltime");
            return (Criteria) this;
        }

        public Criteria andBirthFulltimeNotLike(String value) {
            addCriterion("birth_fulltime not like", value, "birthFulltime");
            return (Criteria) this;
        }

        public Criteria andBirthFulltimeIn(List<String> values) {
            addCriterion("birth_fulltime in", values, "birthFulltime");
            return (Criteria) this;
        }

        public Criteria andBirthFulltimeNotIn(List<String> values) {
            addCriterion("birth_fulltime not in", values, "birthFulltime");
            return (Criteria) this;
        }

        public Criteria andBirthFulltimeBetween(String value1, String value2) {
            addCriterion("birth_fulltime between", value1, value2, "birthFulltime");
            return (Criteria) this;
        }

        public Criteria andBirthFulltimeNotBetween(String value1, String value2) {
            addCriterion("birth_fulltime not between", value1, value2, "birthFulltime");
            return (Criteria) this;
        }

        public Criteria andBirthProcessIsNull() {
            addCriterion("birth_process is null");
            return (Criteria) this;
        }

        public Criteria andBirthProcessIsNotNull() {
            addCriterion("birth_process is not null");
            return (Criteria) this;
        }

        public Criteria andBirthProcessEqualTo(String value) {
            addCriterion("birth_process =", value, "birthProcess");
            return (Criteria) this;
        }

        public Criteria andBirthProcessNotEqualTo(String value) {
            addCriterion("birth_process <>", value, "birthProcess");
            return (Criteria) this;
        }

        public Criteria andBirthProcessGreaterThan(String value) {
            addCriterion("birth_process >", value, "birthProcess");
            return (Criteria) this;
        }

        public Criteria andBirthProcessGreaterThanOrEqualTo(String value) {
            addCriterion("birth_process >=", value, "birthProcess");
            return (Criteria) this;
        }

        public Criteria andBirthProcessLessThan(String value) {
            addCriterion("birth_process <", value, "birthProcess");
            return (Criteria) this;
        }

        public Criteria andBirthProcessLessThanOrEqualTo(String value) {
            addCriterion("birth_process <=", value, "birthProcess");
            return (Criteria) this;
        }

        public Criteria andBirthProcessLike(String value) {
            addCriterion("birth_process like", value, "birthProcess");
            return (Criteria) this;
        }

        public Criteria andBirthProcessNotLike(String value) {
            addCriterion("birth_process not like", value, "birthProcess");
            return (Criteria) this;
        }

        public Criteria andBirthProcessIn(List<String> values) {
            addCriterion("birth_process in", values, "birthProcess");
            return (Criteria) this;
        }

        public Criteria andBirthProcessNotIn(List<String> values) {
            addCriterion("birth_process not in", values, "birthProcess");
            return (Criteria) this;
        }

        public Criteria andBirthProcessBetween(String value1, String value2) {
            addCriterion("birth_process between", value1, value2, "birthProcess");
            return (Criteria) this;
        }

        public Criteria andBirthProcessNotBetween(String value1, String value2) {
            addCriterion("birth_process not between", value1, value2, "birthProcess");
            return (Criteria) this;
        }

        public Criteria andBirthModeIsNull() {
            addCriterion("birth_mode is null");
            return (Criteria) this;
        }

        public Criteria andBirthModeIsNotNull() {
            addCriterion("birth_mode is not null");
            return (Criteria) this;
        }

        public Criteria andBirthModeEqualTo(String value) {
            addCriterion("birth_mode =", value, "birthMode");
            return (Criteria) this;
        }

        public Criteria andBirthModeNotEqualTo(String value) {
            addCriterion("birth_mode <>", value, "birthMode");
            return (Criteria) this;
        }

        public Criteria andBirthModeGreaterThan(String value) {
            addCriterion("birth_mode >", value, "birthMode");
            return (Criteria) this;
        }

        public Criteria andBirthModeGreaterThanOrEqualTo(String value) {
            addCriterion("birth_mode >=", value, "birthMode");
            return (Criteria) this;
        }

        public Criteria andBirthModeLessThan(String value) {
            addCriterion("birth_mode <", value, "birthMode");
            return (Criteria) this;
        }

        public Criteria andBirthModeLessThanOrEqualTo(String value) {
            addCriterion("birth_mode <=", value, "birthMode");
            return (Criteria) this;
        }

        public Criteria andBirthModeLike(String value) {
            addCriterion("birth_mode like", value, "birthMode");
            return (Criteria) this;
        }

        public Criteria andBirthModeNotLike(String value) {
            addCriterion("birth_mode not like", value, "birthMode");
            return (Criteria) this;
        }

        public Criteria andBirthModeIn(List<String> values) {
            addCriterion("birth_mode in", values, "birthMode");
            return (Criteria) this;
        }

        public Criteria andBirthModeNotIn(List<String> values) {
            addCriterion("birth_mode not in", values, "birthMode");
            return (Criteria) this;
        }

        public Criteria andBirthModeBetween(String value1, String value2) {
            addCriterion("birth_mode between", value1, value2, "birthMode");
            return (Criteria) this;
        }

        public Criteria andBirthModeNotBetween(String value1, String value2) {
            addCriterion("birth_mode not between", value1, value2, "birthMode");
            return (Criteria) this;
        }

        public Criteria andBirthEarlyIsNull() {
            addCriterion("birth_early is null");
            return (Criteria) this;
        }

        public Criteria andBirthEarlyIsNotNull() {
            addCriterion("birth_early is not null");
            return (Criteria) this;
        }

        public Criteria andBirthEarlyEqualTo(String value) {
            addCriterion("birth_early =", value, "birthEarly");
            return (Criteria) this;
        }

        public Criteria andBirthEarlyNotEqualTo(String value) {
            addCriterion("birth_early <>", value, "birthEarly");
            return (Criteria) this;
        }

        public Criteria andBirthEarlyGreaterThan(String value) {
            addCriterion("birth_early >", value, "birthEarly");
            return (Criteria) this;
        }

        public Criteria andBirthEarlyGreaterThanOrEqualTo(String value) {
            addCriterion("birth_early >=", value, "birthEarly");
            return (Criteria) this;
        }

        public Criteria andBirthEarlyLessThan(String value) {
            addCriterion("birth_early <", value, "birthEarly");
            return (Criteria) this;
        }

        public Criteria andBirthEarlyLessThanOrEqualTo(String value) {
            addCriterion("birth_early <=", value, "birthEarly");
            return (Criteria) this;
        }

        public Criteria andBirthEarlyLike(String value) {
            addCriterion("birth_early like", value, "birthEarly");
            return (Criteria) this;
        }

        public Criteria andBirthEarlyNotLike(String value) {
            addCriterion("birth_early not like", value, "birthEarly");
            return (Criteria) this;
        }

        public Criteria andBirthEarlyIn(List<String> values) {
            addCriterion("birth_early in", values, "birthEarly");
            return (Criteria) this;
        }

        public Criteria andBirthEarlyNotIn(List<String> values) {
            addCriterion("birth_early not in", values, "birthEarly");
            return (Criteria) this;
        }

        public Criteria andBirthEarlyBetween(String value1, String value2) {
            addCriterion("birth_early between", value1, value2, "birthEarly");
            return (Criteria) this;
        }

        public Criteria andBirthEarlyNotBetween(String value1, String value2) {
            addCriterion("birth_early not between", value1, value2, "birthEarly");
            return (Criteria) this;
        }

        public Criteria andBirthStifleIsNull() {
            addCriterion("birth_stifle is null");
            return (Criteria) this;
        }

        public Criteria andBirthStifleIsNotNull() {
            addCriterion("birth_stifle is not null");
            return (Criteria) this;
        }

        public Criteria andBirthStifleEqualTo(String value) {
            addCriterion("birth_stifle =", value, "birthStifle");
            return (Criteria) this;
        }

        public Criteria andBirthStifleNotEqualTo(String value) {
            addCriterion("birth_stifle <>", value, "birthStifle");
            return (Criteria) this;
        }

        public Criteria andBirthStifleGreaterThan(String value) {
            addCriterion("birth_stifle >", value, "birthStifle");
            return (Criteria) this;
        }

        public Criteria andBirthStifleGreaterThanOrEqualTo(String value) {
            addCriterion("birth_stifle >=", value, "birthStifle");
            return (Criteria) this;
        }

        public Criteria andBirthStifleLessThan(String value) {
            addCriterion("birth_stifle <", value, "birthStifle");
            return (Criteria) this;
        }

        public Criteria andBirthStifleLessThanOrEqualTo(String value) {
            addCriterion("birth_stifle <=", value, "birthStifle");
            return (Criteria) this;
        }

        public Criteria andBirthStifleLike(String value) {
            addCriterion("birth_stifle like", value, "birthStifle");
            return (Criteria) this;
        }

        public Criteria andBirthStifleNotLike(String value) {
            addCriterion("birth_stifle not like", value, "birthStifle");
            return (Criteria) this;
        }

        public Criteria andBirthStifleIn(List<String> values) {
            addCriterion("birth_stifle in", values, "birthStifle");
            return (Criteria) this;
        }

        public Criteria andBirthStifleNotIn(List<String> values) {
            addCriterion("birth_stifle not in", values, "birthStifle");
            return (Criteria) this;
        }

        public Criteria andBirthStifleBetween(String value1, String value2) {
            addCriterion("birth_stifle between", value1, value2, "birthStifle");
            return (Criteria) this;
        }

        public Criteria andBirthStifleNotBetween(String value1, String value2) {
            addCriterion("birth_stifle not between", value1, value2, "birthStifle");
            return (Criteria) this;
        }

        public Criteria andBirthWeightIsNull() {
            addCriterion("birth_weight is null");
            return (Criteria) this;
        }

        public Criteria andBirthWeightIsNotNull() {
            addCriterion("birth_weight is not null");
            return (Criteria) this;
        }

        public Criteria andBirthWeightEqualTo(String value) {
            addCriterion("birth_weight =", value, "birthWeight");
            return (Criteria) this;
        }

        public Criteria andBirthWeightNotEqualTo(String value) {
            addCriterion("birth_weight <>", value, "birthWeight");
            return (Criteria) this;
        }

        public Criteria andBirthWeightGreaterThan(String value) {
            addCriterion("birth_weight >", value, "birthWeight");
            return (Criteria) this;
        }

        public Criteria andBirthWeightGreaterThanOrEqualTo(String value) {
            addCriterion("birth_weight >=", value, "birthWeight");
            return (Criteria) this;
        }

        public Criteria andBirthWeightLessThan(String value) {
            addCriterion("birth_weight <", value, "birthWeight");
            return (Criteria) this;
        }

        public Criteria andBirthWeightLessThanOrEqualTo(String value) {
            addCriterion("birth_weight <=", value, "birthWeight");
            return (Criteria) this;
        }

        public Criteria andBirthWeightLike(String value) {
            addCriterion("birth_weight like", value, "birthWeight");
            return (Criteria) this;
        }

        public Criteria andBirthWeightNotLike(String value) {
            addCriterion("birth_weight not like", value, "birthWeight");
            return (Criteria) this;
        }

        public Criteria andBirthWeightIn(List<String> values) {
            addCriterion("birth_weight in", values, "birthWeight");
            return (Criteria) this;
        }

        public Criteria andBirthWeightNotIn(List<String> values) {
            addCriterion("birth_weight not in", values, "birthWeight");
            return (Criteria) this;
        }

        public Criteria andBirthWeightBetween(String value1, String value2) {
            addCriterion("birth_weight between", value1, value2, "birthWeight");
            return (Criteria) this;
        }

        public Criteria andBirthWeightNotBetween(String value1, String value2) {
            addCriterion("birth_weight not between", value1, value2, "birthWeight");
            return (Criteria) this;
        }

        public Criteria andMontherMilkIsNull() {
            addCriterion("monther_milk is null");
            return (Criteria) this;
        }

        public Criteria andMontherMilkIsNotNull() {
            addCriterion("monther_milk is not null");
            return (Criteria) this;
        }

        public Criteria andMontherMilkEqualTo(String value) {
            addCriterion("monther_milk =", value, "montherMilk");
            return (Criteria) this;
        }

        public Criteria andMontherMilkNotEqualTo(String value) {
            addCriterion("monther_milk <>", value, "montherMilk");
            return (Criteria) this;
        }

        public Criteria andMontherMilkGreaterThan(String value) {
            addCriterion("monther_milk >", value, "montherMilk");
            return (Criteria) this;
        }

        public Criteria andMontherMilkGreaterThanOrEqualTo(String value) {
            addCriterion("monther_milk >=", value, "montherMilk");
            return (Criteria) this;
        }

        public Criteria andMontherMilkLessThan(String value) {
            addCriterion("monther_milk <", value, "montherMilk");
            return (Criteria) this;
        }

        public Criteria andMontherMilkLessThanOrEqualTo(String value) {
            addCriterion("monther_milk <=", value, "montherMilk");
            return (Criteria) this;
        }

        public Criteria andMontherMilkLike(String value) {
            addCriterion("monther_milk like", value, "montherMilk");
            return (Criteria) this;
        }

        public Criteria andMontherMilkNotLike(String value) {
            addCriterion("monther_milk not like", value, "montherMilk");
            return (Criteria) this;
        }

        public Criteria andMontherMilkIn(List<String> values) {
            addCriterion("monther_milk in", values, "montherMilk");
            return (Criteria) this;
        }

        public Criteria andMontherMilkNotIn(List<String> values) {
            addCriterion("monther_milk not in", values, "montherMilk");
            return (Criteria) this;
        }

        public Criteria andMontherMilkBetween(String value1, String value2) {
            addCriterion("monther_milk between", value1, value2, "montherMilk");
            return (Criteria) this;
        }

        public Criteria andMontherMilkNotBetween(String value1, String value2) {
            addCriterion("monther_milk not between", value1, value2, "montherMilk");
            return (Criteria) this;
        }

        public Criteria andManualMilkIsNull() {
            addCriterion("manual_milk is null");
            return (Criteria) this;
        }

        public Criteria andManualMilkIsNotNull() {
            addCriterion("manual_milk is not null");
            return (Criteria) this;
        }

        public Criteria andManualMilkEqualTo(String value) {
            addCriterion("manual_milk =", value, "manualMilk");
            return (Criteria) this;
        }

        public Criteria andManualMilkNotEqualTo(String value) {
            addCriterion("manual_milk <>", value, "manualMilk");
            return (Criteria) this;
        }

        public Criteria andManualMilkGreaterThan(String value) {
            addCriterion("manual_milk >", value, "manualMilk");
            return (Criteria) this;
        }

        public Criteria andManualMilkGreaterThanOrEqualTo(String value) {
            addCriterion("manual_milk >=", value, "manualMilk");
            return (Criteria) this;
        }

        public Criteria andManualMilkLessThan(String value) {
            addCriterion("manual_milk <", value, "manualMilk");
            return (Criteria) this;
        }

        public Criteria andManualMilkLessThanOrEqualTo(String value) {
            addCriterion("manual_milk <=", value, "manualMilk");
            return (Criteria) this;
        }

        public Criteria andManualMilkLike(String value) {
            addCriterion("manual_milk like", value, "manualMilk");
            return (Criteria) this;
        }

        public Criteria andManualMilkNotLike(String value) {
            addCriterion("manual_milk not like", value, "manualMilk");
            return (Criteria) this;
        }

        public Criteria andManualMilkIn(List<String> values) {
            addCriterion("manual_milk in", values, "manualMilk");
            return (Criteria) this;
        }

        public Criteria andManualMilkNotIn(List<String> values) {
            addCriterion("manual_milk not in", values, "manualMilk");
            return (Criteria) this;
        }

        public Criteria andManualMilkBetween(String value1, String value2) {
            addCriterion("manual_milk between", value1, value2, "manualMilk");
            return (Criteria) this;
        }

        public Criteria andManualMilkNotBetween(String value1, String value2) {
            addCriterion("manual_milk not between", value1, value2, "manualMilk");
            return (Criteria) this;
        }

        public Criteria andFeverConvulsionIsNull() {
            addCriterion("fever_convulsion is null");
            return (Criteria) this;
        }

        public Criteria andFeverConvulsionIsNotNull() {
            addCriterion("fever_convulsion is not null");
            return (Criteria) this;
        }

        public Criteria andFeverConvulsionEqualTo(String value) {
            addCriterion("fever_convulsion =", value, "feverConvulsion");
            return (Criteria) this;
        }

        public Criteria andFeverConvulsionNotEqualTo(String value) {
            addCriterion("fever_convulsion <>", value, "feverConvulsion");
            return (Criteria) this;
        }

        public Criteria andFeverConvulsionGreaterThan(String value) {
            addCriterion("fever_convulsion >", value, "feverConvulsion");
            return (Criteria) this;
        }

        public Criteria andFeverConvulsionGreaterThanOrEqualTo(String value) {
            addCriterion("fever_convulsion >=", value, "feverConvulsion");
            return (Criteria) this;
        }

        public Criteria andFeverConvulsionLessThan(String value) {
            addCriterion("fever_convulsion <", value, "feverConvulsion");
            return (Criteria) this;
        }

        public Criteria andFeverConvulsionLessThanOrEqualTo(String value) {
            addCriterion("fever_convulsion <=", value, "feverConvulsion");
            return (Criteria) this;
        }

        public Criteria andFeverConvulsionLike(String value) {
            addCriterion("fever_convulsion like", value, "feverConvulsion");
            return (Criteria) this;
        }

        public Criteria andFeverConvulsionNotLike(String value) {
            addCriterion("fever_convulsion not like", value, "feverConvulsion");
            return (Criteria) this;
        }

        public Criteria andFeverConvulsionIn(List<String> values) {
            addCriterion("fever_convulsion in", values, "feverConvulsion");
            return (Criteria) this;
        }

        public Criteria andFeverConvulsionNotIn(List<String> values) {
            addCriterion("fever_convulsion not in", values, "feverConvulsion");
            return (Criteria) this;
        }

        public Criteria andFeverConvulsionBetween(String value1, String value2) {
            addCriterion("fever_convulsion between", value1, value2, "feverConvulsion");
            return (Criteria) this;
        }

        public Criteria andFeverConvulsionNotBetween(String value1, String value2) {
            addCriterion("fever_convulsion not between", value1, value2, "feverConvulsion");
            return (Criteria) this;
        }

        public Criteria andRiseTimeIsNull() {
            addCriterion("rise_time is null");
            return (Criteria) this;
        }

        public Criteria andRiseTimeIsNotNull() {
            addCriterion("rise_time is not null");
            return (Criteria) this;
        }

        public Criteria andRiseTimeEqualTo(String value) {
            addCriterion("rise_time =", value, "riseTime");
            return (Criteria) this;
        }

        public Criteria andRiseTimeNotEqualTo(String value) {
            addCriterion("rise_time <>", value, "riseTime");
            return (Criteria) this;
        }

        public Criteria andRiseTimeGreaterThan(String value) {
            addCriterion("rise_time >", value, "riseTime");
            return (Criteria) this;
        }

        public Criteria andRiseTimeGreaterThanOrEqualTo(String value) {
            addCriterion("rise_time >=", value, "riseTime");
            return (Criteria) this;
        }

        public Criteria andRiseTimeLessThan(String value) {
            addCriterion("rise_time <", value, "riseTime");
            return (Criteria) this;
        }

        public Criteria andRiseTimeLessThanOrEqualTo(String value) {
            addCriterion("rise_time <=", value, "riseTime");
            return (Criteria) this;
        }

        public Criteria andRiseTimeLike(String value) {
            addCriterion("rise_time like", value, "riseTime");
            return (Criteria) this;
        }

        public Criteria andRiseTimeNotLike(String value) {
            addCriterion("rise_time not like", value, "riseTime");
            return (Criteria) this;
        }

        public Criteria andRiseTimeIn(List<String> values) {
            addCriterion("rise_time in", values, "riseTime");
            return (Criteria) this;
        }

        public Criteria andRiseTimeNotIn(List<String> values) {
            addCriterion("rise_time not in", values, "riseTime");
            return (Criteria) this;
        }

        public Criteria andRiseTimeBetween(String value1, String value2) {
            addCriterion("rise_time between", value1, value2, "riseTime");
            return (Criteria) this;
        }

        public Criteria andRiseTimeNotBetween(String value1, String value2) {
            addCriterion("rise_time not between", value1, value2, "riseTime");
            return (Criteria) this;
        }

        public Criteria andTurnoverTimeIsNull() {
            addCriterion("turnover_time is null");
            return (Criteria) this;
        }

        public Criteria andTurnoverTimeIsNotNull() {
            addCriterion("turnover_time is not null");
            return (Criteria) this;
        }

        public Criteria andTurnoverTimeEqualTo(String value) {
            addCriterion("turnover_time =", value, "turnoverTime");
            return (Criteria) this;
        }

        public Criteria andTurnoverTimeNotEqualTo(String value) {
            addCriterion("turnover_time <>", value, "turnoverTime");
            return (Criteria) this;
        }

        public Criteria andTurnoverTimeGreaterThan(String value) {
            addCriterion("turnover_time >", value, "turnoverTime");
            return (Criteria) this;
        }

        public Criteria andTurnoverTimeGreaterThanOrEqualTo(String value) {
            addCriterion("turnover_time >=", value, "turnoverTime");
            return (Criteria) this;
        }

        public Criteria andTurnoverTimeLessThan(String value) {
            addCriterion("turnover_time <", value, "turnoverTime");
            return (Criteria) this;
        }

        public Criteria andTurnoverTimeLessThanOrEqualTo(String value) {
            addCriterion("turnover_time <=", value, "turnoverTime");
            return (Criteria) this;
        }

        public Criteria andTurnoverTimeLike(String value) {
            addCriterion("turnover_time like", value, "turnoverTime");
            return (Criteria) this;
        }

        public Criteria andTurnoverTimeNotLike(String value) {
            addCriterion("turnover_time not like", value, "turnoverTime");
            return (Criteria) this;
        }

        public Criteria andTurnoverTimeIn(List<String> values) {
            addCriterion("turnover_time in", values, "turnoverTime");
            return (Criteria) this;
        }

        public Criteria andTurnoverTimeNotIn(List<String> values) {
            addCriterion("turnover_time not in", values, "turnoverTime");
            return (Criteria) this;
        }

        public Criteria andTurnoverTimeBetween(String value1, String value2) {
            addCriterion("turnover_time between", value1, value2, "turnoverTime");
            return (Criteria) this;
        }

        public Criteria andTurnoverTimeNotBetween(String value1, String value2) {
            addCriterion("turnover_time not between", value1, value2, "turnoverTime");
            return (Criteria) this;
        }

        public Criteria andCreepTimeIsNull() {
            addCriterion("creep_time is null");
            return (Criteria) this;
        }

        public Criteria andCreepTimeIsNotNull() {
            addCriterion("creep_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreepTimeEqualTo(String value) {
            addCriterion("creep_time =", value, "creepTime");
            return (Criteria) this;
        }

        public Criteria andCreepTimeNotEqualTo(String value) {
            addCriterion("creep_time <>", value, "creepTime");
            return (Criteria) this;
        }

        public Criteria andCreepTimeGreaterThan(String value) {
            addCriterion("creep_time >", value, "creepTime");
            return (Criteria) this;
        }

        public Criteria andCreepTimeGreaterThanOrEqualTo(String value) {
            addCriterion("creep_time >=", value, "creepTime");
            return (Criteria) this;
        }

        public Criteria andCreepTimeLessThan(String value) {
            addCriterion("creep_time <", value, "creepTime");
            return (Criteria) this;
        }

        public Criteria andCreepTimeLessThanOrEqualTo(String value) {
            addCriterion("creep_time <=", value, "creepTime");
            return (Criteria) this;
        }

        public Criteria andCreepTimeLike(String value) {
            addCriterion("creep_time like", value, "creepTime");
            return (Criteria) this;
        }

        public Criteria andCreepTimeNotLike(String value) {
            addCriterion("creep_time not like", value, "creepTime");
            return (Criteria) this;
        }

        public Criteria andCreepTimeIn(List<String> values) {
            addCriterion("creep_time in", values, "creepTime");
            return (Criteria) this;
        }

        public Criteria andCreepTimeNotIn(List<String> values) {
            addCriterion("creep_time not in", values, "creepTime");
            return (Criteria) this;
        }

        public Criteria andCreepTimeBetween(String value1, String value2) {
            addCriterion("creep_time between", value1, value2, "creepTime");
            return (Criteria) this;
        }

        public Criteria andCreepTimeNotBetween(String value1, String value2) {
            addCriterion("creep_time not between", value1, value2, "creepTime");
            return (Criteria) this;
        }

        public Criteria andSmileTimeIsNull() {
            addCriterion("smile_time is null");
            return (Criteria) this;
        }

        public Criteria andSmileTimeIsNotNull() {
            addCriterion("smile_time is not null");
            return (Criteria) this;
        }

        public Criteria andSmileTimeEqualTo(String value) {
            addCriterion("smile_time =", value, "smileTime");
            return (Criteria) this;
        }

        public Criteria andSmileTimeNotEqualTo(String value) {
            addCriterion("smile_time <>", value, "smileTime");
            return (Criteria) this;
        }

        public Criteria andSmileTimeGreaterThan(String value) {
            addCriterion("smile_time >", value, "smileTime");
            return (Criteria) this;
        }

        public Criteria andSmileTimeGreaterThanOrEqualTo(String value) {
            addCriterion("smile_time >=", value, "smileTime");
            return (Criteria) this;
        }

        public Criteria andSmileTimeLessThan(String value) {
            addCriterion("smile_time <", value, "smileTime");
            return (Criteria) this;
        }

        public Criteria andSmileTimeLessThanOrEqualTo(String value) {
            addCriterion("smile_time <=", value, "smileTime");
            return (Criteria) this;
        }

        public Criteria andSmileTimeLike(String value) {
            addCriterion("smile_time like", value, "smileTime");
            return (Criteria) this;
        }

        public Criteria andSmileTimeNotLike(String value) {
            addCriterion("smile_time not like", value, "smileTime");
            return (Criteria) this;
        }

        public Criteria andSmileTimeIn(List<String> values) {
            addCriterion("smile_time in", values, "smileTime");
            return (Criteria) this;
        }

        public Criteria andSmileTimeNotIn(List<String> values) {
            addCriterion("smile_time not in", values, "smileTime");
            return (Criteria) this;
        }

        public Criteria andSmileTimeBetween(String value1, String value2) {
            addCriterion("smile_time between", value1, value2, "smileTime");
            return (Criteria) this;
        }

        public Criteria andSmileTimeNotBetween(String value1, String value2) {
            addCriterion("smile_time not between", value1, value2, "smileTime");
            return (Criteria) this;
        }

        public Criteria andSitTimeIsNull() {
            addCriterion("sit_time is null");
            return (Criteria) this;
        }

        public Criteria andSitTimeIsNotNull() {
            addCriterion("sit_time is not null");
            return (Criteria) this;
        }

        public Criteria andSitTimeEqualTo(String value) {
            addCriterion("sit_time =", value, "sitTime");
            return (Criteria) this;
        }

        public Criteria andSitTimeNotEqualTo(String value) {
            addCriterion("sit_time <>", value, "sitTime");
            return (Criteria) this;
        }

        public Criteria andSitTimeGreaterThan(String value) {
            addCriterion("sit_time >", value, "sitTime");
            return (Criteria) this;
        }

        public Criteria andSitTimeGreaterThanOrEqualTo(String value) {
            addCriterion("sit_time >=", value, "sitTime");
            return (Criteria) this;
        }

        public Criteria andSitTimeLessThan(String value) {
            addCriterion("sit_time <", value, "sitTime");
            return (Criteria) this;
        }

        public Criteria andSitTimeLessThanOrEqualTo(String value) {
            addCriterion("sit_time <=", value, "sitTime");
            return (Criteria) this;
        }

        public Criteria andSitTimeLike(String value) {
            addCriterion("sit_time like", value, "sitTime");
            return (Criteria) this;
        }

        public Criteria andSitTimeNotLike(String value) {
            addCriterion("sit_time not like", value, "sitTime");
            return (Criteria) this;
        }

        public Criteria andSitTimeIn(List<String> values) {
            addCriterion("sit_time in", values, "sitTime");
            return (Criteria) this;
        }

        public Criteria andSitTimeNotIn(List<String> values) {
            addCriterion("sit_time not in", values, "sitTime");
            return (Criteria) this;
        }

        public Criteria andSitTimeBetween(String value1, String value2) {
            addCriterion("sit_time between", value1, value2, "sitTime");
            return (Criteria) this;
        }

        public Criteria andSitTimeNotBetween(String value1, String value2) {
            addCriterion("sit_time not between", value1, value2, "sitTime");
            return (Criteria) this;
        }

        public Criteria andWalkTimeIsNull() {
            addCriterion("walk_time is null");
            return (Criteria) this;
        }

        public Criteria andWalkTimeIsNotNull() {
            addCriterion("walk_time is not null");
            return (Criteria) this;
        }

        public Criteria andWalkTimeEqualTo(String value) {
            addCriterion("walk_time =", value, "walkTime");
            return (Criteria) this;
        }

        public Criteria andWalkTimeNotEqualTo(String value) {
            addCriterion("walk_time <>", value, "walkTime");
            return (Criteria) this;
        }

        public Criteria andWalkTimeGreaterThan(String value) {
            addCriterion("walk_time >", value, "walkTime");
            return (Criteria) this;
        }

        public Criteria andWalkTimeGreaterThanOrEqualTo(String value) {
            addCriterion("walk_time >=", value, "walkTime");
            return (Criteria) this;
        }

        public Criteria andWalkTimeLessThan(String value) {
            addCriterion("walk_time <", value, "walkTime");
            return (Criteria) this;
        }

        public Criteria andWalkTimeLessThanOrEqualTo(String value) {
            addCriterion("walk_time <=", value, "walkTime");
            return (Criteria) this;
        }

        public Criteria andWalkTimeLike(String value) {
            addCriterion("walk_time like", value, "walkTime");
            return (Criteria) this;
        }

        public Criteria andWalkTimeNotLike(String value) {
            addCriterion("walk_time not like", value, "walkTime");
            return (Criteria) this;
        }

        public Criteria andWalkTimeIn(List<String> values) {
            addCriterion("walk_time in", values, "walkTime");
            return (Criteria) this;
        }

        public Criteria andWalkTimeNotIn(List<String> values) {
            addCriterion("walk_time not in", values, "walkTime");
            return (Criteria) this;
        }

        public Criteria andWalkTimeBetween(String value1, String value2) {
            addCriterion("walk_time between", value1, value2, "walkTime");
            return (Criteria) this;
        }

        public Criteria andWalkTimeNotBetween(String value1, String value2) {
            addCriterion("walk_time not between", value1, value2, "walkTime");
            return (Criteria) this;
        }

        public Criteria andVoiceTimeIsNull() {
            addCriterion("voice_time is null");
            return (Criteria) this;
        }

        public Criteria andVoiceTimeIsNotNull() {
            addCriterion("voice_time is not null");
            return (Criteria) this;
        }

        public Criteria andVoiceTimeEqualTo(String value) {
            addCriterion("voice_time =", value, "voiceTime");
            return (Criteria) this;
        }

        public Criteria andVoiceTimeNotEqualTo(String value) {
            addCriterion("voice_time <>", value, "voiceTime");
            return (Criteria) this;
        }

        public Criteria andVoiceTimeGreaterThan(String value) {
            addCriterion("voice_time >", value, "voiceTime");
            return (Criteria) this;
        }

        public Criteria andVoiceTimeGreaterThanOrEqualTo(String value) {
            addCriterion("voice_time >=", value, "voiceTime");
            return (Criteria) this;
        }

        public Criteria andVoiceTimeLessThan(String value) {
            addCriterion("voice_time <", value, "voiceTime");
            return (Criteria) this;
        }

        public Criteria andVoiceTimeLessThanOrEqualTo(String value) {
            addCriterion("voice_time <=", value, "voiceTime");
            return (Criteria) this;
        }

        public Criteria andVoiceTimeLike(String value) {
            addCriterion("voice_time like", value, "voiceTime");
            return (Criteria) this;
        }

        public Criteria andVoiceTimeNotLike(String value) {
            addCriterion("voice_time not like", value, "voiceTime");
            return (Criteria) this;
        }

        public Criteria andVoiceTimeIn(List<String> values) {
            addCriterion("voice_time in", values, "voiceTime");
            return (Criteria) this;
        }

        public Criteria andVoiceTimeNotIn(List<String> values) {
            addCriterion("voice_time not in", values, "voiceTime");
            return (Criteria) this;
        }

        public Criteria andVoiceTimeBetween(String value1, String value2) {
            addCriterion("voice_time between", value1, value2, "voiceTime");
            return (Criteria) this;
        }

        public Criteria andVoiceTimeNotBetween(String value1, String value2) {
            addCriterion("voice_time not between", value1, value2, "voiceTime");
            return (Criteria) this;
        }

        public Criteria andWordTimeIsNull() {
            addCriterion("word_time is null");
            return (Criteria) this;
        }

        public Criteria andWordTimeIsNotNull() {
            addCriterion("word_time is not null");
            return (Criteria) this;
        }

        public Criteria andWordTimeEqualTo(String value) {
            addCriterion("word_time =", value, "wordTime");
            return (Criteria) this;
        }

        public Criteria andWordTimeNotEqualTo(String value) {
            addCriterion("word_time <>", value, "wordTime");
            return (Criteria) this;
        }

        public Criteria andWordTimeGreaterThan(String value) {
            addCriterion("word_time >", value, "wordTime");
            return (Criteria) this;
        }

        public Criteria andWordTimeGreaterThanOrEqualTo(String value) {
            addCriterion("word_time >=", value, "wordTime");
            return (Criteria) this;
        }

        public Criteria andWordTimeLessThan(String value) {
            addCriterion("word_time <", value, "wordTime");
            return (Criteria) this;
        }

        public Criteria andWordTimeLessThanOrEqualTo(String value) {
            addCriterion("word_time <=", value, "wordTime");
            return (Criteria) this;
        }

        public Criteria andWordTimeLike(String value) {
            addCriterion("word_time like", value, "wordTime");
            return (Criteria) this;
        }

        public Criteria andWordTimeNotLike(String value) {
            addCriterion("word_time not like", value, "wordTime");
            return (Criteria) this;
        }

        public Criteria andWordTimeIn(List<String> values) {
            addCriterion("word_time in", values, "wordTime");
            return (Criteria) this;
        }

        public Criteria andWordTimeNotIn(List<String> values) {
            addCriterion("word_time not in", values, "wordTime");
            return (Criteria) this;
        }

        public Criteria andWordTimeBetween(String value1, String value2) {
            addCriterion("word_time between", value1, value2, "wordTime");
            return (Criteria) this;
        }

        public Criteria andWordTimeNotBetween(String value1, String value2) {
            addCriterion("word_time not between", value1, value2, "wordTime");
            return (Criteria) this;
        }

        public Criteria andMultiwordTimeIsNull() {
            addCriterion("multiword_time is null");
            return (Criteria) this;
        }

        public Criteria andMultiwordTimeIsNotNull() {
            addCriterion("multiword_time is not null");
            return (Criteria) this;
        }

        public Criteria andMultiwordTimeEqualTo(String value) {
            addCriterion("multiword_time =", value, "multiwordTime");
            return (Criteria) this;
        }

        public Criteria andMultiwordTimeNotEqualTo(String value) {
            addCriterion("multiword_time <>", value, "multiwordTime");
            return (Criteria) this;
        }

        public Criteria andMultiwordTimeGreaterThan(String value) {
            addCriterion("multiword_time >", value, "multiwordTime");
            return (Criteria) this;
        }

        public Criteria andMultiwordTimeGreaterThanOrEqualTo(String value) {
            addCriterion("multiword_time >=", value, "multiwordTime");
            return (Criteria) this;
        }

        public Criteria andMultiwordTimeLessThan(String value) {
            addCriterion("multiword_time <", value, "multiwordTime");
            return (Criteria) this;
        }

        public Criteria andMultiwordTimeLessThanOrEqualTo(String value) {
            addCriterion("multiword_time <=", value, "multiwordTime");
            return (Criteria) this;
        }

        public Criteria andMultiwordTimeLike(String value) {
            addCriterion("multiword_time like", value, "multiwordTime");
            return (Criteria) this;
        }

        public Criteria andMultiwordTimeNotLike(String value) {
            addCriterion("multiword_time not like", value, "multiwordTime");
            return (Criteria) this;
        }

        public Criteria andMultiwordTimeIn(List<String> values) {
            addCriterion("multiword_time in", values, "multiwordTime");
            return (Criteria) this;
        }

        public Criteria andMultiwordTimeNotIn(List<String> values) {
            addCriterion("multiword_time not in", values, "multiwordTime");
            return (Criteria) this;
        }

        public Criteria andMultiwordTimeBetween(String value1, String value2) {
            addCriterion("multiword_time between", value1, value2, "multiwordTime");
            return (Criteria) this;
        }

        public Criteria andMultiwordTimeNotBetween(String value1, String value2) {
            addCriterion("multiword_time not between", value1, value2, "multiwordTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_self_info
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 26 23:48:23 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_self_info
     *
     * @mbggenerated Fri Jul 26 23:48:23 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}