package com.xingyu.domain.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SdYearSummaryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    public SdYearSummaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andArchiveNoIsNull() {
            addCriterion("archive_no is null");
            return (Criteria) this;
        }

        public Criteria andArchiveNoIsNotNull() {
            addCriterion("archive_no is not null");
            return (Criteria) this;
        }

        public Criteria andArchiveNoEqualTo(String value) {
            addCriterion("archive_no =", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotEqualTo(String value) {
            addCriterion("archive_no <>", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoGreaterThan(String value) {
            addCriterion("archive_no >", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoGreaterThanOrEqualTo(String value) {
            addCriterion("archive_no >=", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoLessThan(String value) {
            addCriterion("archive_no <", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoLessThanOrEqualTo(String value) {
            addCriterion("archive_no <=", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoLike(String value) {
            addCriterion("archive_no like", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotLike(String value) {
            addCriterion("archive_no not like", value, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoIn(List<String> values) {
            addCriterion("archive_no in", values, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotIn(List<String> values) {
            addCriterion("archive_no not in", values, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoBetween(String value1, String value2) {
            addCriterion("archive_no between", value1, value2, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andArchiveNoNotBetween(String value1, String value2) {
            addCriterion("archive_no not between", value1, value2, "archiveNo");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(String value) {
            addCriterion("year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(String value) {
            addCriterion("year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(String value) {
            addCriterion("year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(String value) {
            addCriterion("year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(String value) {
            addCriterion("year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(String value) {
            addCriterion("year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLike(String value) {
            addCriterion("year like", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotLike(String value) {
            addCriterion("year not like", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<String> values) {
            addCriterion("year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<String> values) {
            addCriterion("year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(String value1, String value2) {
            addCriterion("year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(String value1, String value2) {
            addCriterion("year not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherIsNull() {
            addCriterion("train_teacher is null");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherIsNotNull() {
            addCriterion("train_teacher is not null");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherEqualTo(String value) {
            addCriterion("train_teacher =", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherNotEqualTo(String value) {
            addCriterion("train_teacher <>", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherGreaterThan(String value) {
            addCriterion("train_teacher >", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherGreaterThanOrEqualTo(String value) {
            addCriterion("train_teacher >=", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherLessThan(String value) {
            addCriterion("train_teacher <", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherLessThanOrEqualTo(String value) {
            addCriterion("train_teacher <=", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherLike(String value) {
            addCriterion("train_teacher like", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherNotLike(String value) {
            addCriterion("train_teacher not like", value, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherIn(List<String> values) {
            addCriterion("train_teacher in", values, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherNotIn(List<String> values) {
            addCriterion("train_teacher not in", values, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherBetween(String value1, String value2) {
            addCriterion("train_teacher between", value1, value2, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andTrainTeacherNotBetween(String value1, String value2) {
            addCriterion("train_teacher not between", value1, value2, "trainTeacher");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterionForJDBCDate("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterionForJDBCDate("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterionForJDBCDate("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterionForJDBCDate("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterionForJDBCDate("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterionForJDBCDate("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andItem1IsNull() {
            addCriterion("item_1 is null");
            return (Criteria) this;
        }

        public Criteria andItem1IsNotNull() {
            addCriterion("item_1 is not null");
            return (Criteria) this;
        }

        public Criteria andItem1EqualTo(String value) {
            addCriterion("item_1 =", value, "item1");
            return (Criteria) this;
        }

        public Criteria andItem1NotEqualTo(String value) {
            addCriterion("item_1 <>", value, "item1");
            return (Criteria) this;
        }

        public Criteria andItem1GreaterThan(String value) {
            addCriterion("item_1 >", value, "item1");
            return (Criteria) this;
        }

        public Criteria andItem1GreaterThanOrEqualTo(String value) {
            addCriterion("item_1 >=", value, "item1");
            return (Criteria) this;
        }

        public Criteria andItem1LessThan(String value) {
            addCriterion("item_1 <", value, "item1");
            return (Criteria) this;
        }

        public Criteria andItem1LessThanOrEqualTo(String value) {
            addCriterion("item_1 <=", value, "item1");
            return (Criteria) this;
        }

        public Criteria andItem1Like(String value) {
            addCriterion("item_1 like", value, "item1");
            return (Criteria) this;
        }

        public Criteria andItem1NotLike(String value) {
            addCriterion("item_1 not like", value, "item1");
            return (Criteria) this;
        }

        public Criteria andItem1In(List<String> values) {
            addCriterion("item_1 in", values, "item1");
            return (Criteria) this;
        }

        public Criteria andItem1NotIn(List<String> values) {
            addCriterion("item_1 not in", values, "item1");
            return (Criteria) this;
        }

        public Criteria andItem1Between(String value1, String value2) {
            addCriterion("item_1 between", value1, value2, "item1");
            return (Criteria) this;
        }

        public Criteria andItem1NotBetween(String value1, String value2) {
            addCriterion("item_1 not between", value1, value2, "item1");
            return (Criteria) this;
        }

        public Criteria andItem2IsNull() {
            addCriterion("item_2 is null");
            return (Criteria) this;
        }

        public Criteria andItem2IsNotNull() {
            addCriterion("item_2 is not null");
            return (Criteria) this;
        }

        public Criteria andItem2EqualTo(String value) {
            addCriterion("item_2 =", value, "item2");
            return (Criteria) this;
        }

        public Criteria andItem2NotEqualTo(String value) {
            addCriterion("item_2 <>", value, "item2");
            return (Criteria) this;
        }

        public Criteria andItem2GreaterThan(String value) {
            addCriterion("item_2 >", value, "item2");
            return (Criteria) this;
        }

        public Criteria andItem2GreaterThanOrEqualTo(String value) {
            addCriterion("item_2 >=", value, "item2");
            return (Criteria) this;
        }

        public Criteria andItem2LessThan(String value) {
            addCriterion("item_2 <", value, "item2");
            return (Criteria) this;
        }

        public Criteria andItem2LessThanOrEqualTo(String value) {
            addCriterion("item_2 <=", value, "item2");
            return (Criteria) this;
        }

        public Criteria andItem2Like(String value) {
            addCriterion("item_2 like", value, "item2");
            return (Criteria) this;
        }

        public Criteria andItem2NotLike(String value) {
            addCriterion("item_2 not like", value, "item2");
            return (Criteria) this;
        }

        public Criteria andItem2In(List<String> values) {
            addCriterion("item_2 in", values, "item2");
            return (Criteria) this;
        }

        public Criteria andItem2NotIn(List<String> values) {
            addCriterion("item_2 not in", values, "item2");
            return (Criteria) this;
        }

        public Criteria andItem2Between(String value1, String value2) {
            addCriterion("item_2 between", value1, value2, "item2");
            return (Criteria) this;
        }

        public Criteria andItem2NotBetween(String value1, String value2) {
            addCriterion("item_2 not between", value1, value2, "item2");
            return (Criteria) this;
        }

        public Criteria andItem3IsNull() {
            addCriterion("item_3 is null");
            return (Criteria) this;
        }

        public Criteria andItem3IsNotNull() {
            addCriterion("item_3 is not null");
            return (Criteria) this;
        }

        public Criteria andItem3EqualTo(String value) {
            addCriterion("item_3 =", value, "item3");
            return (Criteria) this;
        }

        public Criteria andItem3NotEqualTo(String value) {
            addCriterion("item_3 <>", value, "item3");
            return (Criteria) this;
        }

        public Criteria andItem3GreaterThan(String value) {
            addCriterion("item_3 >", value, "item3");
            return (Criteria) this;
        }

        public Criteria andItem3GreaterThanOrEqualTo(String value) {
            addCriterion("item_3 >=", value, "item3");
            return (Criteria) this;
        }

        public Criteria andItem3LessThan(String value) {
            addCriterion("item_3 <", value, "item3");
            return (Criteria) this;
        }

        public Criteria andItem3LessThanOrEqualTo(String value) {
            addCriterion("item_3 <=", value, "item3");
            return (Criteria) this;
        }

        public Criteria andItem3Like(String value) {
            addCriterion("item_3 like", value, "item3");
            return (Criteria) this;
        }

        public Criteria andItem3NotLike(String value) {
            addCriterion("item_3 not like", value, "item3");
            return (Criteria) this;
        }

        public Criteria andItem3In(List<String> values) {
            addCriterion("item_3 in", values, "item3");
            return (Criteria) this;
        }

        public Criteria andItem3NotIn(List<String> values) {
            addCriterion("item_3 not in", values, "item3");
            return (Criteria) this;
        }

        public Criteria andItem3Between(String value1, String value2) {
            addCriterion("item_3 between", value1, value2, "item3");
            return (Criteria) this;
        }

        public Criteria andItem3NotBetween(String value1, String value2) {
            addCriterion("item_3 not between", value1, value2, "item3");
            return (Criteria) this;
        }

        public Criteria andItem4IsNull() {
            addCriterion("item_4 is null");
            return (Criteria) this;
        }

        public Criteria andItem4IsNotNull() {
            addCriterion("item_4 is not null");
            return (Criteria) this;
        }

        public Criteria andItem4EqualTo(String value) {
            addCriterion("item_4 =", value, "item4");
            return (Criteria) this;
        }

        public Criteria andItem4NotEqualTo(String value) {
            addCriterion("item_4 <>", value, "item4");
            return (Criteria) this;
        }

        public Criteria andItem4GreaterThan(String value) {
            addCriterion("item_4 >", value, "item4");
            return (Criteria) this;
        }

        public Criteria andItem4GreaterThanOrEqualTo(String value) {
            addCriterion("item_4 >=", value, "item4");
            return (Criteria) this;
        }

        public Criteria andItem4LessThan(String value) {
            addCriterion("item_4 <", value, "item4");
            return (Criteria) this;
        }

        public Criteria andItem4LessThanOrEqualTo(String value) {
            addCriterion("item_4 <=", value, "item4");
            return (Criteria) this;
        }

        public Criteria andItem4Like(String value) {
            addCriterion("item_4 like", value, "item4");
            return (Criteria) this;
        }

        public Criteria andItem4NotLike(String value) {
            addCriterion("item_4 not like", value, "item4");
            return (Criteria) this;
        }

        public Criteria andItem4In(List<String> values) {
            addCriterion("item_4 in", values, "item4");
            return (Criteria) this;
        }

        public Criteria andItem4NotIn(List<String> values) {
            addCriterion("item_4 not in", values, "item4");
            return (Criteria) this;
        }

        public Criteria andItem4Between(String value1, String value2) {
            addCriterion("item_4 between", value1, value2, "item4");
            return (Criteria) this;
        }

        public Criteria andItem4NotBetween(String value1, String value2) {
            addCriterion("item_4 not between", value1, value2, "item4");
            return (Criteria) this;
        }

        public Criteria andItem5IsNull() {
            addCriterion("item_5 is null");
            return (Criteria) this;
        }

        public Criteria andItem5IsNotNull() {
            addCriterion("item_5 is not null");
            return (Criteria) this;
        }

        public Criteria andItem5EqualTo(String value) {
            addCriterion("item_5 =", value, "item5");
            return (Criteria) this;
        }

        public Criteria andItem5NotEqualTo(String value) {
            addCriterion("item_5 <>", value, "item5");
            return (Criteria) this;
        }

        public Criteria andItem5GreaterThan(String value) {
            addCriterion("item_5 >", value, "item5");
            return (Criteria) this;
        }

        public Criteria andItem5GreaterThanOrEqualTo(String value) {
            addCriterion("item_5 >=", value, "item5");
            return (Criteria) this;
        }

        public Criteria andItem5LessThan(String value) {
            addCriterion("item_5 <", value, "item5");
            return (Criteria) this;
        }

        public Criteria andItem5LessThanOrEqualTo(String value) {
            addCriterion("item_5 <=", value, "item5");
            return (Criteria) this;
        }

        public Criteria andItem5Like(String value) {
            addCriterion("item_5 like", value, "item5");
            return (Criteria) this;
        }

        public Criteria andItem5NotLike(String value) {
            addCriterion("item_5 not like", value, "item5");
            return (Criteria) this;
        }

        public Criteria andItem5In(List<String> values) {
            addCriterion("item_5 in", values, "item5");
            return (Criteria) this;
        }

        public Criteria andItem5NotIn(List<String> values) {
            addCriterion("item_5 not in", values, "item5");
            return (Criteria) this;
        }

        public Criteria andItem5Between(String value1, String value2) {
            addCriterion("item_5 between", value1, value2, "item5");
            return (Criteria) this;
        }

        public Criteria andItem5NotBetween(String value1, String value2) {
            addCriterion("item_5 not between", value1, value2, "item5");
            return (Criteria) this;
        }

        public Criteria andItem6IsNull() {
            addCriterion("item_6 is null");
            return (Criteria) this;
        }

        public Criteria andItem6IsNotNull() {
            addCriterion("item_6 is not null");
            return (Criteria) this;
        }

        public Criteria andItem6EqualTo(String value) {
            addCriterion("item_6 =", value, "item6");
            return (Criteria) this;
        }

        public Criteria andItem6NotEqualTo(String value) {
            addCriterion("item_6 <>", value, "item6");
            return (Criteria) this;
        }

        public Criteria andItem6GreaterThan(String value) {
            addCriterion("item_6 >", value, "item6");
            return (Criteria) this;
        }

        public Criteria andItem6GreaterThanOrEqualTo(String value) {
            addCriterion("item_6 >=", value, "item6");
            return (Criteria) this;
        }

        public Criteria andItem6LessThan(String value) {
            addCriterion("item_6 <", value, "item6");
            return (Criteria) this;
        }

        public Criteria andItem6LessThanOrEqualTo(String value) {
            addCriterion("item_6 <=", value, "item6");
            return (Criteria) this;
        }

        public Criteria andItem6Like(String value) {
            addCriterion("item_6 like", value, "item6");
            return (Criteria) this;
        }

        public Criteria andItem6NotLike(String value) {
            addCriterion("item_6 not like", value, "item6");
            return (Criteria) this;
        }

        public Criteria andItem6In(List<String> values) {
            addCriterion("item_6 in", values, "item6");
            return (Criteria) this;
        }

        public Criteria andItem6NotIn(List<String> values) {
            addCriterion("item_6 not in", values, "item6");
            return (Criteria) this;
        }

        public Criteria andItem6Between(String value1, String value2) {
            addCriterion("item_6 between", value1, value2, "item6");
            return (Criteria) this;
        }

        public Criteria andItem6NotBetween(String value1, String value2) {
            addCriterion("item_6 not between", value1, value2, "item6");
            return (Criteria) this;
        }

        public Criteria andItem7IsNull() {
            addCriterion("item_7 is null");
            return (Criteria) this;
        }

        public Criteria andItem7IsNotNull() {
            addCriterion("item_7 is not null");
            return (Criteria) this;
        }

        public Criteria andItem7EqualTo(String value) {
            addCriterion("item_7 =", value, "item7");
            return (Criteria) this;
        }

        public Criteria andItem7NotEqualTo(String value) {
            addCriterion("item_7 <>", value, "item7");
            return (Criteria) this;
        }

        public Criteria andItem7GreaterThan(String value) {
            addCriterion("item_7 >", value, "item7");
            return (Criteria) this;
        }

        public Criteria andItem7GreaterThanOrEqualTo(String value) {
            addCriterion("item_7 >=", value, "item7");
            return (Criteria) this;
        }

        public Criteria andItem7LessThan(String value) {
            addCriterion("item_7 <", value, "item7");
            return (Criteria) this;
        }

        public Criteria andItem7LessThanOrEqualTo(String value) {
            addCriterion("item_7 <=", value, "item7");
            return (Criteria) this;
        }

        public Criteria andItem7Like(String value) {
            addCriterion("item_7 like", value, "item7");
            return (Criteria) this;
        }

        public Criteria andItem7NotLike(String value) {
            addCriterion("item_7 not like", value, "item7");
            return (Criteria) this;
        }

        public Criteria andItem7In(List<String> values) {
            addCriterion("item_7 in", values, "item7");
            return (Criteria) this;
        }

        public Criteria andItem7NotIn(List<String> values) {
            addCriterion("item_7 not in", values, "item7");
            return (Criteria) this;
        }

        public Criteria andItem7Between(String value1, String value2) {
            addCriterion("item_7 between", value1, value2, "item7");
            return (Criteria) this;
        }

        public Criteria andItem7NotBetween(String value1, String value2) {
            addCriterion("item_7 not between", value1, value2, "item7");
            return (Criteria) this;
        }

        public Criteria andItem8IsNull() {
            addCriterion("item_8 is null");
            return (Criteria) this;
        }

        public Criteria andItem8IsNotNull() {
            addCriterion("item_8 is not null");
            return (Criteria) this;
        }

        public Criteria andItem8EqualTo(String value) {
            addCriterion("item_8 =", value, "item8");
            return (Criteria) this;
        }

        public Criteria andItem8NotEqualTo(String value) {
            addCriterion("item_8 <>", value, "item8");
            return (Criteria) this;
        }

        public Criteria andItem8GreaterThan(String value) {
            addCriterion("item_8 >", value, "item8");
            return (Criteria) this;
        }

        public Criteria andItem8GreaterThanOrEqualTo(String value) {
            addCriterion("item_8 >=", value, "item8");
            return (Criteria) this;
        }

        public Criteria andItem8LessThan(String value) {
            addCriterion("item_8 <", value, "item8");
            return (Criteria) this;
        }

        public Criteria andItem8LessThanOrEqualTo(String value) {
            addCriterion("item_8 <=", value, "item8");
            return (Criteria) this;
        }

        public Criteria andItem8Like(String value) {
            addCriterion("item_8 like", value, "item8");
            return (Criteria) this;
        }

        public Criteria andItem8NotLike(String value) {
            addCriterion("item_8 not like", value, "item8");
            return (Criteria) this;
        }

        public Criteria andItem8In(List<String> values) {
            addCriterion("item_8 in", values, "item8");
            return (Criteria) this;
        }

        public Criteria andItem8NotIn(List<String> values) {
            addCriterion("item_8 not in", values, "item8");
            return (Criteria) this;
        }

        public Criteria andItem8Between(String value1, String value2) {
            addCriterion("item_8 between", value1, value2, "item8");
            return (Criteria) this;
        }

        public Criteria andItem8NotBetween(String value1, String value2) {
            addCriterion("item_8 not between", value1, value2, "item8");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNull() {
            addCriterion("summary is null");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNotNull() {
            addCriterion("summary is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryEqualTo(String value) {
            addCriterion("summary =", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotEqualTo(String value) {
            addCriterion("summary <>", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThan(String value) {
            addCriterion("summary >", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("summary >=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThan(String value) {
            addCriterion("summary <", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThanOrEqualTo(String value) {
            addCriterion("summary <=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLike(String value) {
            addCriterion("summary like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotLike(String value) {
            addCriterion("summary not like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryIn(List<String> values) {
            addCriterion("summary in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotIn(List<String> values) {
            addCriterion("summary not in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryBetween(String value1, String value2) {
            addCriterion("summary between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotBetween(String value1, String value2) {
            addCriterion("summary not between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andScoreImproveIsNull() {
            addCriterion("score_improve is null");
            return (Criteria) this;
        }

        public Criteria andScoreImproveIsNotNull() {
            addCriterion("score_improve is not null");
            return (Criteria) this;
        }

        public Criteria andScoreImproveEqualTo(Integer value) {
            addCriterion("score_improve =", value, "scoreImprove");
            return (Criteria) this;
        }

        public Criteria andScoreImproveNotEqualTo(Integer value) {
            addCriterion("score_improve <>", value, "scoreImprove");
            return (Criteria) this;
        }

        public Criteria andScoreImproveGreaterThan(Integer value) {
            addCriterion("score_improve >", value, "scoreImprove");
            return (Criteria) this;
        }

        public Criteria andScoreImproveGreaterThanOrEqualTo(Integer value) {
            addCriterion("score_improve >=", value, "scoreImprove");
            return (Criteria) this;
        }

        public Criteria andScoreImproveLessThan(Integer value) {
            addCriterion("score_improve <", value, "scoreImprove");
            return (Criteria) this;
        }

        public Criteria andScoreImproveLessThanOrEqualTo(Integer value) {
            addCriterion("score_improve <=", value, "scoreImprove");
            return (Criteria) this;
        }

        public Criteria andScoreImproveIn(List<Integer> values) {
            addCriterion("score_improve in", values, "scoreImprove");
            return (Criteria) this;
        }

        public Criteria andScoreImproveNotIn(List<Integer> values) {
            addCriterion("score_improve not in", values, "scoreImprove");
            return (Criteria) this;
        }

        public Criteria andScoreImproveBetween(Integer value1, Integer value2) {
            addCriterion("score_improve between", value1, value2, "scoreImprove");
            return (Criteria) this;
        }

        public Criteria andScoreImproveNotBetween(Integer value1, Integer value2) {
            addCriterion("score_improve not between", value1, value2, "scoreImprove");
            return (Criteria) this;
        }

        public Criteria andTrainResultIsNull() {
            addCriterion("train_result is null");
            return (Criteria) this;
        }

        public Criteria andTrainResultIsNotNull() {
            addCriterion("train_result is not null");
            return (Criteria) this;
        }

        public Criteria andTrainResultEqualTo(String value) {
            addCriterion("train_result =", value, "trainResult");
            return (Criteria) this;
        }

        public Criteria andTrainResultNotEqualTo(String value) {
            addCriterion("train_result <>", value, "trainResult");
            return (Criteria) this;
        }

        public Criteria andTrainResultGreaterThan(String value) {
            addCriterion("train_result >", value, "trainResult");
            return (Criteria) this;
        }

        public Criteria andTrainResultGreaterThanOrEqualTo(String value) {
            addCriterion("train_result >=", value, "trainResult");
            return (Criteria) this;
        }

        public Criteria andTrainResultLessThan(String value) {
            addCriterion("train_result <", value, "trainResult");
            return (Criteria) this;
        }

        public Criteria andTrainResultLessThanOrEqualTo(String value) {
            addCriterion("train_result <=", value, "trainResult");
            return (Criteria) this;
        }

        public Criteria andTrainResultLike(String value) {
            addCriterion("train_result like", value, "trainResult");
            return (Criteria) this;
        }

        public Criteria andTrainResultNotLike(String value) {
            addCriterion("train_result not like", value, "trainResult");
            return (Criteria) this;
        }

        public Criteria andTrainResultIn(List<String> values) {
            addCriterion("train_result in", values, "trainResult");
            return (Criteria) this;
        }

        public Criteria andTrainResultNotIn(List<String> values) {
            addCriterion("train_result not in", values, "trainResult");
            return (Criteria) this;
        }

        public Criteria andTrainResultBetween(String value1, String value2) {
            addCriterion("train_result between", value1, value2, "trainResult");
            return (Criteria) this;
        }

        public Criteria andTrainResultNotBetween(String value1, String value2) {
            addCriterion("train_result not between", value1, value2, "trainResult");
            return (Criteria) this;
        }

        public Criteria andActivityIsNull() {
            addCriterion("activity is null");
            return (Criteria) this;
        }

        public Criteria andActivityIsNotNull() {
            addCriterion("activity is not null");
            return (Criteria) this;
        }

        public Criteria andActivityEqualTo(Integer value) {
            addCriterion("activity =", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityNotEqualTo(Integer value) {
            addCriterion("activity <>", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityGreaterThan(Integer value) {
            addCriterion("activity >", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityGreaterThanOrEqualTo(Integer value) {
            addCriterion("activity >=", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityLessThan(Integer value) {
            addCriterion("activity <", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityLessThanOrEqualTo(Integer value) {
            addCriterion("activity <=", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityIn(List<Integer> values) {
            addCriterion("activity in", values, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityNotIn(List<Integer> values) {
            addCriterion("activity not in", values, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityBetween(Integer value1, Integer value2) {
            addCriterion("activity between", value1, value2, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityNotBetween(Integer value1, Integer value2) {
            addCriterion("activity not between", value1, value2, "activity");
            return (Criteria) this;
        }

        public Criteria andParentTrainTypeIsNull() {
            addCriterion("parent_train_type is null");
            return (Criteria) this;
        }

        public Criteria andParentTrainTypeIsNotNull() {
            addCriterion("parent_train_type is not null");
            return (Criteria) this;
        }

        public Criteria andParentTrainTypeEqualTo(String value) {
            addCriterion("parent_train_type =", value, "parentTrainType");
            return (Criteria) this;
        }

        public Criteria andParentTrainTypeNotEqualTo(String value) {
            addCriterion("parent_train_type <>", value, "parentTrainType");
            return (Criteria) this;
        }

        public Criteria andParentTrainTypeGreaterThan(String value) {
            addCriterion("parent_train_type >", value, "parentTrainType");
            return (Criteria) this;
        }

        public Criteria andParentTrainTypeGreaterThanOrEqualTo(String value) {
            addCriterion("parent_train_type >=", value, "parentTrainType");
            return (Criteria) this;
        }

        public Criteria andParentTrainTypeLessThan(String value) {
            addCriterion("parent_train_type <", value, "parentTrainType");
            return (Criteria) this;
        }

        public Criteria andParentTrainTypeLessThanOrEqualTo(String value) {
            addCriterion("parent_train_type <=", value, "parentTrainType");
            return (Criteria) this;
        }

        public Criteria andParentTrainTypeLike(String value) {
            addCriterion("parent_train_type like", value, "parentTrainType");
            return (Criteria) this;
        }

        public Criteria andParentTrainTypeNotLike(String value) {
            addCriterion("parent_train_type not like", value, "parentTrainType");
            return (Criteria) this;
        }

        public Criteria andParentTrainTypeIn(List<String> values) {
            addCriterion("parent_train_type in", values, "parentTrainType");
            return (Criteria) this;
        }

        public Criteria andParentTrainTypeNotIn(List<String> values) {
            addCriterion("parent_train_type not in", values, "parentTrainType");
            return (Criteria) this;
        }

        public Criteria andParentTrainTypeBetween(String value1, String value2) {
            addCriterion("parent_train_type between", value1, value2, "parentTrainType");
            return (Criteria) this;
        }

        public Criteria andParentTrainTypeNotBetween(String value1, String value2) {
            addCriterion("parent_train_type not between", value1, value2, "parentTrainType");
            return (Criteria) this;
        }

        public Criteria andSatisfactionTrainIsNull() {
            addCriterion("satisfaction_train is null");
            return (Criteria) this;
        }

        public Criteria andSatisfactionTrainIsNotNull() {
            addCriterion("satisfaction_train is not null");
            return (Criteria) this;
        }

        public Criteria andSatisfactionTrainEqualTo(String value) {
            addCriterion("satisfaction_train =", value, "satisfactionTrain");
            return (Criteria) this;
        }

        public Criteria andSatisfactionTrainNotEqualTo(String value) {
            addCriterion("satisfaction_train <>", value, "satisfactionTrain");
            return (Criteria) this;
        }

        public Criteria andSatisfactionTrainGreaterThan(String value) {
            addCriterion("satisfaction_train >", value, "satisfactionTrain");
            return (Criteria) this;
        }

        public Criteria andSatisfactionTrainGreaterThanOrEqualTo(String value) {
            addCriterion("satisfaction_train >=", value, "satisfactionTrain");
            return (Criteria) this;
        }

        public Criteria andSatisfactionTrainLessThan(String value) {
            addCriterion("satisfaction_train <", value, "satisfactionTrain");
            return (Criteria) this;
        }

        public Criteria andSatisfactionTrainLessThanOrEqualTo(String value) {
            addCriterion("satisfaction_train <=", value, "satisfactionTrain");
            return (Criteria) this;
        }

        public Criteria andSatisfactionTrainLike(String value) {
            addCriterion("satisfaction_train like", value, "satisfactionTrain");
            return (Criteria) this;
        }

        public Criteria andSatisfactionTrainNotLike(String value) {
            addCriterion("satisfaction_train not like", value, "satisfactionTrain");
            return (Criteria) this;
        }

        public Criteria andSatisfactionTrainIn(List<String> values) {
            addCriterion("satisfaction_train in", values, "satisfactionTrain");
            return (Criteria) this;
        }

        public Criteria andSatisfactionTrainNotIn(List<String> values) {
            addCriterion("satisfaction_train not in", values, "satisfactionTrain");
            return (Criteria) this;
        }

        public Criteria andSatisfactionTrainBetween(String value1, String value2) {
            addCriterion("satisfaction_train between", value1, value2, "satisfactionTrain");
            return (Criteria) this;
        }

        public Criteria andSatisfactionTrainNotBetween(String value1, String value2) {
            addCriterion("satisfaction_train not between", value1, value2, "satisfactionTrain");
            return (Criteria) this;
        }

        public Criteria andSatisfactionRecoveryIsNull() {
            addCriterion("satisfaction_recovery is null");
            return (Criteria) this;
        }

        public Criteria andSatisfactionRecoveryIsNotNull() {
            addCriterion("satisfaction_recovery is not null");
            return (Criteria) this;
        }

        public Criteria andSatisfactionRecoveryEqualTo(String value) {
            addCriterion("satisfaction_recovery =", value, "satisfactionRecovery");
            return (Criteria) this;
        }

        public Criteria andSatisfactionRecoveryNotEqualTo(String value) {
            addCriterion("satisfaction_recovery <>", value, "satisfactionRecovery");
            return (Criteria) this;
        }

        public Criteria andSatisfactionRecoveryGreaterThan(String value) {
            addCriterion("satisfaction_recovery >", value, "satisfactionRecovery");
            return (Criteria) this;
        }

        public Criteria andSatisfactionRecoveryGreaterThanOrEqualTo(String value) {
            addCriterion("satisfaction_recovery >=", value, "satisfactionRecovery");
            return (Criteria) this;
        }

        public Criteria andSatisfactionRecoveryLessThan(String value) {
            addCriterion("satisfaction_recovery <", value, "satisfactionRecovery");
            return (Criteria) this;
        }

        public Criteria andSatisfactionRecoveryLessThanOrEqualTo(String value) {
            addCriterion("satisfaction_recovery <=", value, "satisfactionRecovery");
            return (Criteria) this;
        }

        public Criteria andSatisfactionRecoveryLike(String value) {
            addCriterion("satisfaction_recovery like", value, "satisfactionRecovery");
            return (Criteria) this;
        }

        public Criteria andSatisfactionRecoveryNotLike(String value) {
            addCriterion("satisfaction_recovery not like", value, "satisfactionRecovery");
            return (Criteria) this;
        }

        public Criteria andSatisfactionRecoveryIn(List<String> values) {
            addCriterion("satisfaction_recovery in", values, "satisfactionRecovery");
            return (Criteria) this;
        }

        public Criteria andSatisfactionRecoveryNotIn(List<String> values) {
            addCriterion("satisfaction_recovery not in", values, "satisfactionRecovery");
            return (Criteria) this;
        }

        public Criteria andSatisfactionRecoveryBetween(String value1, String value2) {
            addCriterion("satisfaction_recovery between", value1, value2, "satisfactionRecovery");
            return (Criteria) this;
        }

        public Criteria andSatisfactionRecoveryNotBetween(String value1, String value2) {
            addCriterion("satisfaction_recovery not between", value1, value2, "satisfactionRecovery");
            return (Criteria) this;
        }

        public Criteria andSuggestionIsNull() {
            addCriterion("suggestion is null");
            return (Criteria) this;
        }

        public Criteria andSuggestionIsNotNull() {
            addCriterion("suggestion is not null");
            return (Criteria) this;
        }

        public Criteria andSuggestionEqualTo(String value) {
            addCriterion("suggestion =", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotEqualTo(String value) {
            addCriterion("suggestion <>", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionGreaterThan(String value) {
            addCriterion("suggestion >", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionGreaterThanOrEqualTo(String value) {
            addCriterion("suggestion >=", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionLessThan(String value) {
            addCriterion("suggestion <", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionLessThanOrEqualTo(String value) {
            addCriterion("suggestion <=", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionLike(String value) {
            addCriterion("suggestion like", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotLike(String value) {
            addCriterion("suggestion not like", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionIn(List<String> values) {
            addCriterion("suggestion in", values, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotIn(List<String> values) {
            addCriterion("suggestion not in", values, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionBetween(String value1, String value2) {
            addCriterion("suggestion between", value1, value2, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotBetween(String value1, String value2) {
            addCriterion("suggestion not between", value1, value2, "suggestion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_year_summary
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 06 11:35:11 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sd_year_summary
     *
     * @mbggenerated Tue Aug 06 11:35:11 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}