package com.xingyu.mapper;

import com.xingyu.domain.po.SdArchiveInfo;
import com.xingyu.domain.po.SdArchiveInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SdArchiveInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_archive_info
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    int countByExample(SdArchiveInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_archive_info
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    int deleteByExample(SdArchiveInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_archive_info
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    int deleteByPrimaryKey(String archiveNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_archive_info
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    int insert(SdArchiveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_archive_info
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    int insertSelective(SdArchiveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_archive_info
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    List<SdArchiveInfo> selectByExample(SdArchiveInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_archive_info
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    SdArchiveInfo selectByPrimaryKey(String archiveNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_archive_info
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") SdArchiveInfo record, @Param("example") SdArchiveInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_archive_info
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    int updateByExample(@Param("record") SdArchiveInfo record, @Param("example") SdArchiveInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_archive_info
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    int updateByPrimaryKeySelective(SdArchiveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_archive_info
     *
     * @mbggenerated Sun Jul 21 22:42:42 CST 2019
     */
    int updateByPrimaryKey(SdArchiveInfo record);
}