package com.xingyu.mapper;

import com.xingyu.domain.po.SdAssessTimes;
import com.xingyu.domain.po.SdAssessTimesExample;
import com.xingyu.domain.po.SdAssessTimesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SdAssessTimesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int countByExample(SdAssessTimesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int deleteByExample(SdAssessTimesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int deleteByPrimaryKey(SdAssessTimesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int insert(SdAssessTimes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int insertSelective(SdAssessTimes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    List<SdAssessTimes> selectByExample(SdAssessTimesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    SdAssessTimes selectByPrimaryKey(SdAssessTimesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") SdAssessTimes record, @Param("example") SdAssessTimesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int updateByExample(@Param("record") SdAssessTimes record, @Param("example") SdAssessTimesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int updateByPrimaryKeySelective(SdAssessTimes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_times
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int updateByPrimaryKey(SdAssessTimes record);
}