package com.xingyu.mapper;

import com.xingyu.domain.po.SdAssessScore;
import com.xingyu.domain.po.SdAssessScoreExample;
import com.xingyu.domain.po.SdAssessScoreKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SdAssessScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_score
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    int countByExample(SdAssessScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_score
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    int deleteByExample(SdAssessScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_score
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    int deleteByPrimaryKey(SdAssessScoreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_score
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    int insert(SdAssessScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_score
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    int insertSelective(SdAssessScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_score
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    List<SdAssessScore> selectByExample(SdAssessScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_score
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    SdAssessScore selectByPrimaryKey(SdAssessScoreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_score
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") SdAssessScore record, @Param("example") SdAssessScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_score
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    int updateByExample(@Param("record") SdAssessScore record, @Param("example") SdAssessScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_score
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    int updateByPrimaryKeySelective(SdAssessScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_assess_score
     *
     * @mbggenerated Tue Jul 30 23:38:17 CST 2019
     */
    int updateByPrimaryKey(SdAssessScore record);
}