package com.xingyu.mapper;

import com.xingyu.domain.po.SdMonthRecord;
import com.xingyu.domain.po.SdMonthRecordExample;
import com.xingyu.domain.po.SdMonthRecordKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SdMonthRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_month_record
     *
     * @mbggenerated Sat Aug 03 11:43:26 CST 2019
     */
    int countByExample(SdMonthRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_month_record
     *
     * @mbggenerated Sat Aug 03 11:43:26 CST 2019
     */
    int deleteByExample(SdMonthRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_month_record
     *
     * @mbggenerated Sat Aug 03 11:43:26 CST 2019
     */
    int deleteByPrimaryKey(SdMonthRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_month_record
     *
     * @mbggenerated Sat Aug 03 11:43:26 CST 2019
     */
    int insert(SdMonthRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_month_record
     *
     * @mbggenerated Sat Aug 03 11:43:26 CST 2019
     */
    int insertSelective(SdMonthRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_month_record
     *
     * @mbggenerated Sat Aug 03 11:43:26 CST 2019
     */
    List<SdMonthRecord> selectByExample(SdMonthRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_month_record
     *
     * @mbggenerated Sat Aug 03 11:43:26 CST 2019
     */
    SdMonthRecord selectByPrimaryKey(SdMonthRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_month_record
     *
     * @mbggenerated Sat Aug 03 11:43:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") SdMonthRecord record, @Param("example") SdMonthRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_month_record
     *
     * @mbggenerated Sat Aug 03 11:43:26 CST 2019
     */
    int updateByExample(@Param("record") SdMonthRecord record, @Param("example") SdMonthRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_month_record
     *
     * @mbggenerated Sat Aug 03 11:43:26 CST 2019
     */
    int updateByPrimaryKeySelective(SdMonthRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_month_record
     *
     * @mbggenerated Sat Aug 03 11:43:26 CST 2019
     */
    int updateByPrimaryKey(SdMonthRecord record);
}