package com.xingyu.mapper;

import com.xingyu.domain.po.SdProgressReport;
import com.xingyu.domain.po.SdProgressReportExample;
import com.xingyu.domain.po.SdProgressReportKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SdProgressReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_progress_report
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int countByExample(SdProgressReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_progress_report
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int deleteByExample(SdProgressReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_progress_report
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int deleteByPrimaryKey(SdProgressReportKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_progress_report
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int insert(SdProgressReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_progress_report
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int insertSelective(SdProgressReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_progress_report
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    List<SdProgressReport> selectByExample(SdProgressReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_progress_report
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    SdProgressReport selectByPrimaryKey(SdProgressReportKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_progress_report
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") SdProgressReport record, @Param("example") SdProgressReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_progress_report
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int updateByExample(@Param("record") SdProgressReport record, @Param("example") SdProgressReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_progress_report
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int updateByPrimaryKeySelective(SdProgressReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_progress_report
     *
     * @mbggenerated Fri Aug 02 23:23:12 CST 2019
     */
    int updateByPrimaryKey(SdProgressReport record);
}