package com.xingyu.mapper;

import com.xingyu.domain.po.SdTrainningRecord;
import com.xingyu.domain.po.SdTrainningRecordExample;
import com.xingyu.domain.po.SdTrainningRecordKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SdTrainningRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_trainning_record
     *
     * @mbggenerated Thu Aug 01 22:52:03 CST 2019
     */
    int countByExample(SdTrainningRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_trainning_record
     *
     * @mbggenerated Thu Aug 01 22:52:03 CST 2019
     */
    int deleteByExample(SdTrainningRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_trainning_record
     *
     * @mbggenerated Thu Aug 01 22:52:03 CST 2019
     */
    int deleteByPrimaryKey(SdTrainningRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_trainning_record
     *
     * @mbggenerated Thu Aug 01 22:52:03 CST 2019
     */
    int insert(SdTrainningRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_trainning_record
     *
     * @mbggenerated Thu Aug 01 22:52:03 CST 2019
     */
    int insertSelective(SdTrainningRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_trainning_record
     *
     * @mbggenerated Thu Aug 01 22:52:03 CST 2019
     */
    List<SdTrainningRecord> selectByExample(SdTrainningRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_trainning_record
     *
     * @mbggenerated Thu Aug 01 22:52:03 CST 2019
     */
    SdTrainningRecord selectByPrimaryKey(SdTrainningRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_trainning_record
     *
     * @mbggenerated Thu Aug 01 22:52:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") SdTrainningRecord record, @Param("example") SdTrainningRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_trainning_record
     *
     * @mbggenerated Thu Aug 01 22:52:03 CST 2019
     */
    int updateByExample(@Param("record") SdTrainningRecord record, @Param("example") SdTrainningRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_trainning_record
     *
     * @mbggenerated Thu Aug 01 22:52:03 CST 2019
     */
    int updateByPrimaryKeySelective(SdTrainningRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_trainning_record
     *
     * @mbggenerated Thu Aug 01 22:52:03 CST 2019
     */
    int updateByPrimaryKey(SdTrainningRecord record);
}