package com.xingyu.mapper;

import com.xingyu.domain.po.SysParams;
import com.xingyu.domain.po.SysParamsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysParamsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Tue Jul 16 23:37:03 CST 2019
     */
    int countByExample(SysParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Tue Jul 16 23:37:03 CST 2019
     */
    int deleteByExample(SysParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Tue Jul 16 23:37:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Tue Jul 16 23:37:03 CST 2019
     */
    int insert(SysParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Tue Jul 16 23:37:03 CST 2019
     */
    int insertSelective(SysParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Tue Jul 16 23:37:03 CST 2019
     */
    List<SysParams> selectByExample(SysParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Tue Jul 16 23:37:03 CST 2019
     */
    SysParams selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Tue Jul 16 23:37:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysParams record, @Param("example") SysParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Tue Jul 16 23:37:03 CST 2019
     */
    int updateByExample(@Param("record") SysParams record, @Param("example") SysParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Tue Jul 16 23:37:03 CST 2019
     */
    int updateByPrimaryKeySelective(SysParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_params
     *
     * @mbggenerated Tue Jul 16 23:37:03 CST 2019
     */
    int updateByPrimaryKey(SysParams record);
}